const { withNx } = require('@nx/rollup/with-nx');

module.exports = withNx(
  {
    main: './src/index.ts',
    // Optional-peer entry point: the pure `.xlsx` builder both render layers
    // share. A separate entry so `exceljs` is pulled in only by an app that
    // actually imports it.
    // note: workspace-relative, and the file name becomes the entry name —
    // `<dir>/index.ts` would collide with the main `index` entry
    additionalEntryPoints: ['packages/pivot-engine/src/export-excel.ts'],
    outputPath: '../../dist/packages/pivot-engine',
    tsConfig: './tsconfig.lib.json',
    compiler: 'swc',
    format: ['cjs', 'esm'],
    // note: '{projectRoot}' tokens are not interpolated inside rollup.config —
    // the path must be spelled out relative to the workspace root
    assets: [
      { input: 'packages/pivot-engine', output: '.', glob: '*.md' },
      { input: 'packages/pivot-engine', output: '.', glob: 'LICENSE' },
      // machine-readable API reference for coding assistants — generated by
      // `nx run docs-tools:llms`, read from node_modules/@oge-ui/pivot-engine/llms.txt
      { input: 'packages/pivot-engine', output: '.', glob: 'llms.txt' },
    ],
  },
  {},
);
