import type { DocsFramework } from '../framework.service';

/**
 * The shape of `public/search-index.json`, generated by
 * `tools/docs-tools/lib/search-index.mjs` (`npx nx run docs-tools:llms`).
 * Sections and API blocks point at their page by index into `pages`.
 */
export interface SearchIndexFile {
  readonly version: 1;
  readonly pages: readonly {
    readonly p: string;
    readonly t: string;
    readonly c?: string;
    readonly d?: string;
  }[];
  readonly sections: readonly {
    readonly p: number;
    readonly a: string;
    readonly t: string;
    readonly f?: DocsFramework;
  }[];
  readonly api: readonly {
    readonly p: number;
    readonly a: string;
    readonly t: string;
    readonly o: string;
    readonly f?: DocsFramework;
    readonly m: Readonly<Record<string, readonly string[]>>;
  }[];
}

export type SearchKind = 'page' | 'section' | 'api';

/** One searchable thing — a page, a heading on a page or an API member. */
export interface SearchItem {
  readonly kind: SearchKind;
  readonly title: string;
  /** Where it lives: the family, the page, or the API block. */
  readonly context: string;
  /** Secondary text: a page's description, an API member's table. */
  readonly detail: string;
  readonly path: string;
  readonly anchor?: string;
  /** Only this render layer has it; `undefined` = whatever the page covers. */
  readonly framework?: DocsFramework;
  /** Lower-cased title, matched first. */
  readonly key: string;
  /** Lower-cased context + detail, matched for multi-word queries. */
  readonly extra: string;
}

export interface SearchResult {
  readonly item: SearchItem;
  readonly score: number;
  /** Whether the item exists in the reader's active framework. */
  readonly inFramework: boolean;
  /** The frameworks it exists in, for the badge. */
  readonly frameworks: readonly DocsFramework[];
  /** `[start, end)` of the best title match, for highlighting. */
  readonly match: readonly [number, number] | null;
}

export interface SearchGroup {
  readonly kind: SearchKind;
  readonly label: string;
  readonly results: readonly SearchResult[];
}

const TABLE_LABEL: Readonly<Record<string, string>> = {
  properties: 'Property',
  methods: 'Method',
  events: 'Event',
  types: 'Type',
};

/** Expands the compact index file into a flat list of searchable items. */
export function flattenIndex(file: SearchIndexFile): SearchItem[] {
  const items: SearchItem[] = [];
  const add = (
    item: Omit<SearchItem, 'key' | 'extra'> & { key?: string },
  ): void => {
    items.push({
      ...item,
      key: item.title.toLowerCase(),
      extra: `${item.context} ${item.detail}`.toLowerCase(),
    });
  };
  for (const page of file.pages) {
    add({
      kind: 'page',
      title: page.t,
      context: page.c ?? '',
      detail: page.d ?? '',
      path: page.p,
    });
  }
  for (const section of file.sections) {
    const page = file.pages[section.p];
    if (!page) continue;
    add({
      kind: 'section',
      title: section.t,
      context: page.c && page.c !== page.t ? `${page.c} › ${page.t}` : page.t,
      detail: '',
      path: page.p,
      anchor: section.a,
      framework: section.f,
    });
  }
  for (const block of file.api) {
    const page = file.pages[block.p];
    if (!page) continue;
    add({
      kind: 'api',
      title: block.t,
      context: block.o,
      detail: 'API reference',
      path: page.p,
      anchor: block.a,
      framework: block.f,
    });
    for (const [table, names] of Object.entries(block.m)) {
      for (const name of names) {
        add({
          kind: 'api',
          title: name,
          context: block.t,
          detail: TABLE_LABEL[table] ?? table,
          path: page.p,
          anchor: `${block.a}-${table}`,
          framework: block.f,
        });
      }
    }
  }
  return items;
}

/**
 * How well `term` (lower-case) matches `text`: exact > prefix > word start
 * (after punctuation, a space or a camelCase hump) > substring. Returns the
 * score and where it matched; `0` when it does not occur.
 */
export function matchTerm(
  text: string,
  lower: string,
  term: string,
): { score: number; at: number } {
  if (!term) return { score: 0, at: -1 };
  if (lower === term) return { score: 100, at: 0 };
  if (lower.startsWith(term)) return { score: 80, at: 0 };
  let first = -1;
  let from = 0;
  for (;;) {
    const at = lower.indexOf(term, from);
    if (at < 0) break;
    if (first < 0) first = at;
    if (isWordStart(text, at)) return { score: 60, at };
    from = at + 1;
  }
  return first < 0 ? { score: 0, at: -1 } : { score: 40, at: first };
}

function isWordStart(text: string, at: number): boolean {
  if (at === 0) return true;
  const previous = text[at - 1];
  const current = text[at];
  if (!/[a-z0-9]/i.test(previous)) return true;
  // camelCase hump: `valueChange` matches "change" at a word start
  return /[a-z0-9]/.test(previous) && /[A-Z]/.test(current);
}

const KIND_BONUS: Readonly<Record<SearchKind, number>> = {
  page: 8,
  section: 4,
  api: 0,
};

/**
 * Scores one item against the query terms. Every term must match the title or
 * the context/detail; a title match is worth far more. `null` = no match.
 */
export function scoreItem(
  item: SearchItem,
  terms: readonly string[],
): { score: number; match: [number, number] | null } | null {
  let total = 0;
  let match: [number, number] | null = null;
  for (const term of terms) {
    const title = matchTerm(item.title, item.key, term);
    if (title.score > 0) {
      total += title.score;
      if (!match) match = [title.at, title.at + term.length];
      continue;
    }
    if (item.extra.includes(term)) {
      total += 10;
      continue;
    }
    return null;
  }
  // the whole query as typed, inside the title, beats scattered words
  const phrase = terms.join(' ');
  if (terms.length > 1 && item.key.includes(phrase)) total += 30;
  total += KIND_BONUS[item.kind];
  total -= Math.min(item.title.length, 60) / 10;
  return { score: total, match };
}

/** Splits a raw query into lower-case terms. */
export function queryTerms(query: string): string[] {
  return query.trim().toLowerCase().split(/\s+/).filter(Boolean);
}

const GROUPS: readonly { kind: SearchKind; label: string; limit: number }[] = [
  { kind: 'page', label: 'Pages', limit: 6 },
  { kind: 'section', label: 'Sections', limit: 8 },
  { kind: 'api', label: 'API', limit: 10 },
];

/**
 * Ranks every item against `query` and returns the grouped results. Items the
 * active framework has come first within each group; the rest follow, still
 * ranked, so a React reader searching for an Angular-only page still finds it.
 */
export function searchItems(
  items: readonly SearchItem[],
  query: string,
  framework: DocsFramework,
  frameworksOf: (item: SearchItem) => readonly DocsFramework[],
): SearchGroup[] {
  const terms = queryTerms(query);
  if (!terms.length) return [];
  const byKind = new Map<SearchKind, SearchResult[]>();
  for (const item of items) {
    const scored = scoreItem(item, terms);
    if (!scored) continue;
    const frameworks = frameworksOf(item);
    const list = byKind.get(item.kind) ?? [];
    list.push({
      item,
      score: scored.score,
      match: scored.match,
      frameworks,
      inFramework: frameworks.includes(framework),
    });
    byKind.set(item.kind, list);
  }
  const groups: SearchGroup[] = [];
  for (const { kind, label, limit } of GROUPS) {
    const list = byKind.get(kind);
    if (!list?.length) continue;
    list.sort(
      (a, b) =>
        Number(b.inFramework) - Number(a.inFramework) ||
        b.score - a.score ||
        a.item.title.length - b.item.title.length ||
        a.item.title.localeCompare(b.item.title),
    );
    groups.push({ kind, label, results: dedupe(list).slice(0, limit) });
  }
  return groups;
}

/** One result per destination + title: an API row listed for both layers. */
function dedupe(list: readonly SearchResult[]): SearchResult[] {
  const seen = new Set<string>();
  const out: SearchResult[] = [];
  for (const result of list) {
    const { item } = result;
    const key = `${item.path}#${item.anchor ?? ''}|${item.title}|${item.context}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(result);
  }
  return out;
}

/** The URL a result opens: path, the framework query and the anchor. */
export function resultUrl(
  item: Pick<SearchItem, 'path' | 'anchor'>,
  framework: DocsFramework,
): string {
  const query = framework === 'angular' ? '' : `?framework=${framework}`;
  return `${item.path}${query}${item.anchor ? `#${item.anchor}` : ''}`;
}
