// Editor
export {
  OgeBpmnEditor,
  type OgeBpmnEditorHandle,
  type OgeBpmnEditorProps,
} from './lib/bpmn-editor';
export type { OgeBpmnPropertiesEntryRenderContext } from './lib/bpmn-properties';

// Config — the React counterpart of `provideOgeBpmnConfig()`
export {
  OgeBpmnConfigProvider,
  useOgeBpmnConfig,
  type OgeBpmnConfigProviderProps,
} from './lib/bpmn-config';

// The message catalog, the defaults, the event payloads and the engine
// surface users need for import/export and model inspection are
// single-sourced in `@oge-ui/bpmn-engine` (ADR 0003) — shared with the Angular
// editor and re-exported here so React consumers import one package: the same
// surface the Angular barrel exposes.
export {
  OGE_DEFAULT_BPMN_COLOR_PRESETS,
  OGE_DEFAULT_BPMN_CONFIG,
  OGE_DEFAULT_BPMN_MESSAGES,
  VALID_EVENT_DEFINITIONS,
  alignElements,
  createEmptyDiagram,
  distributeElements,
  fromBpmnJson,
  readBpmnXml,
  renderDiagramSvg,
  toBpmnJson,
  writeBpmnXml,
  type BpmnActivityMarker,
  type BpmnAlignMode,
  type BpmnClipboard,
  type BpmnDataNodeType,
  type BpmnDiagram,
  type BpmnDiagramJson,
  type BpmnDistributeAxis,
  type BpmnEdge,
  type BpmnEdgeType,
  type BpmnElementNameKey,
  type BpmnEventDefinitionKind,
  type BpmnImportResult,
  type BpmnImportWarning,
  type BpmnImportWarningCode,
  type BpmnJsonParseResult,
  type BpmnLane,
  type BpmnMessageFlow,
  type BpmnNode,
  type BpmnNodeType,
  type BpmnPaletteItemType,
  type BpmnPool,
  type BpmnSubProcessType,
  type BpmnSvgExportOptions,
  type OgeBpmnAnnouncementMessages,
  type OgeBpmnChangeSource,
  type OgeBpmnConfig,
  type OgeBpmnConfigInput,
  type OgeBpmnContextPadMessages,
  type OgeBpmnDiagramChangedEvent,
  type OgeBpmnEditorMode,
  type OgeBpmnElementInfo,
  type OgeBpmnElementsChangedEvent,
  type OgeBpmnHeaderMessages,
  type OgeBpmnImportEvent,
  type OgeBpmnMessages,
  type OgeBpmnOverlay,
  type OgeBpmnPaletteItem,
  type OgeBpmnPropertiesMessages,
  type OgeBpmnSelectionEvent,
  type Point,
  type Rect,
} from '@oge-ui/bpmn-engine';

// G5b — validation, extensibility, Camunda / Zeebe (engine surface)
export {
  OGE_BPMN_CAMUNDA7_PROVIDER,
  OGE_BPMN_CAMUNDA_PROVIDERS,
  OGE_BPMN_DEFAULT_LINT_RULES,
  OGE_BPMN_ZEEBE_PROVIDER,
  applyElementTemplateCommand,
  bpmnElementTemplatesProvider,
  bpmnForeignAttribute,
  bpmnSvg,
  lintBpmnDiagram,
  setDocumentationCommand,
  setElementColorsCommand,
  setForeignAttributeCommand,
  type OgeBpmnCamundaMessages,
  type OgeBpmnContextPadEntry,
  type OgeBpmnContextPadProvider,
  type OgeBpmnEditorApi,
  type OgeBpmnElementRenderer,
  type OgeBpmnElementTemplate,
  type OgeBpmnExtensionMessages,
  type OgeBpmnLintChangedEvent,
  type OgeBpmnLintIssue,
  type OgeBpmnLintMessages,
  type OgeBpmnLintRule,
  type OgeBpmnLintRuleMessages,
  type OgeBpmnLintRuleOverride,
  type OgeBpmnLintRulesInput,
  type OgeBpmnLintSeverity,
  type OgeBpmnPaletteEntry,
  type OgeBpmnPaletteProvider,
  type OgeBpmnPngExportOptions,
  type OgeBpmnPropertiesEntry,
  type OgeBpmnPropertiesGroup,
  type OgeBpmnPropertiesProvider,
  type OgeBpmnPropertiesValue,
  type OgeBpmnRenderContext,
  type OgeBpmnRenderers,
  type OgeBpmnSvgNode,
  type OgeBpmnTemplateProperty,
} from '@oge-ui/bpmn-engine';
