const { withNx } = require('@nx/rollup/with-nx');

module.exports = withNx(
  {
    main: './src/index.ts',
    // Optional-peer entry points: the pure `.xlsx` / `.pdf` / `.png` builders
    // shared by both Gantt render layers. Separate entries so `exceljs` and
    // `jspdf` are pulled in only by an app that actually imports one of them.
    // note: workspace-relative, and each file name becomes the entry name —
    // `<dir>/index.ts` would collide with the main `index` entry
    additionalEntryPoints: [
      'packages/gantt-engine/src/export-excel.ts',
      'packages/gantt-engine/src/export-pdf.ts',
      'packages/gantt-engine/src/export-image.ts',
      // no peer: separate only so the MS Project reader/writer stays lazy
      'packages/gantt-engine/src/export-msproject.ts',
    ],
    outputPath: '../../dist/packages/gantt-engine',
    tsConfig: './tsconfig.lib.json',
    compiler: 'swc',
    format: ['cjs', 'esm'],
    // note: '{projectRoot}' tokens are not interpolated inside rollup.config —
    // the path must be spelled out relative to the workspace root
    assets: [
      { input: 'packages/gantt-engine', output: '.', glob: '*.md' },
      { input: 'packages/gantt-engine', output: '.', glob: 'LICENSE' },
      // machine-readable API reference for coding assistants — generated by
      // `nx run docs-tools:llms`, read from node_modules/@oge-ui/gantt-engine/llms.txt
      { input: 'packages/gantt-engine', output: '.', glob: 'llms.txt' },
    ],
  },
  {},
);
