const { withNx } = require('@nx/rollup/with-nx');

module.exports = withNx(
  {
    main: './src/index.ts',
    // The image exporter is its own entry, like the Angular package's
    // `/export-image` secondary entry: an app that never exports an image
    // never loads the serializer. `/export-pdf` is the only module that
    // imports the optional peers `jspdf` and `@oge-ui/behavior`.
    // note: workspace-relative, and each file name becomes the entry name —
    // `<dir>/index.ts` would collide with the main `index` entry
    additionalEntryPoints: [
      'packages/charts-engine/src/export-image.ts',
      'packages/charts-engine/src/export-pdf.ts',
    ],
    outputPath: '../../dist/packages/charts-engine',
    tsConfig: './tsconfig.lib.json',
    compiler: 'swc',
    format: ['cjs', 'esm'],
    // note: '{projectRoot}' tokens are not interpolated inside rollup.config —
    // the path must be spelled out relative to the workspace root
    assets: [
      { input: 'packages/charts-engine', output: '.', glob: '*.md' },
      { input: 'packages/charts-engine', output: '.', glob: 'LICENSE' },
      // machine-readable API reference for coding assistants — generated by
      // `nx run docs-tools:llms`, read from node_modules/@oge-ui/charts-engine/llms.txt
      { input: 'packages/charts-engine', output: '.', glob: 'llms.txt' },
    ],
  },
  {},
);
