const { withNx } = require('@nx/rollup/with-nx');

/** One entry per language, so an app bundles only the pack it imports. */
const LANGUAGES = [
  'de',
  'fr',
  'es',
  'it',
  'pt-BR',
  'tr',
  'ja',
  'zh-CN',
  'ar',
  'he',
];

module.exports = withNx(
  {
    main: './src/index.ts',
    // note: workspace-relative, and each file name becomes the entry name —
    // `src/tr.ts` is published as `tr.esm.js` / `tr.cjs.js` / `tr.d.ts`, the
    // `./tr` subpath in package.json. The primary entry's `ogeLocalePacks`
    // map imports them dynamically, so runtime switching code-splits too.
    additionalEntryPoints: LANGUAGES.map(
      (code) => `packages/locales/src/${code}.ts`,
    ),
    outputPath: '../../dist/packages/locales',
    tsConfig: './tsconfig.lib.json',
    compiler: 'swc',
    format: ['cjs', 'esm'],
    // note: '{projectRoot}' tokens are not interpolated inside rollup.config —
    // the path must be spelled out relative to the workspace root
    assets: [
      { input: 'packages/locales', output: '.', glob: '*.md' },
      { input: 'packages/locales', output: '.', glob: 'LICENSE' },
      // machine-readable API reference for coding assistants — generated by
      // `nx run docs-tools:llms`, read from node_modules/@oge-ui/locales/llms.txt
      { input: 'packages/locales', output: '.', glob: 'llms.txt' },
    ],
  },
  {},
);
