// Public API of @oge-ui/scheduler-engine (commercial — see LICENSE).
// Framework-free: no Angular or React import anywhere (ADR 0003). Both
// @oge-ui/scheduler and @oge-ui/react-scheduler render from this surface.
// Explicit named exports only (house rule).

export {
  OGE_DEFAULT_SCHEDULER_CONFIG,
  OGE_DEFAULT_SCHEDULER_MESSAGES,
  fillSchedulerMessages,
  resolveOgeSchedulerConfig,
  type OgeSchedulerAnnouncementMessages,
  type OgeSchedulerConfig,
  type OgeSchedulerConfigInput,
  type OgeSchedulerEditorMessages,
  type OgeSchedulerExportMessages,
  type OgeSchedulerGridMessages,
  type OgeSchedulerMenuMessages,
  type OgeSchedulerMessages,
  type OgeSchedulerPopupMessages,
  type OgeSchedulerRecurrenceScopeMessages,
  type OgeSchedulerResolvedMessages,
  type OgeSchedulerToolbarMessages,
} from './lib/config';
export {
  type OgeSchedulerAppointment,
  type OgeSchedulerAppointmentAddedEvent,
  type OgeSchedulerAppointmentAddingEvent,
  type OgeSchedulerAppointmentClickEvent,
  type OgeSchedulerAppointmentDeletedEvent,
  type OgeSchedulerAppointmentDeletingEvent,
  type OgeSchedulerAppointmentDroppedEvent,
  type OgeSchedulerAppointmentUpdatedEvent,
  type OgeSchedulerAppointmentUpdatingEvent,
  type OgeSchedulerBlockedRange,
  type OgeSchedulerCellClickEvent,
  type OgeSchedulerConflictCheck,
  type OgeSchedulerDisabledSlots,
  type OgeSchedulerDragOutEvent,
  type OgeSchedulerEditorShowingEvent,
  type OgeSchedulerGroupOrientation,
  type OgeSchedulerMoreMode,
  type OgeSchedulerRangeSelectedEvent,
  type OgeSchedulerReminderEvent,
  type OgeSchedulerResource,
  type OgeSchedulerResourceItem,
  type OgeSchedulerView,
  type OgeSchedulerViewOptions,
  type OgeSchedulerWeekNumberRule,
  type OgeSchedulerWorkHours,
} from './lib/scheduler-types';
export {
  buildColumnHeaderRows,
  buildDayWeekGroupLayout,
  buildGroupLeaves,
  buildRowHeaderBlocks,
  dayWeekCellLeaf,
  dayWeekCellValues,
  dayWeekPlacement,
  groupLeafMatcher,
  leafWorkHours,
  resolveGroupLevels,
  resourceValuesOfItem,
  type DayWeekGroupLayout,
  type SchedulerGroupLeaf,
  type SchedulerHeaderCell,
} from './lib/grouping';
export {
  blockedIntervals,
  isDayBlocked,
  isOffWorkHours,
  isRangeBlocked,
  snapProposalToWorkHours,
  type SchedulerBlockedInterval,
} from './lib/availability';
export {
  findSchedulerConflicts,
  type SchedulerConflictCandidate,
} from './lib/conflicts';
export {
  SchedulerEditHistory,
  invertHistoryOp,
  restorePatch,
  type SchedulerHistoryEntry,
  type SchedulerHistoryOp,
} from './lib/history';
export {
  calendarDayDiff,
  planSchedulerPaste,
  schedulerClipboardEntries,
  type SchedulerClipboardEntry,
  type SchedulerPasteTarget,
} from './lib/clipboard';
export {
  nextSchedulerSelection,
  pruneSchedulerSelection,
} from './lib/selection';
export {
  resolveMinimalDays,
  schedulerWeekNumber,
  schedulerWeekNumberTexts,
  weekNumberOf,
  weekNumbersOfDays,
} from './lib/week-number';
export {
  armOgeSchedulerPayload,
  armedOgeSchedulerPayload,
  beginOgeSchedulerExternalDrag,
  findOgeSchedulerDropTarget,
  ogeSchedulerDraggableKey,
  onArmedOgeSchedulerPayload,
  registerOgeSchedulerDropTarget,
  takeArmedOgeSchedulerPayload,
  type OgeSchedulerDragPayload,
  type OgeSchedulerDropSlot,
  type OgeSchedulerDropTarget,
  type OgeSchedulerExternalDragOptions,
} from './lib/external-drag';
export {
  buildSchedulerExportData,
  exportResourcesOf,
  type OgeSchedulerExportData,
  type OgeSchedulerExportRow,
} from './lib/export-data';
export {
  printOgeScheduler,
  type OgeSchedulerPrintOptions,
} from './lib/print';
export {
  appointmentPatch,
  expandAppointment,
  normalizeAppointment,
  resolveSchedulerFields,
  type ResolvedSchedulerFields,
  type SchedulerAppointment,
  type SchedulerAppointmentChange,
  type SchedulerFieldExpr,
  type SchedulerFieldExprs,
  type SchedulerFieldKey,
} from './lib/scheduler-model';
export {
  clampMinutesToWindow,
  durationMinutes,
  minutesOfDay,
  setMinutesOfDay,
  slotCount,
  snapToSlot,
} from './lib/time-math';
export {
  parseRecurrenceException,
  parseRecurrenceRule,
  serializeRecurrenceRule,
  type RecurrenceByDay,
  type RecurrenceFrequency,
  type RecurrenceRule,
} from './lib/rrule';
export { appendException, expandRecurrence } from './lib/rrule-expand';
export {
  buildMonthGrid,
  buildTimeGrid,
  isTimelineView,
  navigateDate,
  normalizeIntervalCount,
  partitionAllDay,
  resolveHiddenWeekDays,
  segmentTimedAppointments,
  viewRange,
  type AppointmentSegment,
  type MonthGridVm,
  type SchedulerTimelineViewType,
  type SchedulerViewType,
  type TimeGridConfig,
  type TimeGridVm,
} from './lib/view-model';
export {
  OGE_SCHEDULER_ADAPTIVE_BREAKPOINT,
  OgeSchedulerAdaptiveViewController,
  resolveSchedulerAdaptiveView,
  type OgeSchedulerAdaptiveView,
  type OgeSchedulerAdaptiveViewControllerOptions,
  type OgeSchedulerAdaptiveViewOptions,
} from './lib/adaptive-view';
export { layoutDayColumn, type LayoutedSegment } from './lib/layout';
export {
  packLanes,
  type LanedItem,
  type LaneInput,
  type LaneLayout,
} from './lib/lanes';
export { buildMonthWeekLanes } from './lib/month-layout';
export {
  fractionForMinutes,
  pointToGridPosition,
  proposeMove,
  proposeResize,
  type AppointmentProposal,
} from './lib/gesture-math';
export {
  beginPointerGesture,
  type SchedulerGestureCallbacks,
} from './lib/gesture';
export {
  type SchedulerCellEvent,
  type SchedulerChipEvent,
  type SchedulerProposalEvent,
  type SchedulerRangeEvent,
} from './lib/view-events';
export {
  chipKey,
  chipSelectKey,
  isSchedulerEditingTarget,
  monthCellKey,
  schedulerLogicalKey,
  schedulerSelectGesture,
  schedulerShortcut,
  timeGridCellKey,
  timeGridChipCtrlKey,
  timelineBarCtrlKey,
  type SchedulerCellKeyAction,
  type SchedulerChipKeyAction,
  type SchedulerCtrlCommit,
  type SchedulerCtrlKeyResult,
  type SchedulerKeyInput,
  type SchedulerSelectGesture,
  type SchedulerShortcut,
  type SchedulerShortcutInput,
} from './lib/keyboard';
export {
  canNavigateScheduler,
  dayWeekViewOf,
  dueSchedulerReminders,
  fillSchedulerTemplate,
  groupResourceIdReader,
  isTodayInSchedulerView,
  mergeSchedulerMessages,
  normalizeSchedulerStore,
  resolveActiveSchedulerView,
  resolveColorResource,
  resolveGroupResource,
  resolveSchedulerViews,
  resourceColorOf,
  schedulerKeyReader,
  schedulerPeriodTitle,
  scrollOffsetForTime,
  visibleSchedulerAppointments,
  type ResolvedSchedulerView,
  type SchedulerViewDefaults,
} from './lib/shell';
export {
  buildItemFromEditor,
  buildPatchFromEditor,
  buildSchedulerEditorItems,
  draftEditorModel,
  editorModelFrom,
  editorRuleFields,
  editorRuleString,
  formatExceptionStamps,
  resourceValuesOf,
  schedulerExceptionItems,
  schedulerMonthDayItems,
  schedulerMonthItems,
  schedulerOrdinalItems,
  schedulerRecurrenceSummary,
  schedulerReminderItems,
  schedulerWeekdayItems,
  schedulerWeekdayKindItems,
  type SchedulerEditorModel,
  type SchedulerEditorResult,
  type SchedulerEditorRuleFields,
  type SchedulerWeekdayKind,
} from './lib/editor';
export {
  allDayDragProposal,
  buildAllDayLayout,
  buildDayWeekColumns,
  buildGutterSlots,
  buildLayoutAllDayStrip,
  cellDateAt,
  chipHeightPercent,
  chipLeftPercent,
  chipTabIndexOf,
  chipTopPercent,
  chipWidthPercent,
  dayWeekCellDate,
  dayWeekChipOrder,
  dayWeekDragMove,
  dayWeekGroupItems,
  dayWeekLayoutDragMove,
  dayWeekLayoutPreviewBox,
  dayWeekPreviewBox,
  dayWeekResizeProposal,
  dayWeekSelectionBox,
  dragSelectionRange,
  escapeAttr,
  isOffHoursCell,
  isWeekendDay,
  layoutDayWeekSegments,
  layoutGroupedDayWeekSegments,
  nowLineFraction,
  originDayIndex,
  resourceIndexOf,
  dayWeekCellSelected,
  dayWeekColumnHeaderText,
  schedulerCellAriaLabel,
  schedulerChipAriaLabel,
  schedulerGridAriaLabel,
  schedulerGridReadOnly,
  segmentKey,
  weekdayShortText,
  withSelectedLabel,
  withUnavailableLabel,
  type AllDayBar,
  type AllDayPlacedBar,
  type AllDayStripCell,
  type DayWeekColumn,
  type DayWeekSegment,
  type DayWeekSelection,
  type SchedulerGutterSlot,
  type SchedulerOverlayBox,
} from './lib/day-week-vm';
export {
  appointmentsOnDay,
  buildMonthWeekLayouts,
  monthCellSelected,
  monthChipOrder,
  monthColumnHeaderText,
  monthDropCell,
  monthMaxLanes,
  monthOriginIndex,
  monthOverflowEntries,
  morePopupKey,
  schedulerDayCellAriaLabel,
  schedulerMoreAriaLabel,
  schedulerMorePopupTitle,
  schedulerMoreText,
  type MonthOverflowEntry,
} from './lib/month-vm';
export {
  OGE_SCHEDULER_TIMELINE_GROUP_ROW_PX,
  OGE_SCHEDULER_TIMELINE_LANE_PX,
  buildGroupedTimelineRows,
  buildHorizontalTimelineRow,
  buildTimelineGrid,
  buildTimelineRows,
  layoutTimelineBars,
  shouldVirtualizeTimeline,
  timelineAxisPct,
  timelineBlockDragMove,
  timelineBlockedBoxes,
  timelineDateAt,
  timelineDayText,
  timelineDragMove,
  timelineHeaderCells,
  timelineHourLabels,
  timelineOffHoursBoxes,
  timelineRowAt,
  timelineRowHeight,
  timelineRowIdReader,
  timelineScaleOf,
  timelineVirtualWindow,
  type TimelineBar,
  type TimelineGridOptions,
  type TimelineGridVm,
  type TimelineHeaderCell,
  type TimelineHourLabel,
  type TimelineMoveEvent,
  type TimelineRow,
  type TimelineScale,
  type TimelineShadeBox,
  type TimelineVirtualWindow,
} from './lib/timeline-vm';
export {
  agendaDayText,
  agendaTimeText,
  buildAgendaDays,
  buildYearMonths,
  chipForeground,
  chipTimeText,
  countAppointmentsByDay,
  popupTimeText,
  yearCellLabel,
  yearWeekdayText,
  type AgendaDay,
  type YearCell,
  type YearMonth,
} from './lib/list-vm';
export {
  OgeSchedulerCore,
  type OgeSchedulerCoreEvents,
  type OgeSchedulerCoreInputs,
  type OgeSchedulerCoreOptions,
  type OgeSchedulerCoreSurfaces,
  type SchedulerContextMenuState,
  type SchedulerScopeAction,
  type SchedulerScopePending,
} from './lib/scheduler-core';
