// Public API of @oge-ui/scheduler-engine (commercial — see LICENSE).
// Framework-free: no Angular or React import anywhere (ADR 0003). Both
// @oge-ui/scheduler and @oge-ui/react-scheduler render from this surface.
// Explicit named exports only (house rule).

export {
  OGE_DEFAULT_SCHEDULER_CONFIG,
  OGE_DEFAULT_SCHEDULER_MESSAGES,
  resolveOgeSchedulerConfig,
  type OgeSchedulerAnnouncementMessages,
  type OgeSchedulerConfig,
  type OgeSchedulerConfigInput,
  type OgeSchedulerEditorMessages,
  type OgeSchedulerGridMessages,
  type OgeSchedulerMenuMessages,
  type OgeSchedulerMessages,
  type OgeSchedulerPopupMessages,
  type OgeSchedulerRecurrenceScopeMessages,
  type OgeSchedulerToolbarMessages,
} from './lib/config';
export {
  type OgeSchedulerAppointment,
  type OgeSchedulerAppointmentAddedEvent,
  type OgeSchedulerAppointmentAddingEvent,
  type OgeSchedulerAppointmentClickEvent,
  type OgeSchedulerAppointmentDeletedEvent,
  type OgeSchedulerAppointmentDeletingEvent,
  type OgeSchedulerAppointmentUpdatedEvent,
  type OgeSchedulerAppointmentUpdatingEvent,
  type OgeSchedulerCellClickEvent,
  type OgeSchedulerEditorShowingEvent,
  type OgeSchedulerRangeSelectedEvent,
  type OgeSchedulerReminderEvent,
  type OgeSchedulerResource,
  type OgeSchedulerResourceItem,
  type OgeSchedulerView,
  type OgeSchedulerViewOptions,
  type OgeSchedulerWorkHours,
} from './lib/scheduler-types';
export {
  appointmentPatch,
  expandAppointment,
  normalizeAppointment,
  resolveSchedulerFields,
  type ResolvedSchedulerFields,
  type SchedulerAppointment,
  type SchedulerAppointmentChange,
  type SchedulerFieldExpr,
  type SchedulerFieldExprs,
  type SchedulerFieldKey,
} from './lib/scheduler-model';
export {
  clampMinutesToWindow,
  durationMinutes,
  minutesOfDay,
  setMinutesOfDay,
  slotCount,
  snapToSlot,
} from './lib/time-math';
export {
  parseRecurrenceException,
  parseRecurrenceRule,
  serializeRecurrenceRule,
  type RecurrenceByDay,
  type RecurrenceFrequency,
  type RecurrenceRule,
} from './lib/rrule';
export { appendException, expandRecurrence } from './lib/rrule-expand';
export {
  buildMonthGrid,
  buildTimeGrid,
  navigateDate,
  partitionAllDay,
  resolveHiddenWeekDays,
  segmentTimedAppointments,
  viewRange,
  type AppointmentSegment,
  type MonthGridVm,
  type SchedulerViewType,
  type TimeGridConfig,
  type TimeGridVm,
} from './lib/view-model';
export {
  OGE_SCHEDULER_ADAPTIVE_BREAKPOINT,
  OgeSchedulerAdaptiveViewController,
  resolveSchedulerAdaptiveView,
  type OgeSchedulerAdaptiveView,
  type OgeSchedulerAdaptiveViewControllerOptions,
  type OgeSchedulerAdaptiveViewOptions,
} from './lib/adaptive-view';
export { layoutDayColumn, type LayoutedSegment } from './lib/layout';
export {
  packLanes,
  type LanedItem,
  type LaneInput,
  type LaneLayout,
} from './lib/lanes';
export { buildMonthWeekLanes } from './lib/month-layout';
export {
  fractionForMinutes,
  pointToGridPosition,
  proposeMove,
  proposeResize,
  type AppointmentProposal,
} from './lib/gesture-math';
export {
  beginPointerGesture,
  type SchedulerGestureCallbacks,
} from './lib/gesture';
export {
  type SchedulerCellEvent,
  type SchedulerChipEvent,
  type SchedulerProposalEvent,
  type SchedulerRangeEvent,
} from './lib/view-events';
export {
  chipKey,
  monthCellKey,
  timeGridCellKey,
  timeGridChipCtrlKey,
  timelineBarCtrlKey,
  type SchedulerCellKeyAction,
  type SchedulerChipKeyAction,
  type SchedulerCtrlCommit,
  type SchedulerCtrlKeyResult,
  type SchedulerKeyInput,
} from './lib/keyboard';
export {
  canNavigateScheduler,
  dayWeekViewOf,
  dueSchedulerReminders,
  fillSchedulerTemplate,
  groupResourceIdReader,
  isTodayInSchedulerView,
  mergeSchedulerMessages,
  normalizeSchedulerStore,
  resolveActiveSchedulerView,
  resolveColorResource,
  resolveGroupResource,
  resolveSchedulerViews,
  resourceColorOf,
  schedulerKeyReader,
  schedulerPeriodTitle,
  scrollOffsetForTime,
  visibleSchedulerAppointments,
  type ResolvedSchedulerView,
  type SchedulerViewDefaults,
} from './lib/shell';
export {
  buildItemFromEditor,
  buildPatchFromEditor,
  buildSchedulerEditorItems,
  draftEditorModel,
  editorModelFrom,
  editorRuleFields,
  editorRuleString,
  resourceValuesOf,
  schedulerReminderItems,
  schedulerWeekdayItems,
  type SchedulerEditorModel,
  type SchedulerEditorResult,
  type SchedulerEditorRuleFields,
} from './lib/editor';
export {
  allDayDragProposal,
  buildAllDayLayout,
  buildDayWeekColumns,
  buildGutterSlots,
  cellDateAt,
  chipLeftPercent,
  chipTabIndexOf,
  chipWidthPercent,
  dayWeekCellDate,
  dayWeekChipOrder,
  dayWeekDragMove,
  dayWeekGroupItems,
  dayWeekPreviewBox,
  dayWeekResizeProposal,
  dayWeekSelectionBox,
  dragSelectionRange,
  escapeAttr,
  isOffHoursCell,
  isWeekendDay,
  layoutDayWeekSegments,
  nowLineFraction,
  originDayIndex,
  resourceIndexOf,
  dayWeekCellSelected,
  dayWeekColumnHeaderText,
  schedulerCellAriaLabel,
  schedulerChipAriaLabel,
  schedulerGridAriaLabel,
  schedulerGridReadOnly,
  segmentKey,
  weekdayShortText,
  type AllDayBar,
  type DayWeekColumn,
  type DayWeekSegment,
  type DayWeekSelection,
  type SchedulerGutterSlot,
  type SchedulerOverlayBox,
} from './lib/day-week-vm';
export {
  buildMonthWeekLayouts,
  monthCellSelected,
  monthChipOrder,
  monthColumnHeaderText,
  monthDropCell,
  monthMaxLanes,
  monthOriginIndex,
  monthOverflowEntries,
  schedulerDayCellAriaLabel,
  schedulerMoreText,
  type MonthOverflowEntry,
} from './lib/month-vm';
export {
  buildTimelineGrid,
  buildTimelineRows,
  layoutTimelineBars,
  timelineDayText,
  timelineDragMove,
  timelineHourLabels,
  timelineRowAt,
  type TimelineBar,
  type TimelineHourLabel,
  type TimelineMoveEvent,
  type TimelineRow,
} from './lib/timeline-vm';
export {
  agendaDayText,
  agendaTimeText,
  buildAgendaDays,
  buildYearMonths,
  chipForeground,
  chipTimeText,
  countAppointmentsByDay,
  popupTimeText,
  yearCellLabel,
  yearWeekdayText,
  type AgendaDay,
  type YearCell,
  type YearMonth,
} from './lib/list-vm';
export {
  OgeSchedulerCore,
  type OgeSchedulerCoreEvents,
  type OgeSchedulerCoreInputs,
  type OgeSchedulerCoreOptions,
  type OgeSchedulerCoreSurfaces,
  type SchedulerContextMenuState,
  type SchedulerScopeAction,
  type SchedulerScopePending,
} from './lib/scheduler-core';
