// Public API of @oge-ui/gantt-engine (commercial — see LICENSE).
//
// The framework-free Gantt engine both render layers run: `@oge-ui/gantt`
// (Angular) and `@oge-ui/react-gantt` (React) depend on it and re-export the
// public types under the same names. Explicit named exports only (house rule).
// The Excel / PDF / PNG builders are separate entry points
// (`/export-excel`, `/export-pdf`, `/export-image`) so their optional peers
// load only when imported.

/* ---------------- the controller ---------------- */
export {
  OgeGanttCore,
  ganttMenuFocusIndex,
  ganttMenuKeyCommand,
  mirrorGanttKey,
  trimGanttDialogChange,
  type GanttArrow,
  type GanttBar,
  type GanttBarGestureKind,
  type GanttBarSegment,
  type GanttCellEditState,
  type GanttContextMenuState,
  type GanttDependencyEditorState,
  type GanttEditorKeyLike,
  type GanttHistogramRowVm,
  type GanttKeyLike,
  type GanttMenuItemState,
  type GanttMenuKeyCommand,
  type GanttMouseLike,
  type GanttProgressLine,
  type GanttResolvedColumn,
  type GanttRollup,
  type GanttStripRect,
  type GanttWorkloadRow,
  type GanttZoomPresetOption,
  type OgeGanttCoreEvents,
  type OgeGanttCoreHost,
  type OgeGanttCoreInputs,
} from './lib/gantt-core';
export {
  beginGanttGesture,
  type GanttGestureCallbacks,
  type GanttGestureHandle,
  type GanttPointerLike,
} from './lib/gantt-gesture';
export {
  buildGanttDialogItems,
  fitGanttScaleType,
  formatGanttMessage,
  ganttDataRange,
  ganttWindowRange,
  GANTT_LIST_WIDTH_MAX,
  GANTT_LIST_WIDTH_MIN,
  GANTT_OVERSCAN_ROWS,
  GANTT_SCALE_HEAD_PX,
  sameGanttRange,
  stepGanttScale,
  widenGanttRange,
  type GanttDialogExtras,
  type GanttEditorModel,
  type GanttEditorResult,
  type GanttRange,
} from './lib/gantt-view';

/* ---------------- config + messages ---------------- */
export {
  OGE_DEFAULT_GANTT_CONFIG,
  OGE_DEFAULT_GANTT_MESSAGES,
  fillGanttMessages,
  resolveGanttConfig,
  type OgeGanttAnnouncementMessages,
  type OgeGanttColumnMessages,
  type OgeGanttConfig,
  type OgeGanttConfigInput,
  type OgeGanttDependencyEditorMessages,
  type OgeGanttDialogMessages,
  type OgeGanttGridMessages,
  type OgeGanttMenuMessages,
  type OgeGanttMessages,
  type OgeGanttResolvedMessages,
  type OgeGanttScaleMessages,
  type OgeGanttSchedulingMessages,
  type OgeGanttToolbarMessages,
} from './lib/gantt-config';

/* ---------------- public types ---------------- */
export type {
  OgeGanttCellEditorType,
  OgeGanttColumn,
  OgeGanttColumnReorderedEvent,
  OgeGanttColumnResizedEvent,
  OgeGanttConflictKind,
  OgeGanttConstraintType,
  OgeGanttDependency,
  OgeGanttDependencyDeletedEvent,
  OgeGanttDependencyDeletingEvent,
  OgeGanttDependencyInsertedEvent,
  OgeGanttDependencyInsertingEvent,
  OgeGanttDependencyType,
  OgeGanttDependencyUpdatedEvent,
  OgeGanttDependencyUpdatingEvent,
  OgeGanttDialogShowingEvent,
  OgeGanttExportColumn,
  OgeGanttExportData,
  OgeGanttLagUnit,
  OgeGanttResource,
  OgeGanttScaleType,
  OgeGanttSchedulingConflict,
  OgeGanttSchedulingConflictEvent,
  OgeGanttSegment,
  OgeGanttSelectionChangedEvent,
  OgeGanttSelectionMode,
  OgeGanttSlack,
  OgeGanttSortChangedEvent,
  OgeGanttSortDirection,
  OgeGanttStripLine,
  OgeGanttTask,
  OgeGanttTaskClickEvent,
  OgeGanttTaskDeletedEvent,
  OgeGanttTaskDeletingEvent,
  OgeGanttTaskInsertedEvent,
  OgeGanttTaskInsertingEvent,
  OgeGanttTaskTitlePosition,
  OgeGanttTaskUpdatedEvent,
  OgeGanttTaskUpdatingEvent,
  OgeGanttViewMode,
  OgeGanttWorkCalendar,
  OgeGanttZoomPreset,
} from './lib/gantt-types';

/* ---------------- the kernel ---------------- */
export {
  dependencyAnchors,
  dependencyPath,
  routeDependency,
  type GanttPoint,
} from './lib/engine/dependency-routing';
export {
  chartPxToDate,
  proposeTaskMove,
  proposeTaskProgress,
  proposeTaskResize,
  type GanttTaskProposal,
} from './lib/engine/gantt-gesture-math';
export {
  buildGanttDependencies,
  buildGanttTasks,
  GANTT_CONSTRAINT_TYPES,
  ganttInstant,
  ganttTaskPatch,
  ganttViewDate,
  ganttWallClock,
  isDatedConstraint,
  normalizeGanttUnits,
  normalizeResourceIds,
  parseGanttConstraintType,
  parseGanttLag,
  parseGanttSegments,
  resolveGanttFields,
  wouldCreateCycle,
  type GanttBuildOptions,
  type GanttConstraintType,
  type GanttDependency,
  type GanttDependencyExprs,
  type GanttDependencyType,
  type GanttFieldExpr,
  type GanttLagUnit,
  type GanttSegment,
  type GanttTask,
  type GanttTaskChange,
  type GanttTaskExprs,
  type ResolvedGanttFields,
} from './lib/engine/gantt-model';
export {
  applyGanttLag,
  autoScheduleForward,
  computeGanttSlack,
  criticalPathKeys,
  detectGanttConflicts,
  scheduleGanttProject,
  type GanttCalendarInput,
  type GanttConflictKind,
  type GanttScheduleChange,
  type GanttScheduleOptions,
  type GanttScheduleResult,
  type GanttSchedulingConflict,
  type GanttSlack,
} from './lib/engine/schedule';
export {
  clampGanttColumnWidth,
  formatGanttLag,
  formatGanttPredecessors,
  GANTT_COLUMN_WIDTH_MAX,
  GANTT_COLUMN_WIDTH_MIN,
  ganttDateInputValue,
  ganttFilterKeys,
  ganttSortValue,
  moveGanttColumn,
  nextGanttSelection,
  parseGanttDateInput,
  parseGanttPredecessors,
  sortGanttItems,
  type GanttCellEditorType,
  type GanttPredecessorEntry,
  type GanttSort,
  type GanttSortDirection,
} from './lib/engine/task-list';
export {
  buildResourceHistogram,
  buildResourceViewRows,
  effortDrivenEnd,
  GANTT_RESOURCE_ROW_PREFIX,
  ganttSpanDays,
  type GanttHistogramCell,
  type GanttHistogramResource,
  type GanttHistogramRow,
  type GanttResourceViewRow,
} from './lib/engine/resources';
export {
  buildGanttScale,
  dateToPx,
  GANTT_SCALE_ORDER,
  GANTT_TICK_WIDTH,
  pxToDate,
  snapToUnit,
  type GanttScale,
  type GanttScaleType,
  type GanttTick,
} from './lib/engine/time-scale';
export {
  addWorkingDays,
  isWorkingDay,
  nextWorkingDay,
  workingDaysBetween,
  type GanttWorkCalendar,
} from './lib/engine/work-calendar';
export {
  buildResourceWorkload,
  type GanttWorkloadSegment,
} from './lib/engine/workload';
