export {
  applyButtonGroupSelection,
  buttonGroupRole,
  buttonGroupNavIndex,
  type OgeButtonGroupSelectionChange,
} from './lib/button/button-group-selection';
export {
  resolveClickGuard,
  resolveHoldToConfirm,
  resolveAutoRepeat,
  type OgeButtonStylingMode,
  type OgeButtonSeverity,
  type OgeButtonSize,
  type OgeButtonIconPosition,
  type OgeClickGuardOptions,
  type OgeHoldToConfirmOptions,
  type OgeAutoRepeatOptions,
  type OgeButtonGroupSelectionMode,
} from './lib/button/button-types';
export {
  OGE_DEFAULT_BUTTONS_MESSAGES,
  OGE_DEFAULT_BUTTONS_CONFIG,
  resolveOgeButtonsConfig,
  type OgeButtonsMessages,
  type OgeButtonsConfig,
  type OgeButtonsConfigInput,
} from './lib/button/button-config';
export {
  OgeButtonPress,
  type OgeButtonPressOptions,
  type OgeButtonHoldTiming,
  type OgeButtonRepeatTiming,
  type OgeButtonGuardTiming,
  type OgeButtonHoldState,
} from './lib/button/button-press';
export {
  resolveButtonSelectionState,
  applyButtonToggle,
  type OgeButtonSelectionRequest,
  type OgeButtonSelectionState,
  type OgeButtonToggleChange,
} from './lib/button/button-toggle';
export {
  type OgeInputLabelMode,
  type OgeInputStylingMode,
  type OgeInputSize,
  type OgeInputSubscriptSizing,
  type OgeInputErrorDisplay,
  type OgeInputCounterMode,
  type OgeInputShowSuccessIcon,
  type OgeFieldError,
} from './lib/input/input-types';
export {
  OGE_DEFAULT_INPUTS_MESSAGES,
  OGE_DEFAULT_INPUTS_CONFIG,
  resolveOgeInputsConfig,
  ogeMoreTagsText,
  type OgeInputsMessages,
  type OgeInputsConfig,
  type OgeInputsConfigInput,
} from './lib/input/input-config';
export {
  formatPattern,
  messageForFieldError,
} from './lib/input/error-messages';
export {
  OgeInputCommit,
  type OgeInputCommitOptions,
} from './lib/input/input-commit';
export {
  OgeMaskCore,
  OGE_DEFAULT_MASK_RULES,
  parseMask,
  ogeMaskComplete,
  ogeMaskInputMode,
  type OgeMaskRule,
  type OgeMaskRules,
  type OgeMaskShowMode,
  type OgeMaskSlot,
  type OgeMaskOptions,
  type OgeMaskEdit,
  type OgeMaskCompletedEvent,
} from './lib/input/mask-core';
export { graphemeCount, resetGraphemeSegmenter } from './lib/input/grapheme';
export {
  resolveDisplay,
  resolveValue,
  resolveDisabled,
  type OgeSelectDisplayExpr,
  type OgeSelectValueExpr,
  type OgeSelectDisabledExpr,
  type OgeSelectImageExpr,
  type OgeSelectSearchExpr,
  type OgeSelectSearchMode,
  type OgeSelectGroupExpr,
  type OgeSelectItemsFn,
} from './lib/input/select-expr';
export {
  OgeListVirtualizerCore,
  OGE_SELECT_OPTION_HEIGHT,
  type OgeListVirtualizerDeps,
  type OgeVirtualScrollOptions,
} from './lib/input/list-virtualizer-core';
export type { OgeReactiveCell, OgeReactivityAdapter } from './lib/reactivity';

// --- grid ---
export {
  OgeGridColumnLayoutCore,
  resizedColumnWidth,
  type OgeGridColumnLayoutDeps,
  type OgeGridColumnRange,
  type OgeGridLayoutColumn,
} from './lib/grid/grid-column-layout';
export {
  OGE_MAX_SCROLL_HEIGHT,
  OgeGridRowVirtualizerCore,
  ogeScrollScale,
  type OgeGridRowVirtualizerDeps,
  type OgeGridRowWindowAdapter,
  type OgeScrollScale,
} from './lib/grid/grid-row-virtualizer';
export {
  OgeGridDeferredChildrenCore,
  type OgeDeferredBaseOptions,
  type OgeGridDeferredChildrenDeps,
  type OgePendingChildRequest,
} from './lib/grid/grid-deferred-children';
export {
  OgeGridEditingState,
  type OgeEditFormItem,
  type OgeEditMode,
  type OgeEditingCell,
  type OgeEditingOptions,
} from './lib/grid/grid-editing-state';
export {
  OgeGridStatePersistenceCore,
  type OgeGridStatePersistenceOptions,
  type OgeStateStorage,
} from './lib/grid/grid-state-persistence';
export {
  adaptiveHiddenColumnIds,
  buildRowFilterExpr,
  dateFilterExpr,
  defaultOperatorFor,
  humanize,
  isDataSource,
  lookupTextOf,
  mapLookupItems,
  ogeGridBandRow,
  resolveLookupItems,
  resolveOgeGridColumns,
  resolveOgeGridAdaptiveHiddenColumns,
  type OgeGridColumnHidingMode,
  defaultAlignmentFor,
  dateRangeFilterExpr,
  type LookupItem,
  type OgeColumnAlignment,
  type OgeColumnLookup,
  type OgeDataType,
  type OgeGridAdaptiveHidingInput,
  type OgeGridBandCell,
  type OgeGridColumnDef,
  type OgeGridColumnResolveInput,
  type OgeGridColumnSpec,
  type OgeGridResolvedColumn,
  isOgeDateType,
  ogeCompileColumnFormat,
  type OgeColumnFormat,
} from './lib/grid/grid-columns';
export {
  OgeGridRangeSelectionCore,
  isOgeRangeExtendKey,
  ogeRangeAnnouncementCounts,
  ogeRangeBounds,
  ogeRangeContains,
  ogeRangeLattice,
  type OgeGridCellCoord,
  type OgeGridCellRange,
  type OgeGridRangeBounds,
  type OgeGridRangeEdges,
  type OgeGridRangeLattice,
  type OgeGridRangeSelectionDeps,
  type OgeRangeSelectionChangedEvent,
} from './lib/grid/grid-range-selection';
export {
  buildOgeRangeTsv,
  ogeFillSeries,
  ogeFillTarget,
  ogeGridEditShortcut,
  ogeKeyboardFillPlan,
  ogeValueFits,
  parseLocaleNumber,
  parseOgeCellText,
  parseOgeTsv,
  planOgeGridPaste,
  type OgeCellTextColumn,
  type OgeCellTextMessages,
  type OgeCellTextParse,
  type OgeFillDirection,
  type OgeFillPlan,
  type OgeGridCellWrite,
  type OgeGridEditShortcut,
  type OgeGridPasteContext,
  type OgeGridPastePlan,
  type OgeRangeTsvOptions,
} from './lib/grid/grid-clipboard';
export {
  OgeGridEditHistory,
  type OgeGridEditBatch,
  type OgeGridEditRecord,
  type OgeGridEditSource,
} from './lib/grid/grid-edit-history';
export {
  OgePreparedTracker,
  ogeClassList,
  ogeColumnValueRange,
  ogeFormatsNeedRange,
  resolveOgeConditionalFormat,
  type OgeCellPreparedEvent,
  type OgeClassValue,
  type OgeColorScaleFormat,
  type OgeConditionalCellFormat,
  type OgeConditionalCondition,
  type OgeConditionalFormat,
  type OgeConditionalIcon,
  type OgeConditionalRange,
  type OgeConditionalRule,
  type OgeConditionalStyle,
  type OgeConditionalTone,
  type OgeGridColumnInfo,
  type OgeDataBarFormat,
  type OgeIconSetFormat,
  type OgeRowPreparedEvent,
} from './lib/grid/grid-conditional-format';
export {
  OGE_NO_SPANS,
  computeOgeGridSpans,
  type OgeGridCellSpan,
  type OgeGridSpanColumn,
  type OgeGridSpanExtent,
  type OgeGridSpanInput,
  type OgeGridSpanLayout,
} from './lib/grid/grid-cell-span';
export {
  emptyHeaderConditionFilter,
  flattenHeaderDateTree,
  groupHeaderValuesByDate,
  headerConditionExpr,
  headerConditionNeedsValue,
  headerConditionOperators,
  ogeHeaderConditionKey,
  parseHeaderConditionExpr,
  type OgeHeaderCondition,
  type OgeHeaderConditionFilter,
  type OgeHeaderDateNode,
  type OgeHeaderFilterMode,
} from './lib/grid/grid-header-conditions';
export {
  ogePagerInfoContext,
  ogePagerInfoText,
  ogePagerPages,
  ogeParsePageInput,
  type OgePagerInfoContext,
  type OgePagerInfoMessages,
} from './lib/grid/grid-pager';
export {
  findOgeRowDragParticipant,
  ogeRowDragParticipantCount,
  ogeRowDropPosition,
  registerOgeRowDragParticipant,
  type OgeRowDragParticipant,
  type OgeRowDragSource,
  type OgeRowDragTarget,
  type OgeRowDropPosition,
} from './lib/grid/grid-row-drag-group';
export {
  OGE_AUTO_FIT_SLACK,
  ogeFirstVisibleRow,
  ogeIsTextTruncated,
  ogeMeasureAutoWidth,
  ogeStickyGroupChain,
} from './lib/grid/grid-auto-fit';
export {
  ogeGroupValueText,
  type OgeGroupIntervalMessages,
} from './lib/grid/grid-grouping';
export {
  OgeContextMenuEcho,
  isOgeContextMenuKey,
  ogeContextMenuKeyTarget,
  type OgeContextMenuKeyTarget,
} from './lib/grid/grid-context-menu';
export {
  OgeGridAnnouncements,
  rowCountText,
  sortChangeText,
  type OgeGridAnnounceSink,
  type OgeGridAnnouncementSnapshot,
  type OgeGridAnnouncementsDeps,
} from './lib/grid/grid-announcements';
export { syncOgeEditorErrorAria } from './lib/grid/grid-editor-aria';
export {
  OgeGridEditingCore,
  type OgeDataChange,
  type OgeEditingStartEvent,
  type OgeGridEditingCoreDeps,
  type OgeGridEditorBridge,
  type OgeGridEditorState,
  type OgeGridInvalidEditor,
  type OgeGridApplyValuesOptions,
  type OgeGridCellValueWrite,
  type OgeRowInsertedEvent,
  type OgeRowInsertingEvent,
  type OgeRowRemovedEvent,
  type OgeRowRemovingEvent,
  type OgeRowUpdatedEvent,
  type OgeRowUpdatingEvent,
  type OgeSavedChangesEvent,
  type OgeSavingChangesEvent,
} from './lib/grid/grid-editing-core';
export {
  allHeaderValuesSelected,
  booleanCellLabel,
  filterHeaderValues,
  formatCellValue,
  groupHeaderValuesByYear,
  headerGroupState,
  headerValueText,
  headerYearLabel,
  isHeaderValueSelected,
  toggleAllHeaderValues,
  toggleHeaderGroup,
  toggleHeaderValue,
  type OgeBooleanCellMessages,
  type OgeHeaderFilterMessages,
  type OgeHeaderFilterSelection,
  type OgeHeaderValueGroup,
  type OgeHeaderValueTextOptions,
} from './lib/grid/grid-header-filter';
export {
  buildOgeExportItems,
  mergeOgeExportStyles,
  ogeExportCellStyle,
  ogeExportCellText,
  ogeExportColumnOf,
  ogeExportColumnsOf,
  ogeExportHeaderCells,
  ogeExportItemsOf,
  ogeExportScope,
  ogeColumnSummaryText,
  ogeSummaryText,
  ogeGridExportItems,
  ogeGridExportLoadOptions,
  type OgeGridExportFieldInfo,
  type OgeGridExportMessages,
  type OgeGridExportStructureInput,
  type OgeExportColumnSource,
  type OgeExportGroupInfo,
  type OgeExportGroupLevel,
  type OgeExportHeaderCell,
  type OgeExportStructureOptions,
} from './lib/grid/grid-export';
export {
  builderToExpr,
  describeExpr,
  effectiveFilterOperator,
  exprToBuilder,
  filterOperatorSymbol,
  filterRowOperatorChoices,
  operatorsFor,
  rowFilterExpr,
  type OgeBuilderCondition,
  type OgeBuilderGroup,
  type OgeFilterBuilderField,
  type OgeFilterDescribeMessages,
  type OgeFilterRowColumn,
} from './lib/grid/grid-filtering';
export {
  allRowsSelected,
  deferredToggleExpr,
  keyEqualsExpr,
  rowClickSelectionIntent,
  someRowsSelected,
  type OgeGridSelectAllState,
  type OgeGridSelectionIntent,
  type OgeGridSelectionMode,
  type OgeGridSelectionModifiers,
} from './lib/grid/grid-selection';
export {
  OgeGridColumnsState,
  OgeGridExpansionState,
  OgeGridFilterState,
  OgeGridGroupingState,
  OgeGridPagingState,
  OgeGridSelectionState,
  OgeGridSortState,
  type OgeGridFilterStateSnapshot,
  type OgePinOverride,
} from './lib/grid/grid-state';
export {
  OgeGridKeyboardNavCore,
  type OgeGridFocusedCell,
  type OgeGridKeyboardNavDeps,
  type OgeGridKeyboardNavTreeHooks,
} from './lib/grid/grid-keyboard-nav';
export {
  OGE_COLUMN_RESIZE_FINE_STEP,
  OGE_COLUMN_RESIZE_FLOOR,
  OGE_COLUMN_RESIZE_STEP,
  clampColumnWidth,
  ogeAdjacentDataRow,
  ogeChooserMoveDirection,
  ogeColumnMoveTarget,
  ogeColumnSeparatorKeyCommand,
  ogeColumnWidthBounds,
  ogeGridHeaderKeyCommand,
  ogeGridHeaderKeyShortcuts,
  ogeGroupChipKeyCommand,
  ogeListMoveTarget,
  ogeRowMoveDirection,
  ogeSeparatorTargetWidth,
  ogeTreeRowKeyMove,
  type OgeColumnMoveTarget,
  type OgeColumnSeparatorKeyCommand,
  type OgeColumnWidthBounds,
  type OgeGridHeaderKeyCommand,
  type OgeGroupChipKeyCommand,
  type OgeKeyInput,
  type OgeMovableColumn,
  type OgeTreeRowKeyMove,
} from './lib/grid/grid-keyboard-moves';
export {
  OGE_GRID_HOST_SELECTOR,
  isOgeDragExcludedTarget,
  ogeMoveGroupingTo,
  ogeOwnedClosest,
  resolveOgeAttributeTarget,
  resolveOgeHeaderDropTarget,
  resolveOgeRowDropIndex,
  type OgeGridHeaderDropTarget,
} from './lib/grid/grid-pointer-drag';
export { OgeGridStateCore, loadOptionsEqual } from './lib/grid/grid-state-core';
export {
  OGE_GRID_WINDOW_BLOCK_SIZE,
  OgeGridDataCore,
  type OgeGridDataCoreDeps,
} from './lib/grid/grid-data-core';
export {
  OGE_DEFAULT_GRID_CONFIG,
  OGE_DEFAULT_GRID_MESSAGES,
  resolveGridConfig,
  type OgeGridConfig,
  type OgeGridConfigInput,
  type OgeGridMessages,
} from './lib/grid/grid-config';
export type {
  OgeDataErrorEvent,
  OgeExportCellArgs,
  OgeExportCellStyle,
  OgeExportCellStyleArgs,
  OgeExportColumn,
  OgeExportData,
  OgeExportItem,
  OgeExportOptions,
  OgeExportRowKind,
  OgeExportSummaryCell,
  OgeExportingEvent,
  OgeContextMenuSource,
  OgeFilterRowOptions,
  OgeFocusedCellChangedEvent,
  OgeFocusedRowChangedEvent,
  OgeGridRowToggleEvent,
  OgeGridRowTogglingEvent,
  OgeGridToggleKind,
  OgeGroupingOptions,
  OgeHeaderFilterOptions,
  OgePageChangedEvent,
  OgePagingOptions,
  OgeRowReorderedEvent,
  OgeRangeSelectionOptions,
  OgeRowDragStartEvent,
  OgeRowDragOverEvent,
  OgeRowDropEvent,
  OgeRowDragEndEvent,
  OgeScrollingOptions,
  OgeSearchPanelOptions,
  OgeSelectionChangedEvent,
  OgeSortChangedEvent,
  OgeSortingOptions,
} from './lib/grid/grid-options';
// --- tree list ---
export {
  OgeTreeListCore,
  ogeTreeCsv,
  ogeTreeDataSource,
  ogeTreeDropPosition,
  ogeTreeHeaderValueGroups,
  ogeTreeHeaderValueText,
  type OgeTreeBooleanMessages,
  type OgeTreeExportBuildOptions,
  type OgeTreeExportOptions,
  type OgeTreeListRemoteOperations,
  type OgeTreeListSummary,
  type OgeTreeSummaryItem,
  type OgeTreeExportData,
  type OgeTreeExportSourceColumn,
  type OgeTreeInitNewRowEvent,
  type OgeTreeListCoreDeps,
  type OgeTreeListStateSlices,
  type OgeTreeLoadMode,
  type OgeTreeOrphanPolicy,
  type OgeTreeRowReparentEvent,
  type OgeTreeRowToggleEvent,
  type OgeTreeRowTogglingEvent,
  type OgeTreeSearchColumn,
  type OgeTreeToggleNotifier,
} from './lib/tree-list/tree-list-core';
export {
  OgeSelectListCore,
  ogeSelectSearchFilter,
  ogeSelectSearchStrings,
  type OgeSelectListCoreDeps,
  type OgeSelectListRow,
} from './lib/input/select-list-core';
export {
  OgeRemoteListCore,
  isNearScrollEnd,
  type OgeListDataSource,
  type OgeListDataStatus,
  type OgeListPageLoadedEvent,
  type OgeRemoteListCoreDeps,
} from './lib/input/remote-list-core';
export {
  ogeAllowDropDownOpen,
  ogeAllowDropDownClose,
  ogeSelectAllState,
  ogeToggleAllValues,
  ogeCanSelectMore,
  ogeChipOverflow,
  type OgeDropDownCloseReason,
  type OgeDropDownOpeningEvent,
  type OgeDropDownClosingEvent,
  type OgeSelectAllState,
} from './lib/input/select-helpers';
export {
  ogeComboColumnCaption,
  ogeComboCellValue,
  ogeComboCellText,
  ogeComboSearchStrings,
  ogeComboGridTemplate,
  ogeComboFixedWidth,
  ogeComboColumnTarget,
  type OgeComboBoxColumnBase,
} from './lib/input/multi-column-core';
export {
  clampValue,
  constrainRangeValue,
  ratioToValue,
  snapToStep,
  valueToRatio,
  type OgeRangeThumb,
  OGE_SLIDER_MAX_TICKS,
  sliderTicks,
  sliderKeyboardTarget,
  sliderValueFromPointer,
  sliderPercent,
  startSliderDrag,
  type OgeSliderScale,
  type OgeSliderAxis,
  type OgeSliderTrackRect,
  type OgeSliderDragHandlers,
} from './lib/input/slider-core';
export {
  addDays,
  addMonths,
  addYears,
  monthMatrix,
  resolveFirstDayOfWeek,
  sameDay,
  sameMonth,
  startOfDay,
  toLocalDate,
  weekNumber,
  type WeekNumberRule,
  type OgeDateBoxType,
  type OgeDateBoxApplyValueMode,
  type OgeDateBoxDisplayFormat,
  type OgeDateBoxTimeView,
  isDayDisabled,
  monthCells,
  yearCells,
  decadeCells,
  weekdayNames,
  viewLabel,
  navigate,
  type CalendarCell,
  type OgeCalendarZoomLevel,
  type OgeCalendarSelectionMode,
  type OgeCalendarRange,
  type OgeCalendarWeekNumberOptions,
  type OgeCalendarDisabledDates,
  type OgeCalendarCellClickEvent,
} from './lib/input/calendar-core';
export {
  datePartOrder,
  parseDateText,
  type DateParseKind,
} from './lib/input/date-parse';
export {
  OgeDateSegmentCore,
  dateSegmentPlaceholders,
  dateSegmentTemplate,
  type OgeDateSegment,
  type OgeDateSegmentKey,
  type OgeDateSegmentKind,
  type OgeDateSegmentOptions,
  type OgeDateSegmentPlaceholders,
  type OgeDateSegmentState,
} from './lib/input/date-segments';
export {
  dayPeriodColumnOptions,
  dayPeriodLabels,
  hourColumnOptions,
  isTimePartSelected,
  minuteColumnOptions,
  nowForType,
  resolveHour12,
  timeDisplayOptions,
  withTimePart,
  type OgeDateRangeBoxType,
  type OgeTimeColumnOption,
  type OgeTimePart,
} from './lib/input/time-parts';
export {
  ogeDateRangePresets,
  dateRangePresetActive,
  dateRangePresetLabel,
  type OgeDateRangePreset,
  type OgeDateRangePresetId,
  type OgeDateRangePresetOptions,
  type OgeDateRangeWeekPresetOptions,
} from './lib/input/date-range-presets';
export {
  createNumberTypingGrouper,
  formatNumberWhileTyping,
  numberWheelDirection,
  type OgeNumberTypingOptions,
  type OgeNumberTypingResult,
} from './lib/input/number-typing';
export {
  colorsEqual,
  contrastForeground,
  formatColor,
  hsvaToRgba,
  parseColor,
  rgbaToHsva,
  OGE_DEFAULT_COLOR_PALETTE,
  type OgeColorBoxApplyValueMode,
  type OgeColorBoxView,
  type OgeColorFormat,
  type OgeHsva,
  type OgeRgba,
} from './lib/input/color-core';
export {
  OGE_COLOR_PALETTE_PRESETS,
  applyColorChannelText,
  colorPaletteNavIndex,
  compositeColorOver,
  contrastLevels,
  contrastRatio,
  type OgeColorChannel,
  type OgeColorPalettePreset,
  type OgeColorPalettePresetData,
  type OgeContrastLevels,
} from './lib/input/color-core';
export {
  applySelectAll,
  applyToggleGroupPress,
  choiceIncludes,
  selectAllState,
  toggleChoiceValue,
  toggleGroupSelectedIndices,
  type OgeCheckBoxGroupLayout,
  type OgeToggleGroupChange,
  type OgeToggleGroupSelectionMode,
} from './lib/input/choice-group-core';
// W8b — list box
export {
  OGE_LIST_BOX_REORDER_SHORTCUTS,
  OgeListBoxCore,
  ogeListBoxDropTarget,
  ogeListBoxReorderAnnouncement,
  ogeListBoxSections,
  ogeListReorderDropIndex,
  ogeMoveListItem,
  type OgeListBoxClickInput,
  type OgeListBoxCoreDeps,
  type OgeListBoxDropTarget,
  type OgeListBoxKeyInput,
  type OgeListBoxKeyResult,
  type OgeListBoxReorder,
  type OgeListBoxReorderCause,
  type OgeListBoxSection,
  type OgeListBoxSelectionMode,
} from './lib/input/list-box-core';
// W8b — transfer list
export {
  ogeTransferAnnouncement,
  ogeTransferCountText,
  ogeTransferDropSide,
  ogeTransferKeyCommand,
  ogeTransferKeyShortcuts,
  ogeTransferMovableValues,
  ogeTransferMove,
  ogeTransferOpposite,
  ogeTransferSplit,
  ogeTransferDropTarget,
  ogeTransferReorderable,
  ogeTransferReorderLine,
  ogeTransferReorderSource,
  ogeTransferReorderTarget,
  type OgeTransferListDropTarget,
  type OgeTransferListKeyInput,
  type OgeTransferListMoveCause,
  type OgeTransferListMoveCommand,
  type OgeTransferListReorderSides,
  type OgeTransferListSide,
  type OgeTransferListSplit,
} from './lib/input/transfer-list-core';
// W8b — rating
export {
  OGE_RATING_ICON_PATHS,
  OGE_RATING_MIN_PRECISION,
  normalizeRatingMax,
  normalizeRatingPrecision,
  ratingItemStates,
  ratingKeyboardTarget,
  ratingPointerRatio,
  ratingPressValue,
  ratingRadioKeyTarget,
  ratingValueFromPointer,
  ratingValueText,
  resolveRatingSemantics,
  snapRatingValue,
  type OgeRatingIcon,
  type OgeRatingItemState,
  type OgeRatingKeyOptions,
  type OgeRatingSelection,
  type OgeRatingSemantics,
} from './lib/input/rating-core';
// W8b — one-time-code input
export {
  clampOtpFocus,
  normalizeOtpLength,
  normalizeOtpValue,
  otpAcceptsChar,
  otpBackspace,
  otpCellLabel,
  otpCells,
  otpDelete,
  otpInputMode,
  otpInsert,
  otpNavigationTarget,
  otpSeparatorAfter,
  otpTypedText,
  sanitizeOtpText,
  type OgeOtpEdit,
  type OgeOtpInputCase,
  type OgeOtpInputType,
  type OgeOtpOptions,
} from './lib/input/otp-core';
// W8b — signature pad
export {
  OgeSignatureCore,
  buildOgeSignatureSvg,
  drawOgeSignatureStroke,
  ogeSignatureFontSize,
  ogeSignatureGeometry,
  ogeSignaturePointFrom,
  ogeSignatureWidths,
  ogeSvgDataUrl,
  parseOgeSignatureSvg,
  renderOgeSignature,
  type OgeSignatureCanvasContext,
  type OgeSignatureData,
  type OgeSignatureFormat,
  type OgeSignatureMode,
  type OgeSignaturePen,
  type OgeSignaturePoint,
  type OgeSignatureRenderOptions,
  type OgeSignatureSegment,
  type OgeSignatureSize,
  type OgeSignatureStroke,
  type OgeSignatureStrokeEvent,
  type OgeSignatureStrokeGeometry,
} from './lib/input/signature-core';
// W8b — mention
export {
  OgeMentionCore,
  ogeFindMentionQuery,
  ogeInsertMention,
  ogeMentionKeyCommand,
  ogeShiftMentions,
  type OgeMentionCoreDeps,
  type OgeMentionInsertion,
  type OgeMentionItemContext,
  type OgeMentionItemsSource,
  type OgeMentionKeyCommand,
  type OgeMentionQuery,
  type OgeMentionQueryOptions,
  type OgeMentionSearchChangedEvent,
  type OgeMentionSelectedEvent,
  type OgeMentionToken,
  type OgeMentionTrigger,
} from './lib/input/mention-core';
export { ogeCaretRect } from './lib/input/caret-rect';
export {
  createNumberFormatter,
  clampNumber,
  offsetByStep,
  type OgeNumberFormatter,
} from './lib/input/number-format';
export {
  OGE_DEFAULT_CARD_CONFIG,
  OGE_DEFAULT_PROGRESS_BAR_CONFIG,
  OGE_DEFAULT_PROGRESS_BAR_MESSAGES,
  OGE_DEFAULT_LOAD_INDICATOR_CONFIG,
  OGE_DEFAULT_LOAD_INDICATOR_MESSAGES,
  OGE_DEFAULT_SKELETON_CONFIG,
  resolveOgeCardConfig,
  resolveOgeProgressBarConfig,
  resolveOgeLoadIndicatorConfig,
  resolveOgeSkeletonConfig,
  type OgeCardStylingMode,
  type OgeCardOrientation,
  type OgeCardSize,
  type OgeCardSeverity,
  type OgeCardActionsAlign,
  type OgeCardConfig,
  type OgeCardConfigInput,
  type OgeProgressBarSeverity,
  type OgeProgressBarCompletedEvent,
  type OgeProgressBarMessages,
  type OgeProgressBarConfig,
  type OgeProgressBarConfigInput,
  type OgeLoadIndicatorMessages,
  type OgeLoadIndicatorConfig,
  type OgeLoadIndicatorConfigInput,
  type OgeSkeletonShape,
  type OgeSkeletonAnimation,
  type OgeSkeletonConfig,
  type OgeSkeletonConfigInput,
} from './lib/layout/layout-core';
export {
  OGE_PROGRESS_RING_DEFAULT_SIZE,
  OGE_PROGRESS_RING_DEFAULT_THICKNESS,
  OGE_PROGRESS_RING_INDETERMINATE_RATIO,
  ogeProgressAriaNow,
  ogeProgressLabel,
  ogeProgressRatio,
  ogeProgressRingGeometry,
  type OgeProgressBarType,
  type OgeProgressRingGeometry,
} from './lib/layout/progress-ring';
export {
  OGE_LOAD_PANEL_TARGET_CLASS,
  OgeLoadPanelCore,
  ogeAcquireLoadPanelTarget,
  ogeLoadPanelBusyTarget,
  ogeLoadPanelNeedsPositioning,
  ogeResolveLoadPanelTarget,
  type OgeLoadPanelClock,
  type OgeLoadPanelCoreHost,
  type OgeLoadPanelPosition,
  type OgeLoadPanelTargetElement,
  type OgeLoadPanelTimings,
} from './lib/layout/load-panel-core';
export {
  ogeExpansionShowsToggle,
  runOgeExpansionToggle,
  type OgeExpansionPanelCollapsingEvent,
  type OgeExpansionPanelExpandingEvent,
  type OgeExpansionPanelToggleEvent,
  type OgeExpansionToggleRequest,
} from './lib/layout/expansion-panel-core';
export {
  flattenOgePanelBarItems,
  isOgePanelBarSingle,
  ogePanelBarExpansionAfter,
  ogePanelBarIndex,
  ogePanelBarInitialExpanded,
  ogePanelBarKeyAction,
  ogePanelBarKeyIntent,
  ogePanelBarVisibleIds,
  type OgePanelBarExpandMode,
  type OgePanelBarExpansionChange,
  type OgePanelBarItem,
  type OgePanelBarItemClickEvent,
  type OgePanelBarItemCollapsingEvent,
  type OgePanelBarItemExpandingEvent,
  type OgePanelBarItemLike,
  type OgePanelBarItemToggleEvent,
  type OgePanelBarKeyAction,
  type OgePanelBarKeyIntent,
  type OgePanelBarNode,
  type OgePanelBarSelectionChangedEvent,
} from './lib/layout/panel-bar-core';
export {
  edgeEnabledIndex,
  stepEnabledIndex,
  OGE_DEFAULT_TABS_MESSAGES,
  OGE_DEFAULT_TABS_CONFIG,
  OGE_TAB_DRAG_THRESHOLD,
  resolveOgeTabsConfig,
  applyTabOrder,
  tabItemDescriptor,
  resolveTabIndex,
  reorderTabIds,
  canSelectTab,
  type OgeTabsMessages,
  type OgeTabsConfig,
  type OgeTabsConfigInput,
  type OgeTabDescriptorCore,
  type OgeTabsActivation,
  type OgeTabsOrientation,
  type OgeTabsPosition,
  type OgeTabsStylingMode,
  type OgeTabsSize,
  type OgeTabsNavButtonsMode,
  type OgeTabsAlignment,
  type OgeTabsIndicatorFit,
  type OgeTabPanelAnimation,
  type OgeTabCloseGuard,
  type OgeTabItem,
  type OgeTabSelectionChangingEvent,
  type OgeTabSelectionChangedEvent,
  type OgeTabClickEvent,
  type OgeTabClosingEvent,
  type OgeTabClosedEvent,
  type OgeTabReorderingEvent,
  type OgeTabReorderedEvent,
} from './lib/tabs/tabs-core';
export {
  type OgeMenuItem,
  type OgeMenuItemSeverity,
  type OgeMenuItemType,
  type OgeMenuCloseReason,
} from './lib/menu/menu-types';
export {
  menuEnabledIndexes,
  menuMoveIndex,
  menuEdgeIndex,
  OgeMenuTypeAhead,
} from './lib/menu/menu-nav';
export {
  isMenuHeader,
  isMenuItemNavigable,
  menuItemRole,
  menuItemAriaChecked,
  menuItemIndicator,
  menuItemNextChecked,
  menuItemKeepsOpen,
  applyMenuItemCheck,
  menuItemSegments,
  menuRetainedActiveIndex,
  type OgeMenuItemRole,
  type OgeMenuActivationTrigger,
  type OgeMenuSegment,
} from './lib/menu/menu-item-state';
export {
  OGE_DEFAULT_OVERLAY_TIMINGS,
  type OgeOverlayTimings,
} from './lib/overlay/overlay-timings';
export {
  OgeAnchoredPanelCore,
  OGE_POPUP_AVAILABLE_HEIGHT_VAR,
  type OgeAnchoredPanelCoreOptions,
  type OgePopupCloseReason,
} from './lib/overlay/anchored-panel-core';
export {
  OGE_DEFAULT_ADAPTIVE_BREAKPOINT,
  OGE_DEFAULT_ADAPTIVE_CONFIG,
  OGE_SHEET_FOCUS_ATTR,
  OGE_SHEET_SWIPE_DISMISS,
  OgeAdaptiveSheetCore,
  adaptiveListViewportHeight,
  adaptiveMediaQuery,
  matchesAdaptiveViewport,
  resolveAdaptivePresentation,
  watchAdaptiveViewport,
  type OgeAdaptiveConfig,
  type OgeAdaptiveMode,
  type OgeAdaptivePresentation,
  type OgeAdaptiveSheetCoreOptions,
} from './lib/overlay/adaptive';
export {
  ogeVisibleViewport,
  popupAvailableHeight,
  type OgePopupAvailableHeightRequest,
  resolvePopupPosition,
  type OgePopupSide,
  type OgePopupAlign,
  type OgePopupPlacement,
  type OgeRect,
  type OgePopupPositionRequest,
  type OgeResolvedPopupPosition,
} from './lib/overlay/position';
export {
  pushOverlay,
  removeOverlay,
  isTopOverlay,
} from './lib/overlay/overlay-stack';
export { getTabbableElements, trapTabKey } from './lib/overlay/focus-trap';
export {
  OGE_DEFAULT_OVERLAY_MESSAGES,
  OGE_DEFAULT_OVERLAY_CONFIG,
  resolveOverlayConfig,
  type OgeOverlayMessages,
  type OgeOverlayConfig,
  type OgeOverlayConfigInput,
} from './lib/overlay/overlay-config';
export {
  OGE_TOOLTIP_PANEL_OPTIONS,
  OgeTooltipCore,
  tooltipDescribedByTarget,
  type OgeTooltipCoreOptions,
  type OgeTooltipShowMode,
} from './lib/overlay/tooltip-core';
export {
  OGE_POPUP_ARROW_SIZE,
  resolvePopupArrow,
  popupArrowInset,
  type OgePopupArrow,
  type OgePopupArrowRequest,
} from './lib/overlay/arrow';
export {
  OgePopoverCore,
  popoverTriggerAria,
  popoverPanelAria,
  syncPopoverTriggerAria,
  supportsAriaExpanded,
  resolvePopoverInitialFocus,
  nextTabbableAfter,
  type OgePopoverCoreOptions,
  type OgePopoverShowOn,
  type OgePopoverOpenReason,
  type OgePopoverCloseReason,
  type OgePopoverInitialFocus,
  type OgePopoverOpeningEvent,
  type OgePopoverOpenedEvent,
  type OgePopoverClosingEvent,
  type OgePopoverClosedEvent,
  type OgePopoverTriggerAria,
  type OgePopoverPanelAria,
} from './lib/overlay/popover-core';
export {
  OGE_ACTION_SHEET_FOCUS_ATTR,
  OgeActionSheetCore,
  beginOgeActionSheetSwipe,
  ogeActionSheetDividerIndex,
  ogeActionSheetKeyIntent,
  ogeActionSheetOrder,
  ogeActionSheetSwipeDismisses,
  ogeActionSheetTabStop,
  type OgeActionSheetClosedEvent,
  type OgeActionSheetCloseReason,
  type OgeActionSheetClosingEvent,
  type OgeActionSheetCoreOptions,
  type OgeActionSheetItem,
  type OgeActionSheetItemClickEvent,
  type OgeActionSheetKeyIntent,
  type OgeActionSheetOpeningEvent,
  type OgeActionSheetResult,
  type OgeActionSheetSwipeOptions,
} from './lib/overlay/action-sheet-core';
export {
  ogeContextMenuApiTarget,
  ogeContextMenuPoint,
  ogeContextMenuTarget,
  ogeResolveContextMenuOpen,
  type OgeContextMenuOpeningEvent,
  type OgeContextMenuPoint,
  type OgeContextMenuOpenRequest,
  type OgeContextMenuOpenResult,
} from './lib/overlay/context-menu-core';
export {
  OGE_MODAL_MIN_RESIZE,
  modalCssSize,
  resolveModalInitialFocus,
  isModalFocusOrphaned,
  inertModalBackground,
  clampModalDrag,
  clampModalResize,
  trackPointerGesture,
  type OgeModalCloseReason,
  type OgeModalOpeningEvent,
  type OgeModalClosingEvent,
  type OgeModalClosedEvent,
  type OgeModalResizeEvent,
  type OgeModalAutoFocus,
  type OgeModalPlacement,
  type OgeModalDragRequest,
  type OgeModalResizeRequest,
} from './lib/overlay/modal-core';
export {
  OGE_MODAL_PLACEMENTS,
  modalPlacementClass,
  type OgeModalRole,
} from './lib/overlay/modal-core';
export { overlayStackSize } from './lib/overlay/overlay-stack';
export { ogeOverlayMessage } from './lib/overlay/overlay-config';
// --- dialog helpers (confirm / alert / prompt) -------------------------------
export {
  OGE_DIALOG_DEFAULT_WIDTH,
  OGE_DIALOG_ICONS,
  OGE_DIALOG_TRIANGLE_PATH,
  OgeDialogCore,
  ogeConfirmResult,
  ogeDialogAutoFocusSelector,
  ogeDialogEnterIsPrimary,
  ogeDialogOptions,
  ogePromptResult,
  resolveOgeDialog,
  validateOgePromptValue,
  type OgeAlertBaseOptions,
  type OgeConfirmBaseOptions,
  type OgeDialogBaseOptions,
  type OgeDialogCoreOptions,
  type OgeDialogIcon,
  type OgeDialogInitialFocus,
  type OgeDialogKeyInput,
  type OgeDialogKind,
  type OgeDialogOutcome,
  type OgeDialogSeverity,
  type OgePromptBaseOptions,
  type OgePromptInputType,
  type OgePromptValidator,
  type OgeResolvedDialog,
} from './lib/overlay/dialog-helpers';
// --- non-modal window ----------------------------------------------------------
export {
  bringOgeWindowToFront,
  isOgeFrontWindow,
  ogeOpenWindowCount,
  ogeWindowLayer,
  registerOgeWindow,
  subscribeOgeWindows,
  unregisterOgeWindow,
} from './lib/overlay/window-stack';
export {
  OGE_WINDOW_GUTTER,
  OGE_WINDOW_KEY_SHORTCUTS,
  OGE_WINDOW_KEY_STEP,
  OGE_WINDOW_MIN_SIZE,
  OGE_WINDOW_RESIZE_EDGES,
  OGE_WINDOW_TITLE_REACH,
  OgeWindowCore,
  clampOgeWindowPosition,
  ogeWindowKeyCommand,
  ogeWindowStateStep,
  ogeWindowZIndex,
  resizeOgeWindowRect,
  resolveOgeWindowPlacement,
  resolveOgeWindowInitialFocus,
  type OgeWindowAutoFocus,
  type OgeWindowBox,
  type OgeWindowChangeSource,
  type OgeWindowCloseReason,
  type OgeWindowClosedEvent,
  type OgeWindowClosingEvent,
  type OgeWindowCoreOptions,
  type OgeWindowCoreProps,
  type OgeWindowKeyCommand,
  type OgeWindowKeyInput,
  type OgeWindowMovedEvent,
  type OgeWindowOpeningEvent,
  type OgeWindowPlacement,
  type OgeWindowPointerInput,
  type OgeWindowPosition,
  type OgeWindowRect,
  type OgeWindowResizeEdge,
  type OgeWindowResizedEvent,
  type OgeWindowSizeLimits,
  type OgeWindowState,
  type OgeWindowStateChangedEvent,
  type OgeWindowStateChangingEvent,
} from './lib/overlay/window-core';
// --- live announcements ------------------------------------------------------
export {
  OgeLiveAnnouncerCore,
  getOgeLiveAnnouncer,
  OGE_LIVE_ANNOUNCER_ATTR,
  OGE_LIVE_ANNOUNCER_CLASS,
  type OgeLivePoliteness,
  type OgeLiveAnnounceOptions,
  type OgeLiveAnnouncerOptions,
} from './lib/a11y/live-announcer';
// --- rich-text editor (W8e) ---------------------------------------------------
export {
  OGE_EDITOR_MAX_INDENT,
  ogeEditorNoMarks,
  ogeEditorParagraph,
  ogeEditorText,
  ogeEditorEmptyDoc,
  ogeEditorCaret,
  inlineLength as ogeEditorInlineLength,
  blockLength as ogeEditorBlockLength,
  blockText as ogeEditorBlockText,
  docText as ogeEditorDocText,
  docIsEmpty as ogeEditorDocIsEmpty,
  marksEqual as ogeEditorMarksEqual,
  normalizeInlines as ogeEditorNormalizeInlines,
  selectionRange as ogeEditorSelectionRange,
  selectionIsCollapsed as ogeEditorSelectionIsCollapsed,
  type OgeEditorToggleMark,
  type OgeEditorMarkName,
  type OgeEditorLink,
  type OgeEditorMarks,
  type OgeEditorText,
  type OgeEditorImage,
  type OgeEditorBreak,
  type OgeEditorInline,
  type OgeEditorBlockType,
  type OgeEditorListKind,
  type OgeEditorHeadingLevel,
  type OgeEditorAlign,
  type OgeEditorDirection,
  type OgeEditorBlock,
  type OgeEditorDoc,
  type OgeEditorPoint,
  type OgeEditorSelection,
} from './lib/editor/editor-model';
export {
  ogeEditorState,
  deleteRange as ogeEditorDeleteRange,
  deleteSelection as ogeEditorDeleteSelection,
  deleteBackward as ogeEditorDeleteBackward,
  deleteForward as ogeEditorDeleteForward,
  insertText as ogeEditorInsertText,
  insertPlainText as ogeEditorInsertPlainText,
  insertFragment as ogeEditorInsertFragment,
  insertBreak as ogeEditorInsertBreak,
  splitBlock as ogeEditorSplitBlock,
  insertImage as ogeEditorInsertImage,
  insertRule as ogeEditorInsertRule,
  toggleMark as ogeEditorToggleMark,
  setColor as ogeEditorSetColor,
  setLink as ogeEditorSetLink,
  clearFormatting as ogeEditorClearFormatting,
  setBlockFormat as ogeEditorSetBlockFormat,
  toggleList as ogeEditorToggleList,
  indentList as ogeEditorIndent,
  outdentList as ogeEditorOutdent,
  setAlign as ogeEditorSetAlign,
  setDirection as ogeEditorSetDirection,
  selectAll as ogeEditorSelectAll,
  selectedFragment as ogeEditorSelectedFragment,
  type OgeEditorState,
  type OgeEditorBlockFormat,
  type OgeEditorDeleteUnit,
} from './lib/editor/editor-commands';
export {
  ogeEditorActiveState,
  ogeEditorCharacterCount,
  ogeEditorWordCount,
  ogeEditorHtmlLength,
  type OgeEditorActiveState,
  type OgeEditorBlockFormatValue,
} from './lib/editor/editor-queries';
export {
  OgeEditorHistory,
  type OgeEditorHistoryEntry,
  type OgeEditorChangeKind,
  type OgeEditorHistoryOptions,
} from './lib/editor/editor-history';
export {
  ogeEditorToHtml,
  ogeEditorFromHtml,
  ogeEditorFromText,
  ogeEditorReadDom,
  ogeSanitizeEditorHtml,
  ogeEditorSafeHref,
  ogeEditorSafeImageSrc,
  ogeEditorSafeColor,
  ogeEditorNormalizeLinkInput,
  ogeEditorEscape,
  ogeEditorRenderGroups,
  ogeEditorSerializeNodes,
  type OgeEditorRenderNode,
  type OgeEditorRenderText,
  type OgeEditorRenderElement,
  type OgeEditorRenderGroup,
  type OgeEditorRenderOptions,
  type OgeEditorUrlOptions,
  type OgeEditorParseOptions,
  type OgeEditorParseSource,
} from './lib/editor/editor-html';
export {
  OGE_EDITOR_TRUSTED_TYPES_POLICY,
  resetOgeEditorTrustedTypesPolicyForTests,
} from './lib/editor/editor-trusted-types';
export {
  OGE_EDITOR_BLOCK_ATTR,
  OGE_EDITOR_PLACEHOLDER_ATTR,
  renderOgeEditorDom,
  ogeEditorPointFromDom,
  ogeEditorPointToDom,
  ogeEditorReadSelection,
  ogeEditorWriteSelection,
} from './lib/editor/editor-dom';
export {
  ogeEditorApply,
  ogeEditorCommandFromName,
  ogeEditorKeyAction,
  ogeEditorMarkdownOnSpace,
  ogeEditorMarkdownOnEnter,
  type OgeEditorCommand,
  type OgeEditorCommandName,
  type OgeEditorApplyOptions,
  type OgeEditorKeyInput,
  type OgeEditorKeyAction,
  type OgeEditorKeyContext,
} from './lib/editor/editor-actions';
export {
  OGE_DEFAULT_EDITOR_MESSAGES,
  OGE_DEFAULT_EDITOR_CONFIG,
  mergeOgeEditorMessages,
  resolveOgeEditorConfig,
  type OgeEditorMessages,
  type OgeEditorMessagesInput,
  type OgeEditorToolMessages,
  type OgeEditorBlockMessages,
  type OgeEditorDialogMessages,
  type OgeEditorColorMessages,
  type OgeEditorCounterMessages,
  type OgeEditorAnnouncementMessages,
  type OgeEditorValidationMessages,
  type OgeEditorKeyMessages,
  type OgeEditorToolName,
  type OgeEditorPasteMode,
  type OgeEditorCounterMode,
  type OgeEditorConfig,
  type OgeEditorConfigInput,
} from './lib/editor/editor-config';
export {
  OGE_DEFAULT_EDITOR_TOOLBAR,
  OGE_EDITOR_TOOLS,
  buildOgeEditorToolbar,
  ogeEditorToolbarItems,
  ogeEditorBlockFormatMenu,
  ogeEditorBlockFormatCommand,
  ogeEditorBlockFormatLabel,
  ogeEditorToolCommand,
  ogeEditorAriaShortcut,
  ogeEditorShortcutLabel,
  ogeEditorIsMac,
  type OgeEditorToolKind,
  type OgeEditorShortcut,
  type OgeEditorToolContext,
  type OgeEditorCustomTool,
  type OgeEditorToolbarEntry,
  type OgeEditorToolView,
  type OgeEditorToolbarContext,
} from './lib/editor/editor-toolbar';
export {
  ogeEditorToolAction,
  ogeEditorCounterText,
  ogeEditorErrorText,
  ogeEditorLinkPrompt,
  ogeEditorLinkCommand,
  ogeEditorImagePrompts,
  ogeEditorDescribedBy,
  ogeEditorCssLength,
  type OgeEditorPopupKind,
  type OgeEditorToolAction,
} from './lib/editor/editor-shell';
export type {
  OgeEditorValueCommittedEvent,
  OgeEditorSelectionChangedEvent,
  OgeEditorCommandExecutedEvent,
  OgeEditorToolClickEvent,
  OgeEditorDialogKind,
  OgeEditorDialogOpeningEvent,
  OgeEditorFocusEvent,
} from './lib/editor/editor-events';
export {
  OgeEditorCore,
  truncateGraphemes as ogeEditorTruncateGraphemes,
  truncateDoc as ogeEditorTruncateDoc,
  type OgeEditorCoreOptions,
  type OgeEditorCoreHost,
  type OgeEditorPastingEvent,
} from './lib/editor/editor-core';
// --- upload ------------------------------------------------------------------
export type {
  OgeUploadFileStatus,
  OgeUploadErrorKind,
  OgeUploadFileError,
  OgeUploadFile,
  OgeUploadPreloadedFile,
  OgeUploadListType,
  OgeUploadDisplayMode,
  OgeUploadActionsLayout,
  OgeUploadDropEffect,
  OgeUploadMode,
  OgeUploadFileListOptions,
  OgeUploadChunkOptions,
  OgeUploadRetryOptions,
  OgeUploadFieldError,
  OgeUploadSelectionSource,
  OgeUploadAbortReason,
  OgeUploadCancelableEvent,
  OgeUploadFilesSelectingEvent,
  OgeUploadFilesSelectedEvent,
  OgeUploadFileRejectedEvent,
  OgeUploadFilesDroppedEvent,
  OgeUploadDropZoneEvent,
  OgeUploadFileRemovingEvent,
  OgeUploadFileRemovedEvent,
  OgeUploadClearingEvent,
  OgeUploadClearedEvent,
  OgeUploadPreviewShowingEvent,
  OgeUploadPreviewHiddenEvent,
  OgeUploadFileDownloadingEvent,
  OgeUploadUploadingEvent,
  OgeUploadStartedEvent,
  OgeUploadProgressEvent,
  OgeUploadUploadedEvent,
  OgeUploadFailedEvent,
  OgeUploadAbortedEvent,
  OgeUploadAllUploadedEvent,
  OgeUploadChunkUploadingEvent,
  OgeUploadChunkUploadedEvent,
  OgeUploadChunkFailedEvent,
  OgeUploadPausingEvent,
  OgeUploadPausedEvent,
  OgeUploadResumingEvent,
  OgeUploadResumedEvent,
  OgeUploadThumbnailFailedEvent,
} from './lib/upload/upload-types';
export type {
  OgeUploadRequest,
  OgeUploadChunkMetadata,
  OgeUploadPart,
  OgeUploadCallbacks,
  OgeUploadHandle,
  OgeUploadAdapter,
} from './lib/upload/transport-types';
export { createXhrUploadAdapter } from './lib/upload/xhr-adapter';
export {
  planChunks,
  chunkedLoaded,
  type OgeUploadChunk,
} from './lib/upload/chunk-plan';
export {
  formatFileSize,
  type OgeFormatFileSizeOptions,
} from './lib/upload/file-size';
export {
  fileExtension,
  matchesAccept,
  validateFile,
  validateSelection,
  type OgeUploadCandidate,
  type OgeUploadRestrictions,
  type OgeUploadValidationResult,
} from './lib/upload/file-validation';
export { isPreviewable, ObjectUrlRegistry } from './lib/upload/thumbnails';
export {
  DragDepthCounter,
  dataTransferHasFiles,
  dropEffectFor,
  readDataTransferFiles,
  readClipboardFiles,
} from './lib/upload/upload-dnd';
export {
  UploadQueue,
  type OgeResolvedChunkOptions,
  type OgeResolvedRetryOptions,
  type OgeUploadTimers,
  type OgeUploadQueueEvent,
  type OgeUploadTask,
  type OgeUploadQueueOptions,
} from './lib/upload/upload-queue';
export {
  OgeFileUploaderCore,
  type OgeFileUploaderCoreOptions,
  type OgeFileUploaderEvents,
  type OgeFileUploaderEventName,
  type OgeFileUploaderProps,
} from './lib/upload/file-uploader-core';
export {
  OGE_DEFAULT_UPLOAD_MESSAGES,
  OGE_DEFAULT_UPLOAD_CONFIG,
  mergeUploadMessages,
  resolveUploadConfig,
  formatUploadMessage,
  type OgeUploadButtonMessages,
  type OgeUploadDropZoneMessages,
  type OgeUploadStatusMessages,
  type OgeUploadValidationMessages,
  type OgeUploadAnnouncementMessages,
  type OgeUploadMessages,
  type OgeUploadMessagesInput,
  type OgeUploadConfig,
  type OgeUploadConfigInput,
} from './lib/upload/upload-messages';
export {
  OGE_DEFAULT_TOAST_DEFAULTS,
  OGE_TOAST_EXIT_MS,
  OGE_TOAST_ANNOUNCE_DELAY_MS,
  OGE_TOAST_POSITIONS,
  OgeToastCore,
  OgeToastRef,
  type OgeToastSeverity,
  type OgeToastPosition,
  type OgeToastCloseReason,
  type OgeToastAnnounce,
  type OgeToastAction,
  type OgeToastActionEvent,
  type OgeToastClosedEvent,
  type OgeToastBaseOptions,
  type OgeToastBasePatch,
  type OgeToastDefaults,
  type OgeResolvedToastOptions,
  type OgeToastProgressStyle,
  type OgeToastEntry,
  type OgeToastPromiseBaseOptions,
  type OgeToastRegion,
  type OgeToastCoreOptions,
} from './lib/overlay/toast-core';
export {
  lockBodyScroll,
  unlockBodyScroll,
  // `@internal`, but necessarily package-public: the scroll lock is module
  // state, and the modal specs that have to reset it between cases now live
  // one package away. Not re-exported from any component package's barrel.
  resetScrollLockForTests,
} from './lib/overlay/scroll-lock';
export {
  runAsyncGuard,
  createTypeAheadBuffer,
  matchByPrefix,
  OGE_DEFAULT_ACCORDION_MESSAGES,
  OGE_DEFAULT_ACCORDION_CONFIG,
  resolveOgeAccordionConfig,
  accordionItemDescriptor,
  resolveAccordionIndex,
  expandedIdsAfterExpand,
  expandedIdsAfterCollapse,
  canCollapseAccordionPanel,
  accordionAriaDisabled,
  shouldRenderAccordionPanel,
  sameAccordionIds,
  sameAccordionKeys,
  accordionNavIntent,
  accordionPageDirection,
  isAccordionTypeAheadKey,
  accordionTypeAheadStart,
  matchAccordionTitle,
  type OgeAsyncGuard,
  type OgeGuardHandlers,
  type OgeTypeAheadBuffer,
  type OgeAccordionTogglePosition,
  type OgeAccordionDisplayMode,
  type OgeAccordionStylingMode,
  type OgeAccordionSize,
  type OgeAccordionExpandGuard,
  type OgeAccordionContentLoader,
  type OgeAccordionItemData,
  type OgeAccordionExpandingEvent,
  type OgeAccordionCollapsingEvent,
  type OgeAccordionExpandedEvent,
  type OgeAccordionCollapsedEvent,
  type OgeAccordionItemClickEvent,
  type OgeAccordionContentLoadedEvent,
  type OgeAccordionContentFailedEvent,
  type OgeAccordionMessages,
  type OgeAccordionConfig,
  type OgeAccordionConfigInput,
  type OgeAccordionDescriptorCore,
  type OgeAccordionLoadState,
  type OgeAccordionNavIntent,
} from './lib/layout/accordion-core';
export {
  fitToolbarItems,
  OGE_DEFAULT_TOOLBAR_MESSAGES,
  OGE_DEFAULT_TOOLBAR_CONFIG,
  OGE_TOOLBAR_STOP_SELECTOR,
  resolveOgeToolbarConfig,
  applyToolbarOverride,
  toolbarItemId,
  toolbarDataDescriptors,
  withToolbarIndexes,
  orderToolbarDescriptors,
  toolbarCollapses,
  fitToolbarDescriptors,
  toolbarTextVisible,
  toolbarIconVisible,
  toolbarItemWidth,
  toolbarMenuItems,
  toolbarOverflowEvent,
  isToolbarTextEntry,
  isToolbarStopDisabled,
  readToolbarStyleMetrics,
  toolbarScrollState,
  loadToolbarItems,
  type OgeToolbarFitItem,
  type OgeToolbarFitOptions,
  type OgeToolbarFitResult,
  type OgeToolbarOverflowPolicy,
  type OgeToolbarItemLocation,
  type OgeToolbarLocateInMenu,
  type OgeToolbarDisplayMode,
  type OgeToolbarItemType,
  type OgeToolbarOverflow,
  type OgeToolbarOrientation,
  type OgeToolbarSize,
  type OgeToolbarStylingMode,
  type OgeToolbarItemSeverity,
  type OgeToolbarMenuCloseReason,
  type OgeToolbarItemData,
  type OgeToolbarItemClickEvent,
  type OgeToolbarItemHoldEvent,
  type OgeToolbarItemActiveChangedEvent,
  type OgeToolbarOverflowChangedEvent,
  type OgeToolbarMenuOpeningEvent,
  type OgeToolbarMenuClosingEvent,
  type OgeToolbarMenuClosedEvent,
  type OgeToolbarItemTemplateContextCore,
  type OgeToolbarMessages,
  type OgeToolbarConfig,
  type OgeToolbarConfigInput,
  type OgeToolbarDescriptorCore,
  type OgeToolbarItemOverride,
  type OgeToolbarFitRequest,
  type OgeToolbarDisplayDefaults,
  type OgeToolbarStyleMetrics,
  type OgeToolbarScrollState,
  type OgeToolbarDataSourceLike,
} from './lib/layout/toolbar-core';
export {
  normalizeSplitTracks,
  resizeSplitAt,
  splitSeparatorRange,
  splitTrackPx,
  OGE_DEFAULT_SPLITTER_MESSAGES,
  OGE_DEFAULT_SPLITTER_CONFIG,
  OGE_SPLITTER_GRIP_SIDES,
  OGE_SPLITTER_FULL_TRAVEL,
  resolveOgeSplitterConfig,
  splitterPaneDescriptor,
  resolveSplitterIndex,
  parseSplitterSize,
  roundSplitterValue,
  splitterBoundInTrackUnit,
  splitterTracksToSizes,
  sameSplitterSizes,
  splitterTracks,
  splitterTrackCss,
  splitterGridTemplate,
  splitterFlexiblePx,
  splitterBounds,
  splitterSeparatorRanges,
  splitterSizesWithRestored,
  loadSplitterPanes,
  splitterPaneOf,
  isSplitterPaneCollapsible,
  isSplitterPaneCollapsed,
  canResizeSplitterAt,
  splitterKeyShortcuts,
  splitterSeparatorLabel,
  splitterGripTitle,
  splitterGripPath,
  splitterCollapseSideInDirection,
  splitterKeyAction,
  startSplitterDrag,
  splitterDragDelta,
  type OgeSplitTrack,
  type OgeSplitBounds,
  type OgeSplitSeparatorRange,
  type OgeSplitterOrientation,
  type OgeSplitterGripSide,
  type OgeSplitterSize,
  type OgeSplitterPaneData,
  type OgeSplitterResizeStartEvent,
  type OgeSplitterResizeEvent,
  type OgeSplitterPaneCollapsingEvent,
  type OgeSplitterPaneCollapsedEvent,
  type OgeSplitterPaneHoldEvent,
  type OgeSplitterPaneClickEvent,
  type OgeSplitterMessages,
  type OgeSplitterConfig,
  type OgeSplitterConfigInput,
  type OgeSplitterDescriptorCore,
  type OgeSplitterDataSourceLike,
  type OgeSplitterView,
  type OgeSplitterKeyAction,
  type OgeSplitterKeyInput,
  type OgeSplitterDragHandlers,
} from './lib/layout/splitter-core';
export {
  OGE_DEFAULT_TREE_VIEW_MESSAGES,
  OGE_DEFAULT_TREE_VIEW_CONFIG,
  resolveOgeTreeViewConfig,
  type CheckState,
  type RowKey,
  type TreeFilterMode,
  type OgeTreeDataStructure,
  type OgeTreeSelectionMode,
  type OgeTreeCheckBoxesMode,
  type OgeTreeExpandEvent,
  type OgeTreeSearchMode,
  type OgeTreeSelectedKeysMode,
  type OgeTreeDropPosition,
  type OgeTreeSize,
  type OgeTreeExpr,
  type OgeTreeVirtualScrollOptions,
  type OgeTreeLoadChildren,
  type OgeTreeExpandingEvent,
  type OgeTreeCollapsingEvent,
  type OgeTreeExpandedEvent,
  type OgeTreeCollapsedEvent,
  type OgeTreeSelectionChangingEvent,
  type OgeTreeSelectionChangedEvent,
  type OgeTreeItemSelectionChangedEvent,
  type OgeTreeItemClickEvent,
  type OgeTreeChildrenLoadedEvent,
  type OgeTreeChildrenFailedEvent,
  type OgeTreeSelectAllChangedEvent,
  type OgeTreeReorderingEvent,
  type OgeTreeReorderedEvent,
  type OgeTreeViewMessages,
  type OgeTreeViewConfig,
  type OgeTreeViewConfigInput,
  // the shared decision layer both render layers run
  ancestorsOf,
  resolveSelectedKeys,
  OGE_TREE_DEFAULT_ITEM_HEIGHT,
  OGE_TREE_DRAG_THRESHOLD,
  OGE_TREE_DRAG_HOVER_EXPAND_MS,
  resolveTreeDropPosition,
  exceedsTreeDragThreshold,
  treeCanDrop,
  treeAccessor,
  buildTreeViewIndex,
  treeHasChildrenHint,
  treeExpandableKeys,
  treeSearchAccessors,
  createTreeSearchPredicate,
  treeVisibleKeys,
  treeFilterExpandedKeys,
  treeEffectiveExpanded,
  treeCheckStates,
  buildTreeViewNodes,
  treeSelectAllState,
  resolveTreeSelectByClick,
  resolveTreeItemHeight,
  treeNodeIndent,
  treeAriaSelected,
  treeAriaChecked,
  treeNodeDisabled,
  treeStepIndex,
  treeEdgeIndex,
  treeParentIndex,
  treeTypeAheadIndex,
  treeSiblingExpansion,
  nextTreeSelection,
  treeRangeSelection,
  treeAnchorIndex,
  treeLoadingAny,
  type TreeIndex,
  type OgeTreeViewNode,
  type OgeTreeLoadState,
  type OgeTreeIndexInput,
  type OgeTreeNodesInput,
} from './lib/navigation/tree-view-core';
// The highlight segment shape travels with the tree's view model, so the
// render layers get it from here rather than reaching past this package.
export type { SearchHighlightSegment } from '@oge-ui/core';
// the composed pipeline + key map — what a second tree renderer runs instead
// of re-deriving the steps above (the tree select's popup, ADR 0001)
export {
  buildTreeViewModel,
  nextTreeExpansion,
  treeChildrenLoadNeeded,
  planTreeViewKey,
  type OgeTreeViewModel,
  type OgeTreeViewModelInput,
  type OgeTreeKeyAction,
  type OgeTreeKeyPlan,
  type OgeTreeKeyInput,
} from './lib/navigation/tree-view-model';
// G5a tree view depth: cross-tree moves, label editing, "Load more" paging
export {
  fillTreeViewMessages,
  OGE_TREE_LOAD_MORE_PREFIX,
  treeLoadMoreKey,
  treeLoadMoreText,
  treeChildPageLimit,
  nextTreeChildPage,
  resolveTreeChildPageSize,
  type OgeTreeViewResolvedMessages,
  type OgeTreeTransferredEvent,
  type OgeTreeMoveSource,
  type OgeTreeChildPageEvent,
  type OgeTreeLoadMoreInfo,
} from './lib/navigation/tree-view-core';
export {
  ogeTreeDragGroupOf,
  registerOgeTreeDragPeer,
  ogeTreeDragPeerCount,
  ogeTreeDragPeerAt,
  ogeTreeLocateDrop,
  ogeTreeDragSourceOf,
  ogeTreeCommitMove,
  planTreeTransferKey,
  OGE_TREE_TRANSFER_SHORTCUTS,
  ogeTreeCutKey,
  ogeTreeHasCut,
  ogeTreeCut,
  ogeTreeCancelCut,
  ogeTreePaste,
  beginOgeTreeDrag,
  type OgeTreeDragSource,
  type OgeTreeDragTarget,
  type OgeTreeDragRowInfo,
  type OgeTreeDragPeer,
  type OgeTreeTransferKeyAction,
  type OgeTreeDragOptions,
} from './lib/navigation/tree-view-transfer';
export {
  treeCanEditNode,
  runTreeEditStart,
  planTreeEditKey,
  isTreeEditKey,
  runTreeEditCommit,
  type OgeTreeAllowEditing,
  type OgeTreeEditValidator,
  type OgeTreeEditStartingEvent,
  type OgeTreeEditingEvent,
  type OgeTreeEditedEvent,
  type OgeTreeEditKeyAction,
  type OgeTreeEditCommitResult,
  type OgeTreeEditCommitInput,
} from './lib/navigation/tree-view-editing';
// G5a drawer depth: built-in navigation items, touch swipe
export {
  ogeDrawerItemKey,
  buildOgeDrawerItems,
  ogeDrawerItemNavIndex,
  runOgeDrawerItemClick,
  type OgeDrawerItem,
  type OgeDrawerItemView,
  type OgeDrawerItemClickEvent,
  type OgeDrawerSelectionChangedEvent,
} from './lib/navigation/drawer-core';
export {
  OGE_DRAWER_SWIPE_EDGE,
  OGE_DRAWER_SWIPE_VELOCITY,
  ogeDrawerPhysicalEdge,
  ogeDrawerRailTooltipPlacement,
  ogeDrawerSwipeDistance,
  ogeDrawerSwipeAlong,
  ogeDrawerSwipeStarts,
  ogeDrawerSwipeOutcome,
  beginOgeDrawerSwipe,
  type OgeDrawerPhysicalEdge,
  type OgeDrawerSwipeOptions,
} from './lib/navigation/drawer-swipe';
export {
  OGE_DEFAULT_DRAWER_MESSAGES,
  OGE_DEFAULT_DRAWER_CONFIG,
  resolveOgeDrawerConfig,
  type OgeDrawerMode,
  type OgeDrawerPosition,
  type OgeDrawerLandmark,
  type OgeDrawerAutoFocus,
  type OgeDrawerCloseReason,
  type OgeDrawerOpeningEvent,
  type OgeDrawerClosingEvent,
  type OgeDrawerClosedEvent,
  type OgeDrawerModeChangedEvent,
  type OgeDrawerMessages,
  type OgeDrawerConfig,
  type OgeDrawerConfigInput,
} from './lib/navigation/drawer-core';
export {
  OGE_BREADCRUMB_ELLIPSIS_FALLBACK,
  OGE_DEFAULT_BREADCRUMB_MESSAGES,
  OGE_DEFAULT_BREADCRUMB_CONFIG,
  breadcrumbDataDescriptors,
  breadcrumbMenuItems,
  fitBreadcrumbDescriptors,
  resolveOgeBreadcrumbConfig,
  type OgeBreadcrumbCollapseMode,
  type OgeBreadcrumbItemData,
  type OgeBreadcrumbItemClickEvent,
  type OgeBreadcrumbDescriptorCore,
  type OgeBreadcrumbFitRequest,
  type OgeBreadcrumbFitResult,
  type OgeBreadcrumbMessages,
  type OgeBreadcrumbConfig,
  type OgeBreadcrumbConfigInput,
} from './lib/navigation/breadcrumb-core';
export {
  OGE_PAGE_ELLIPSIS,
  OGE_PAGINATION_DEFAULT_MAX_BUTTONS,
  OGE_PAGINATION_DEFAULT_COMPACT_BELOW,
  OGE_DEFAULT_PAGINATION_MESSAGES,
  OGE_DEFAULT_PAGINATION_CONFIG,
  clampPaginationIndex,
  formatPaginationMessage,
  paginationHasNextPage,
  paginationInfoText,
  paginationIsCompact,
  paginationPageCount,
  resolvePageCount,
  resolvePageRange,
  resolvePageWindow,
  resolveOgePaginationConfig,
  type OgePageCountRequest,
  type OgePageRangeRequest,
  type OgePageRangeResult,
  type OgePageWindowEntry,
  type OgePageWindowRequest,
  type OgePaginationCompactRequest,
  type OgePaginationDisplayMode,
  type OgePaginationSize,
  type OgePaginationPageChangedEvent,
  type OgePaginationPageSizeChangedEvent,
  type OgePaginationMessages,
  type OgePaginationConfig,
  type OgePaginationConfigInput,
} from './lib/navigation/pagination-core';
export {
  resolveDrawerMode,
  type OgeDrawerModeRequest,
  type OgeDrawerModeResult,
} from './lib/navigation/drawer-core';
export {
  OGE_DEFAULT_STEPPER_MESSAGES,
  OGE_DEFAULT_STEPPER_CONFIG,
  resolveOgeStepperConfig,
  stepItemDescriptor,
  resolveStepIndex,
  stepState,
  stepsCompleteBefore,
  isStepReachable,
  stepBlockReason,
  stepperArrowKeys,
  stepperKeyTarget,
  type OgeStepperOrientation,
  type OgeStepperDisplay,
  type OgeStepState,
  type OgeStepGuard,
  type OgeStepData,
  type OgeStepChangingEvent,
  type OgeStepChangedEvent,
  type OgeStepBlockReason,
  type OgeStepBlockedEvent,
  type OgeStepperFinishEvent,
  type OgeStepperMessages,
  type OgeStepperConfig,
  type OgeStepperConfigInput,
  type OgeStepDescriptorCore,
  type OgeStepReachRequest,
  type OgeStepperArrowKeys,
  type OgeStepperKeyRequest,
} from './lib/navigation/stepper-core';
export {
  OGE_DEFAULT_MENUBAR_MESSAGES,
  OGE_DEFAULT_MENUBAR_CONFIG,
  OGE_MENUBAR_HOVER_DELAY,
  resolveOgeMenubarConfig,
  resolveMenubarCompact,
  isMenubarCompact,
  pruneHiddenMenubarItems,
  menubarDataDescriptors,
  findMenubarItemPath,
  menubarStopDisabled,
  menubarBarKeys,
  menubarPanelItems,
  menubarPanelLabel,
  menubarPanelPlacement,
  menubarEventBase,
  menubarPopupCloseReason,
  menubarClosedReason,
  menubarItemDomId,
  type OgeMenubarOrientation,
  type OgeMenubarOpenMode,
  type OgeMenubarCloseReason,
  type OgeMenubarItemData,
  type OgeMenubarItemClickEvent,
  type OgeMenubarSubmenuOpeningEvent,
  type OgeMenubarSubmenuOpenedEvent,
  type OgeMenubarSubmenuClosingEvent,
  type OgeMenubarSubmenuClosedEvent,
  type OgeMenubarCompactChangedEvent,
  type OgeMenubarCompactRequest,
  type OgeMenubarCompactResult,
  type OgeMenubarPanelSource,
  type OgeMenubarDescriptorCore,
  type OgeMenubarBarKeys,
  type OgeMenubarMessages,
  type OgeMenubarConfig,
  type OgeMenubarConfigInput,
  OGE_MENUBAR_MORE_KEY,
  resolveMenubarOverflow,
  menubarOverflowItems,
  menubarBarEntries,
  menubarEntryHidden,
  menubarMoreActive,
  menubarItemPath,
  type OgeMenubarOverflowMode,
  type OgeMenubarItemOverflow,
  type OgeMenubarOverflowRequest,
} from './lib/navigation/menubar-core';

// --- forms -----------------------------------------------------------------

export {
  captionize,
  readPath,
  writePath,
  inferDataType,
  pickEditorType,
  isBareEditor,
  resolveItem,
  isFormItemVisible,
  orderByVisibleIndex,
  emptyValueForDataType,
  formColumnsCss,
  formColumnsCount,
} from './lib/forms/form-model';
export {
  evaluateOgeValidationRules,
  evaluateOgeFormCondition,
  asyncValidationRules,
  isEmptyFormValue,
} from './lib/forms/form-validation';
export {
  OGE_DEFAULT_FORMS_CONFIG,
  OGE_DEFAULT_FORMS_MESSAGES,
  resolveOgeFormsConfig,
  validationSummaryTitle,
  type OgeFormsConfig,
  type OgeFormsConfigInput,
  type OgeFormsMessages,
} from './lib/forms/form-config';
export type {
  OgeComparisonType,
  OgeFormCondition,
  OgeFormColCount,
  OgeFormDataType,
  OgeFormEditorOptions,
  OgeFormEditorType,
  OgeFormErrorEntry,
  OgeFormFieldChangedEvent,
  OgeFormGroupData,
  OgeFormItemDataBase,
  OgeFormLabelLocation,
  OgeFormScreenSize,
  OgeFormValidatedEvent,
  OgeResolvedFormItem,
  OgeValidationContext,
  OgeValidationRule,
} from './lib/forms/form-types';
export {
  sanitizeUrl,
  sanitizeResourceUrl,
  type OgeSanitizeUrlOptions,
} from './lib/security/sanitize-url';
export { prefersReducedMotion, motionScrollBehavior } from './lib/a11y/motion';
export {
  ogeIsRtl,
  ogeResolveDirection,
  observeDirection,
  type OgeDirection,
  type OgeDirectionInput,
} from './lib/a11y/direction';

// pointer gestures + pointer drag & drop (no HTML5 DnD in packages/)
export {
  OGE_GESTURE_THRESHOLD,
  OGE_LONG_PRESS_DELAY,
  beginPointerGesture,
  prepareTouchDrag,
  type OgePointerGestureHandle,
  type OgePointerGestureInput,
  type OgePointerGestureOptions,
} from './lib/gesture/pointer-gesture';
export {
  OGE_AUTO_SCROLL_EDGE,
  OGE_AUTO_SCROLL_MAX_SPEED,
  createAutoScroller,
  ogeEdgeScrollVelocity,
  type OgeAutoScrollOptions,
  type OgeAutoScroller,
} from './lib/gesture/auto-scroll';
export {
  beginPointerDragDrop,
  createDragGhost,
  ogeElementAtPoint,
  type OgeDragGhost,
  type OgePointerDragDropOptions,
} from './lib/gesture/pointer-drag-drop';

// the live-config helper behind provideOge<X>Config(() => …), re-exported for
// packages that depend on behavior but not on core
export { ogeLiveConfig } from '@oge-ui/core';

export {
  getOgePdfDefaultFont,
  isOgePdfWinAnsi,
  registerOgePdfFont,
  resolveOgePdfFont,
  setOgePdfDefaultFont,
  warnOgePdfUnicode,
  type OgePdfFont,
  type OgePdfFontData,
  type OgePdfFontTarget,
} from './lib/export/pdf-font';

// --- layout and feedback components (W8a) -----------------------------------
export {
  OGE_AVATAR_ICON_PATH,
  OGE_DEFAULT_AVATAR_CONFIG,
  OGE_DEFAULT_AVATAR_MESSAGES,
  ogeAvatarGroupWindow,
  ogeAvatarInitials,
  ogeAvatarLabel,
  ogeAvatarOverflowLabel,
  ogeAvatarOverflowText,
  ogeAvatarStatusLabel,
  ogeResolveAvatarContent,
  resolveOgeAvatarConfig,
  type OgeAvatarConfig,
  type OgeAvatarConfigInput,
  type OgeAvatarContentInput,
  type OgeAvatarContentType,
  type OgeAvatarGroupWindow,
  type OgeAvatarImageFailedEvent,
  type OgeAvatarImageLoadedEvent,
  type OgeAvatarItem,
  type OgeAvatarLabelInput,
  type OgeAvatarMessages,
  type OgeAvatarShape,
  type OgeAvatarSize,
  type OgeAvatarStatus,
} from './lib/layout/avatar-core';
export {
  OGE_BADGE_DEFAULT_MAX,
  OGE_DEFAULT_BADGE_CONFIG,
  OGE_DEFAULT_BADGE_MESSAGES,
  ogeAddDescribedBy,
  ogeBadgeAriaTarget,
  ogeBadgeDescription,
  ogeBadgeText,
  ogeBadgeVisible,
  ogeRemoveDescribedBy,
  resolveOgeBadgeConfig,
  syncOgeBadgeHostAria,
  type OgeBadgeConfig,
  type OgeBadgeConfigInput,
  type OgeBadgeMessages,
  type OgeBadgeOverlap,
  type OgeBadgePosition,
  type OgeBadgeSeverity,
  type OgeBadgeSize,
  type OgeBadgeTextInput,
  type OgeBadgeValue,
  type OgeBadgeVisibilityInput,
} from './lib/layout/badge-core';
export {
  OGE_CHIP_REMOVE_SHORTCUTS,
  OGE_DEFAULT_CHIP_CONFIG,
  OGE_DEFAULT_CHIP_MESSAGES,
  ogeChipFocusAfterRemove,
  ogeChipGridStops,
  ogeChipIsRemovable,
  ogeChipKeyIntent,
  ogeChipListRole,
  ogeChipNavIndex,
  ogeChipRemoveLabel,
  ogeChipTabStop,
  ogeChipToggleSelection,
  resolveOgeChipConfig,
  type OgeChipAvatar,
  type OgeChipConfig,
  type OgeChipConfigInput,
  type OgeChipGridStop,
  type OgeChipItem,
  type OgeChipItemClickEvent,
  type OgeChipItemRemovedEvent,
  type OgeChipItemRemovingEvent,
  type OgeChipKey,
  type OgeChipKeyIntent,
  type OgeChipListRole,
  type OgeChipMessages,
  type OgeChipRemovedEvent,
  type OgeChipSelectionChangedEvent,
  type OgeChipSelectionMode,
  type OgeChipSeverity,
  type OgeChipSize,
  type OgeChipStylingMode,
} from './lib/layout/chip-core';
export {
  OGE_ALERT_DISMISS_PATH,
  OGE_ALERT_ICON_PATHS,
  OGE_DEFAULT_ALERT_CONFIG,
  OGE_DEFAULT_ALERT_MESSAGES,
  ogeAlertFocusAfterClose,
  ogeAlertRole,
  ogeAlertSeverityLabel,
  resolveOgeAlertConfig,
  type OgeAlertClosedEvent,
  type OgeAlertClosingEvent,
  type OgeAlertConfig,
  type OgeAlertConfigInput,
  type OgeAlertLive,
  type OgeAlertMessages,
  type OgeAlertSeverity,
  type OgeAlertStylingMode,
} from './lib/layout/alert-core';
export {
  OGE_DEFAULT_TIMELINE_CONFIG,
  OGE_TIMELINE_DEFAULT_DATE_FORMAT,
  ogeTimelineDateTimeAttr,
  ogeTimelineHasOpposite,
  ogeTimelineItemSide,
  ogeTimelineTime,
  resolveOgeTimelineConfig,
  type OgeTimelineAlign,
  type OgeTimelineConfig,
  type OgeTimelineConfigInput,
  type OgeTimelineItem,
  type OgeTimelineMarkerVariant,
  type OgeTimelineOrientation,
  type OgeTimelineSeverity,
  type OgeTimelineTime,
} from './lib/layout/timeline-core';
export {
  OGE_DEFAULT_APP_BAR_CONFIG,
  ogeAppBarAcceptsLabel,
  ogeAppBarRole,
  resolveOgeAppBarConfig,
  type OgeAppBarCenterAlign,
  type OgeAppBarColor,
  type OgeAppBarConfig,
  type OgeAppBarConfigInput,
  type OgeAppBarLandmark,
  type OgeAppBarPosition,
  type OgeAppBarPositionMode,
  type OgeAppBarSize,
} from './lib/layout/app-bar-core';
export {
  OGE_DEFAULT_FAB_CONFIG,
  OGE_DEFAULT_FAB_MESSAGES,
  OGE_FAB_PLUS_PATH,
  ogeSpeedDialAwayKey,
  ogeSpeedDialDirection,
  ogeSpeedDialItemKey,
  ogeSpeedDialNavIndex,
  ogeSpeedDialToggleKey,
  ogeSpeedDialTowardKey,
  ogeSpeedDialVertical,
  resolveOgeFabConfig,
  type OgeFabClickEvent,
  type OgeFabConfig,
  type OgeFabConfigInput,
  type OgeFabMessages,
  type OgeFabPosition,
  type OgeFabPositionMode,
  type OgeFabSeverity,
  type OgeFabSize,
  type OgeSpeedDialDirection,
  type OgeSpeedDialItem,
  type OgeSpeedDialItemClickEvent,
  type OgeSpeedDialKeyIntent,
  type OgeSpeedDialLabelMode,
  type OgeSpeedDialOpenMode,
} from './lib/button/fab-core';
export {
  OGE_DATA_VIEW_DEFAULT_MIN_ITEM_WIDTH,
  OGE_DATA_VIEW_PAGER_BUTTONS,
  OGE_DEFAULT_DATA_VIEW_CONFIG,
  OGE_DEFAULT_DATA_VIEW_MESSAGES,
  ogeDataViewClampPage,
  ogeDataViewCollator,
  ogeDataViewCompare,
  ogeDataViewDisplayText,
  ogeDataViewField,
  ogeDataViewFormat,
  ogeDataViewInfoText,
  ogeDataViewIsEllipsis,
  ogeDataViewKey,
  ogeDataViewKeyIntent,
  ogeDataViewMatches,
  ogeDataViewMeasureColumns,
  ogeDataViewPageCount,
  ogeDataViewPageItems,
  ogeDataViewPagerWindow,
  ogeDataViewProcess,
  ogeDataViewRole,
  ogeDataViewSearchText,
  ogeDataViewStyleVars,
  ogeDataViewTabStop,
  ogeDataViewToggleSelection,
  resolveOgeDataViewConfig,
  type OgeDataViewConfig,
  type OgeDataViewConfigInput,
  type OgeDataViewDisplayExpr,
  type OgeDataViewItemClickEvent,
  type OgeDataViewKey,
  type OgeDataViewKeyExpr,
  type OgeDataViewKeyInput,
  type OgeDataViewKeyIntent,
  type OgeDataViewLayout,
  type OgeDataViewLayoutChangedEvent,
  type OgeDataViewMessages,
  type OgeDataViewOptionsChangedEvent,
  type OgeDataViewPageChangedEvent,
  type OgeDataViewPagerEntry,
  type OgeDataViewProcessOptions,
  type OgeDataViewSearchExpr,
  type OgeDataViewSelectionChangedEvent,
  type OgeDataViewSelectionMode,
  type OgeDataViewSort,
  type OgeDataViewSortChangedEvent,
  type OgeDataViewSortDirection,
  type OgeDataViewSortOption,
} from './lib/layout/data-view-core';
export {
  OGE_DEFAULT_TILE_LAYOUT_CONFIG,
  OGE_DEFAULT_TILE_LAYOUT_MESSAGES,
  OGE_TILE_LAYOUT_DEFAULTS,
  ogeTileLayoutAutoRows,
  ogeTileLayoutClampResize,
  ogeTileLayoutClampSpan,
  ogeTileLayoutDropIndex,
  ogeTileLayoutKeyIntent,
  ogeTileLayoutMoveState,
  ogeTileLayoutMovedText,
  ogeTileLayoutResizeSpan,
  ogeTileLayoutResizeState,
  ogeTileLayoutResizedText,
  ogeTileLayoutResolve,
  ogeTileLayoutShortcuts,
  ogeTileLayoutStep,
  ogeTileLayoutTabStop,
  ogeTileLayoutTemplateColumns,
  ogeTileLayoutTileLabel,
  ogeTileLayoutToState,
  ogeTileLayoutUnchangedText,
  resolveOgeTileLayoutConfig,
  sanitizeOgeTileLayoutState,
  type OgeTileLayoutChangeSource,
  type OgeTileLayoutChangedEvent,
  type OgeTileLayoutConfig,
  type OgeTileLayoutConfigInput,
  type OgeTileLayoutDirection,
  type OgeTileLayoutItemData,
  type OgeTileLayoutKey,
  type OgeTileLayoutKeyInput,
  type OgeTileLayoutKeyIntent,
  type OgeTileLayoutMessages,
  type OgeTileLayoutRect,
  type OgeTileLayoutReorderedEvent,
  type OgeTileLayoutReorderingEvent,
  type OgeTileLayoutResizable,
  type OgeTileLayoutResizeInput,
  type OgeTileLayoutResizedEvent,
  type OgeTileLayoutResizingEvent,
  type OgeTileLayoutResolveOptions,
  type OgeTileLayoutResolvedTile,
  type OgeTileLayoutSpan,
  type OgeTileLayoutState,
  type OgeTileLayoutTileState,
} from './lib/layout/tile-layout-core';
export {
  OGE_CAROUSEL_DEFAULT_INTERVAL,
  OGE_CAROUSEL_DRAGGING_CLASS,
  OGE_CAROUSEL_MIN_INTERVAL,
  OGE_CAROUSEL_SWIPE_DISTANCE,
  OGE_CAROUSEL_SWIPE_RATIO,
  OGE_DEFAULT_CAROUSEL_CONFIG,
  OGE_DEFAULT_CAROUSEL_MESSAGES,
  OgeCarouselAutoplay,
  beginOgeCarouselSwipe,
  ogeCarouselClampIndex,
  ogeCarouselIndexFromOffset,
  ogeCarouselLive,
  ogeCarouselMaxIndex,
  ogeCarouselMeasureStep,
  ogeCarouselPerView,
  ogeCarouselPickerKey,
  ogeCarouselPickerLabel,
  ogeCarouselPickerMode,
  ogeCarouselPickerTarget,
  ogeCarouselPositions,
  ogeCarouselScrollOffset,
  ogeCarouselScrollTo,
  ogeCarouselSlideLabel,
  ogeCarouselSlideVisible,
  ogeCarouselStep,
  ogeCarouselSwipeTarget,
  resolveOgeCarouselConfig,
  type OgeCarouselAutoplayChangedEvent,
  type OgeCarouselAutoplayOptions,
  type OgeCarouselChangeSource,
  type OgeCarouselConfig,
  type OgeCarouselConfigInput,
  type OgeCarouselHoldReason,
  type OgeCarouselIndicators,
  type OgeCarouselItem,
  type OgeCarouselMessages,
  type OgeCarouselPickerIntent,
  type OgeCarouselPickerMode,
  type OgeCarouselSlideChangedEvent,
  type OgeCarouselSwipeOptions,
} from './lib/layout/carousel-core';
export {
  OGE_DEFAULT_LIST_VIEW_CONFIG,
  OGE_DEFAULT_LIST_VIEW_MESSAGES,
  OGE_LIST_VIEW_FALLBACK_HEIGHT,
  OGE_LIST_VIEW_GROUP_HEIGHT,
  OGE_LIST_VIEW_ITEM_HEIGHT,
  OGE_LIST_VIEW_LOAD_THRESHOLD,
  OGE_LIST_VIEW_OVERSCAN,
  ogeListViewActionForKey,
  ogeListViewActionFromTarget,
  ogeListViewActionShortcuts,
  ogeListViewActionsText,
  ogeListViewBuildRows,
  ogeListViewClick,
  ogeListViewExprValue,
  ogeListViewFilter,
  ogeListViewFirstEnabled,
  ogeListViewIndexFromTarget,
  ogeListViewInitialActive,
  ogeListViewItemId,
  ogeListViewKeyDown,
  ogeListViewKeyOf,
  ogeListViewMatchesShortcut,
  ogeListViewOffsetTree,
  ogeListViewRange,
  ogeListViewRole,
  ogeListViewSameKeys,
  ogeListViewScrollTarget,
  ogeListViewSegments,
  ogeListViewSelectionDiff,
  ogeListViewShouldLoadMore,
  ogeListViewSwipeAxis,
  ogeListViewSwipeOpens,
  ogeListViewSwipeReveal,
  ogeListViewSwipeTranslate,
  ogeListViewTextOf,
  ogeListViewToggle,
  ogeListViewVirtualSettings,
  ogeListViewWindow,
  ogeListViewWindowHasIndex,
  resolveOgeListViewConfig,
  type OgeListViewActionSeverity,
  type OgeListViewActiveItemChangedEvent,
  type OgeListViewClickInput,
  type OgeListViewConfig,
  type OgeListViewConfigInput,
  type OgeListViewExpr,
  type OgeListViewGroupRow,
  type OgeListViewItemAction,
  type OgeListViewItemActionClickEvent,
  type OgeListViewItemClickEvent,
  type OgeListViewItemRow,
  type OgeListViewKey,
  type OgeListViewKeyInput,
  type OgeListViewLoadMoreEvent,
  type OgeListViewMessages,
  type OgeListViewNavResult,
  type OgeListViewNavState,
  type OgeListViewPageLoadMode,
  type OgeListViewRow,
  type OgeListViewRows,
  type OgeListViewSearchExpr,
  type OgeListViewSearchMode,
  type OgeListViewSegment,
  type OgeListViewSelectionChangedEvent,
  type OgeListViewSelectionMode,
  type OgeListViewVirtualScrollOptions,
  type OgeListViewVirtualSettings,
  type OgeListViewWindow,
} from './lib/layout/list-view-core';
