import { describe, expect, it } from 'vitest';
import * as behavior from './index';

/**
 * The barrel is the whole contract with the React render layer: it imports
 * `@oge-ui/behavior` and nothing else (ADR 0001), so an entry point that
 * silently stops being exported here breaks a render layer without breaking
 * a single family spec. One list, one guard.
 */
const ENTRY_POINTS = [
  // button
  'OgeButtonPress',
  'resolveOgeButtonsConfig',
  'applyButtonGroupSelection',
  'buttonGroupRole',
  'buttonGroupNavIndex',
  'resolveClickGuard',
  // overlay
  'OgeAnchoredPanelCore',
  'resolvePopupPosition',
  'getTabbableElements',
  'trapTabKey',
  'pushOverlay',
  'isTopOverlay',
  'lockBodyScroll',
  'OGE_DEFAULT_OVERLAY_TIMINGS',
  // export fonts (Unicode PDF text)
  'setOgePdfDefaultFont',
  'getOgePdfDefaultFont',
  'isOgePdfWinAnsi',
  'registerOgePdfFont',
  'resolveOgePdfFont',
  'warnOgePdfUnicode',
  // gestures
  'beginPointerGesture',
  'prepareTouchDrag',
  'beginPointerDragDrop',
  'createAutoScroller',
  'ogeEdgeScrollVelocity',
  'createDragGhost',
  'ogeElementAtPoint',
  'ogeVisibleViewport',
  'popupAvailableHeight',
  // adaptive
  'OgeAdaptiveSheetCore',
  'resolveAdaptivePresentation',
  'watchAdaptiveViewport',
  'matchesAdaptiveViewport',
  'OGE_DEFAULT_ADAPTIVE_CONFIG',
  // live announcements
  'OgeLiveAnnouncerCore',
  'getOgeLiveAnnouncer',
  // menu
  'menuMoveIndex',
  'OgeMenuTypeAhead',
  // inputs
  'OgeInputCommit',
  'OgeMaskCore',
  'parseMask',
  'ogeMaskComplete',
  'ogeMaskInputMode',
  'OgeSelectListCore',
  'OgeListVirtualizerCore',
  'OgeRemoteListCore',
  'isNearScrollEnd',
  'ogeAllowDropDownClose',
  'ogeSelectAllState',
  'ogeToggleAllValues',
  'ogeChipOverflow',
  'ogeComboCellText',
  'ogeComboGridTemplate',
  'ogeComboColumnTarget',
  'createNumberFormatter',
  'formatNumberWhileTyping',
  'createNumberTypingGrouper',
  'numberWheelDirection',
  'OgeDateSegmentCore',
  'dateSegmentPlaceholders',
  'resolveHour12',
  'hourColumnOptions',
  'withTimePart',
  'nowForType',
  'timeDisplayOptions',
  'ogeDateRangePresets',
  'dateRangePresetLabel',
  'dateRangePresetActive',
  'parseDateText',
  'monthCells',
  'sliderKeyboardTarget',
  'startSliderDrag',
  'contrastRatio',
  'contrastLevels',
  'applyColorChannelText',
  'colorPaletteNavIndex',
  'OGE_COLOR_PALETTE_PRESETS',
  'toggleChoiceValue',
  'selectAllState',
  'applySelectAll',
  'applyToggleGroupPress',
  'graphemeCount',
  'resolveOgeInputsConfig',
  // tabs
  'resolveOgeTabsConfig',
  'canSelectTab',
  // layout
  'resolveOgeAccordionConfig',
  'splitterKeyAction',
  'fitToolbarDescriptors',
  'resolveOgeCardConfig',
  // navigation
  'buildTreeViewModel',
  'planTreeViewKey',
  'fitBreadcrumbDescriptors',
  'resolveDrawerMode',
  'menubarBarKeys',
  'paginationIsCompact',
  'stepperKeyTarget',
  // forms
  'resolveItem',
  'evaluateOgeValidationRules',
  'evaluateOgeFormCondition',
  'isFormItemVisible',
  'resolveOgeFormsConfig',
  'formColumnsCss',
  // tree list
  'OgeTreeListCore',
  'ogeTreeCsv',
  'ogeTreeDataSource',
  'ogeTreeDropPosition',
  'ogeTreeHeaderValueGroups',
  'ogeTreeHeaderValueText',
  // grid
  'buildOgeExportItems',
  'ogeExportColumnsOf',
  'ogeExportColumnOf',
  'ogeExportHeaderCells',
  'ogeExportItemsOf',
  'ogeExportCellText',
  'mergeOgeExportStyles',
  'ogeExportScope',
  'ogeSummaryText',
  'ogeColumnSummaryText',
  'ogeGridExportItems',
  'ogeGridExportLoadOptions',
  'OgeGridKeyboardNavCore',
  'OgeGridColumnLayoutCore',
  'OgeGridRowVirtualizerCore',
  'OgeGridDeferredChildrenCore',
  'OgeGridEditingState',
  'OgeGridSortState',
  'OgeGridFilterState',
  'OgeGridSelectionState',
  'OgeGridEditingCore',
  'formatCellValue',
  'booleanCellLabel',
  'resizedColumnWidth',
  'ogeGridHeaderKeyCommand',
  'ogeColumnSeparatorKeyCommand',
  'ogeColumnMoveTarget',
  'ogeRowMoveDirection',
  'ogeTreeRowKeyMove',
  'ogeGroupChipKeyCommand',
  'builderToExpr',
  'operatorsFor',
  'rowFilterExpr',
  'rowClickSelectionIntent',
  'deferredToggleExpr',
  'toggleHeaderValue',
  'OgeGridStatePersistenceCore',
  'resolveOgeGridColumns',
  'adaptiveHiddenColumnIds',
  'buildRowFilterExpr',
  'OgeGridAnnouncements',
  'syncOgeEditorErrorAria',
  'OgeGridRangeSelectionCore',
  'ogeRangeLattice',
  'buildOgeRangeTsv',
  'parseOgeTsv',
  'planOgeGridPaste',
  'parseOgeCellText',
  'ogeFillSeries',
  'ogeFillTarget',
  'ogeKeyboardFillPlan',
  'ogeGridEditShortcut',
  'OgeGridEditHistory',
  'resolveOgeConditionalFormat',
  'ogeClassList',
  'OgePreparedTracker',
  'computeOgeGridSpans',
  'headerConditionExpr',
  'groupHeaderValuesByDate',
  'ogePagerPages',
  'ogeParsePageInput',
  'registerOgeRowDragParticipant',
  'findOgeRowDragParticipant',
  'ogeMeasureAutoWidth',
  'ogeStickyGroupChain',
  'ogeGroupValueText',
  'isOgeDateType',
  // a11y
  'prefersReducedMotion',
  'motionScrollBehavior',
] as const;

describe('the @oge-ui/behavior barrel', () => {
  for (const name of ENTRY_POINTS) {
    it(`exports ${name}`, () => {
      expect(behavior).toHaveProperty(name);
      expect(
        (behavior as unknown as Record<string, unknown>)[name],
      ).toBeDefined();
    });
  }

  it('re-exports the shared engine tables the two layers must agree on', () => {
    expect(behavior.OGE_DEFAULT_OVERLAY_TIMINGS.menuHideDelayMs).toBe(300);
    expect(behavior.OGE_SELECT_OPTION_HEIGHT).toEqual({
      sm: 28,
      md: 34,
      lg: 40,
    });
    expect(behavior.OGE_DEFAULT_COLOR_PALETTE.length).toBe(50);
  });
});
