import { describe, expect, it } from 'vitest';
import * as behavior from './index';

/**
 * The barrel is the whole contract with the React render layer: it imports
 * `@oge-ui/behavior` and nothing else (ADR 0001), so an entry point that
 * silently stops being exported here breaks a render layer without breaking
 * a single family spec. One list, one guard.
 */
const ENTRY_POINTS = [
  // button
  'OgeButtonPress',
  'resolveOgeButtonsConfig',
  'applyButtonGroupSelection',
  'buttonGroupRole',
  'buttonGroupNavIndex',
  'resolveClickGuard',
  'resolveButtonSelectionState',
  'applyButtonToggle',
  // layout and feedback components (W8a)
  // list view (W8d)
  'resolveOgeListViewConfig',
  'ogeListViewBuildRows',
  'ogeListViewFilter',
  'ogeListViewWindow',
  'ogeListViewKeyDown',
  'ogeListViewClick',
  'ogeListViewSwipeReveal',
  // action sheet (W8d)
  'OgeActionSheetCore',
  'ogeActionSheetKeyIntent',
  'ogeActionSheetOrder',
  'beginOgeActionSheetSwipe',
  // carousel (W8d)
  'resolveOgeCarouselConfig',
  'ogeCarouselStep',
  'ogeCarouselSwipeTarget',
  'ogeCarouselPickerKey',
  'ogeCarouselSlideLabel',
  'ogeCarouselScrollTo',
  'beginOgeCarouselSwipe',
  'OgeCarouselAutoplay',
  // tile layout (W8d)
  'resolveOgeTileLayoutConfig',
  'ogeTileLayoutResolve',
  'ogeTileLayoutKeyIntent',
  'ogeTileLayoutStep',
  'ogeTileLayoutDropIndex',
  'ogeTileLayoutResizeSpan',
  'ogeTileLayoutMoveState',
  'ogeTileLayoutResizeState',
  'sanitizeOgeTileLayoutState',
  // data view (W8d)
  'resolveOgeDataViewConfig',
  'ogeDataViewProcess',
  'ogeDataViewPageItems',
  'ogeDataViewPagerWindow',
  'ogeDataViewKeyIntent',
  'ogeDataViewToggleSelection',
  'ogeDataViewTabStop',
  'ogeDataViewMeasureColumns',
  'resolveOgeAvatarConfig',
  'ogeAvatarInitials',
  'ogeResolveAvatarContent',
  'ogeAvatarLabel',
  'ogeAvatarGroupWindow',
  'ogeAvatarOverflowLabel',
  'resolveOgeBadgeConfig',
  'ogeBadgeVisible',
  'ogeBadgeText',
  'ogeBadgeDescription',
  'syncOgeBadgeHostAria',
  'resolveOgeChipConfig',
  'ogeChipListRole',
  'ogeChipKeyIntent',
  'ogeChipNavIndex',
  'ogeChipTabStop',
  'ogeChipToggleSelection',
  'ogeChipFocusAfterRemove',
  'ogeChipGridStops',
  'resolveOgeAlertConfig',
  'ogeAlertRole',
  'ogeAlertFocusAfterClose',
  'OGE_ALERT_ICON_PATHS',
  'resolveOgeTimelineConfig',
  'ogeTimelineItemSide',
  'ogeTimelineTime',
  'ogeTimelineDateTimeAttr',
  'resolveOgeAppBarConfig',
  'ogeAppBarRole',
  'resolveOgeFabConfig',
  'ogeSpeedDialDirection',
  'ogeSpeedDialToggleKey',
  'ogeSpeedDialItemKey',
  'ogeSpeedDialNavIndex',
  // overlay
  'OgeAnchoredPanelCore',
  'resolvePopupPosition',
  'getTabbableElements',
  'trapTabKey',
  'pushOverlay',
  'isTopOverlay',
  'lockBodyScroll',
  'OGE_DEFAULT_OVERLAY_TIMINGS',
  // dialog helpers + non-modal window (G5a)
  'resolveOgeDialog',
  'OgeDialogCore',
  'ogeDialogEnterIsPrimary',
  'OGE_DIALOG_ICONS',
  'OgeWindowCore',
  'resolveOgeWindowPlacement',
  'clampOgeWindowPosition',
  'resizeOgeWindowRect',
  'ogeWindowKeyCommand',
  'registerOgeWindow',
  'bringOgeWindowToFront',
  'modalPlacementClass',
  'overlayStackSize',
  'ogeOverlayMessage',
  // anchored overlays (G5a): popover, arrow, context-menu delegation
  'OgePopoverCore',
  'popoverTriggerAria',
  'popoverPanelAria',
  'syncPopoverTriggerAria',
  'supportsAriaExpanded',
  'resolvePopoverInitialFocus',
  'nextTabbableAfter',
  'resolvePopupArrow',
  'popupArrowInset',
  'OGE_POPUP_ARROW_SIZE',
  'ogeContextMenuPoint',
  'ogeContextMenuApiTarget',
  'ogeContextMenuTarget',
  'ogeResolveContextMenuOpen',
  // export fonts (Unicode PDF text)
  'setOgePdfDefaultFont',
  'getOgePdfDefaultFont',
  'isOgePdfWinAnsi',
  'registerOgePdfFont',
  'resolveOgePdfFont',
  'warnOgePdfUnicode',
  // gestures
  'beginPointerGesture',
  'prepareTouchDrag',
  'beginPointerDragDrop',
  'createAutoScroller',
  'ogeEdgeScrollVelocity',
  'createDragGhost',
  'ogeElementAtPoint',
  'ogeVisibleViewport',
  'popupAvailableHeight',
  // adaptive
  'OgeAdaptiveSheetCore',
  'resolveAdaptivePresentation',
  'watchAdaptiveViewport',
  'matchesAdaptiveViewport',
  'OGE_DEFAULT_ADAPTIVE_CONFIG',
  // live announcements
  'OgeLiveAnnouncerCore',
  'getOgeLiveAnnouncer',
  // menu
  'menuMoveIndex',
  'OgeMenuTypeAhead',
  'menuItemRole',
  'menuItemSegments',
  'applyMenuItemCheck',
  'menuItemKeepsOpen',
  'menuRetainedActiveIndex',
  // inputs
  'OgeInputCommit',
  'OgeMaskCore',
  'parseMask',
  'ogeMaskComplete',
  'ogeMaskInputMode',
  'OgeSelectListCore',
  'OgeListVirtualizerCore',
  'OgeRemoteListCore',
  'isNearScrollEnd',
  'ogeAllowDropDownClose',
  'ogeSelectAllState',
  'ogeToggleAllValues',
  'ogeChipOverflow',
  'ogeComboCellText',
  'ogeComboGridTemplate',
  'ogeComboColumnTarget',
  'createNumberFormatter',
  'formatNumberWhileTyping',
  'createNumberTypingGrouper',
  'numberWheelDirection',
  'OgeDateSegmentCore',
  'dateSegmentPlaceholders',
  'resolveHour12',
  'hourColumnOptions',
  'withTimePart',
  'nowForType',
  'timeDisplayOptions',
  'ogeDateRangePresets',
  'dateRangePresetLabel',
  'dateRangePresetActive',
  'parseDateText',
  'monthCells',
  'sliderKeyboardTarget',
  'startSliderDrag',
  'contrastRatio',
  'contrastLevels',
  'applyColorChannelText',
  'colorPaletteNavIndex',
  'OGE_COLOR_PALETTE_PRESETS',
  'toggleChoiceValue',
  'selectAllState',
  'applySelectAll',
  'applyToggleGroupPress',
  // W8b list box + transfer list
  'OgeListBoxCore',
  'ogeListBoxSections',
  'ogeTransferSplit',
  'ogeTransferMove',
  'ogeTransferMovableValues',
  'ogeTransferKeyCommand',
  'ogeTransferKeyShortcuts',
  'ogeTransferDropSide',
  'ogeTransferAnnouncement',
  'ogeTransferCountText',
  'ogeTransferOpposite',
  // W8b rating + one-time-code input
  'snapRatingValue',
  'ratingItemStates',
  'ratingKeyboardTarget',
  'ratingRadioKeyTarget',
  'ratingValueFromPointer',
  'ratingPointerRatio',
  'ratingPressValue',
  'ratingValueText',
  'resolveRatingSemantics',
  'otpInsert',
  'otpBackspace',
  'otpDelete',
  'otpNavigationTarget',
  'otpTypedText',
  'sanitizeOtpText',
  'normalizeOtpValue',
  'otpCellLabel',
  // W8b signature pad + mention
  'OgeSignatureCore',
  'buildOgeSignatureSvg',
  'renderOgeSignature',
  'ogeSignaturePointFrom',
  'ogeSvgDataUrl',
  'parseOgeSignatureSvg',
  'OgeMentionCore',
  'ogeFindMentionQuery',
  'ogeInsertMention',
  'ogeShiftMentions',
  'ogeMentionKeyCommand',
  'ogeCaretRect',
  'graphemeCount',
  'resolveOgeInputsConfig',
  // tabs
  'resolveOgeTabsConfig',
  'canSelectTab',
  // layout
  'resolveOgeAccordionConfig',
  'ogeProgressRingGeometry',
  'ogeProgressRatio',
  'OgeLoadPanelCore',
  'ogeAcquireLoadPanelTarget',
  'ogeResolveLoadPanelTarget',
  'runOgeExpansionToggle',
  'flattenOgePanelBarItems',
  'ogePanelBarKeyAction',
  'splitterKeyAction',
  'fitToolbarDescriptors',
  'resolveOgeCardConfig',
  // navigation
  'buildTreeViewModel',
  'planTreeViewKey',
  'fitBreadcrumbDescriptors',
  'resolveDrawerMode',
  'menubarBarKeys',
  'resolveMenubarOverflow',
  'menubarBarEntries',
  'menubarItemPath',
  'paginationIsCompact',
  'stepperKeyTarget',
  'registerOgeTreeDragPeer',
  'beginOgeTreeDrag',
  'ogeTreeCommitMove',
  'ogeTreePaste',
  'runTreeEditCommit',
  'nextTreeChildPage',
  'fillTreeViewMessages',
  'buildOgeDrawerItems',
  'runOgeDrawerItemClick',
  'beginOgeDrawerSwipe',
  'ogeDrawerSwipeOutcome',
  // forms
  'resolveItem',
  'evaluateOgeValidationRules',
  'evaluateOgeFormCondition',
  'isFormItemVisible',
  'resolveOgeFormsConfig',
  'formColumnsCss',
  // tree list
  'OgeTreeListCore',
  'ogeTreeCsv',
  'ogeTreeDataSource',
  'ogeTreeDropPosition',
  'ogeTreeHeaderValueGroups',
  'ogeTreeHeaderValueText',
  // grid
  'buildOgeExportItems',
  'ogeExportColumnsOf',
  'ogeExportColumnOf',
  'ogeExportHeaderCells',
  'ogeExportItemsOf',
  'ogeExportCellText',
  'mergeOgeExportStyles',
  'ogeExportScope',
  'ogeSummaryText',
  'ogeColumnSummaryText',
  'ogeGridExportItems',
  'ogeGridExportLoadOptions',
  'OgeGridKeyboardNavCore',
  'OgeGridColumnLayoutCore',
  'OgeGridRowVirtualizerCore',
  'OgeGridDeferredChildrenCore',
  'OgeGridEditingState',
  'OgeGridSortState',
  'OgeGridFilterState',
  'OgeGridSelectionState',
  'OgeGridEditingCore',
  'formatCellValue',
  'booleanCellLabel',
  'resizedColumnWidth',
  'ogeGridHeaderKeyCommand',
  'ogeColumnSeparatorKeyCommand',
  'ogeColumnMoveTarget',
  'ogeRowMoveDirection',
  'ogeTreeRowKeyMove',
  'ogeGroupChipKeyCommand',
  'builderToExpr',
  'operatorsFor',
  'rowFilterExpr',
  'rowClickSelectionIntent',
  'deferredToggleExpr',
  'toggleHeaderValue',
  'OgeGridStatePersistenceCore',
  'resolveOgeGridColumns',
  'adaptiveHiddenColumnIds',
  'buildRowFilterExpr',
  'OgeGridAnnouncements',
  'syncOgeEditorErrorAria',
  'OgeGridRangeSelectionCore',
  'ogeRangeLattice',
  'buildOgeRangeTsv',
  'parseOgeTsv',
  'planOgeGridPaste',
  'parseOgeCellText',
  'ogeFillSeries',
  'ogeFillTarget',
  'ogeKeyboardFillPlan',
  'ogeGridEditShortcut',
  'OgeGridEditHistory',
  'resolveOgeConditionalFormat',
  'ogeClassList',
  'OgePreparedTracker',
  'computeOgeGridSpans',
  'headerConditionExpr',
  'groupHeaderValuesByDate',
  'ogePagerPages',
  'ogeParsePageInput',
  'registerOgeRowDragParticipant',
  'findOgeRowDragParticipant',
  'ogeMeasureAutoWidth',
  'ogeStickyGroupChain',
  'ogeGroupValueText',
  'isOgeDateType',
  // a11y
  'prefersReducedMotion',
  'motionScrollBehavior',
  // rich-text editor (W8e)
  'OgeEditorCore',
  'OgeEditorHistory',
  'ogeEditorState',
  'ogeEditorApply',
  'ogeEditorCommandFromName',
  'ogeEditorKeyAction',
  'ogeEditorMarkdownOnSpace',
  'ogeEditorMarkdownOnEnter',
  'ogeEditorActiveState',
  'ogeEditorCharacterCount',
  'ogeEditorWordCount',
  'ogeEditorHtmlLength',
  'ogeEditorToHtml',
  'ogeEditorFromHtml',
  'ogeEditorFromText',
  'ogeSanitizeEditorHtml',
  'ogeEditorSafeHref',
  'ogeEditorSafeImageSrc',
  'ogeEditorSafeColor',
  'renderOgeEditorDom',
  'ogeEditorPointFromDom',
  'ogeEditorPointToDom',
  'OGE_EDITOR_TRUSTED_TYPES_POLICY',
  'OGE_DEFAULT_EDITOR_MESSAGES',
  'OGE_DEFAULT_EDITOR_CONFIG',
  'resolveOgeEditorConfig',
  'mergeOgeEditorMessages',
  'OGE_DEFAULT_EDITOR_TOOLBAR',
  'OGE_EDITOR_TOOLS',
  'buildOgeEditorToolbar',
  'ogeEditorToolbarItems',
  'ogeEditorBlockFormatMenu',
  'ogeEditorBlockFormatCommand',
  'ogeEditorToolCommand',
  'ogeEditorIsMac',
] as const;

describe('the @oge-ui/behavior barrel', () => {
  for (const name of ENTRY_POINTS) {
    it(`exports ${name}`, () => {
      expect(behavior).toHaveProperty(name);
      expect(
        (behavior as unknown as Record<string, unknown>)[name],
      ).toBeDefined();
    });
  }

  it('re-exports the shared engine tables the two layers must agree on', () => {
    expect(behavior.OGE_DEFAULT_OVERLAY_TIMINGS.menuHideDelayMs).toBe(300);
    expect(behavior.OGE_SELECT_OPTION_HEIGHT).toEqual({
      sm: 28,
      md: 34,
      lg: 40,
    });
    expect(behavior.OGE_DEFAULT_COLOR_PALETTE.length).toBe(50);
  });
});
