const { withNx } = require('@nx/rollup/with-nx');

module.exports = withNx(
  {
    main: './src/index.ts',
    // Optional-peer entry point: the pure `.xlsx` builder shared by both
    // Kanban render layers, separate so only an app importing it pulls in
    // `exceljs` (workspace-relative; the file name becomes the entry name)
    additionalEntryPoints: ['packages/kanban-engine/src/export-excel.ts'],
    outputPath: '../../dist/packages/kanban-engine',
    tsConfig: './tsconfig.lib.json',
    compiler: 'swc',
    format: ['cjs', 'esm'],
    // note: '{projectRoot}' tokens are not interpolated inside rollup.config —
    // the path must be spelled out relative to the workspace root
    assets: [
      { input: 'packages/kanban-engine', output: '.', glob: '*.md' },
      // the commercial license travels with the engine (ADR 0003)
      { input: 'packages/kanban-engine', output: '.', glob: 'LICENSE' },
      // machine-readable API reference for coding assistants — generated by
      // `nx run docs-tools:llms`, read from node_modules/@oge-ui/kanban-engine/llms.txt
      { input: 'packages/kanban-engine', output: '.', glob: 'llms.txt' },
    ],
  },
  {},
);
