const { withNx } = require('@nx/rollup/with-nx');

module.exports = withNx(
  {
    main: './src/index.ts',
    outputPath: '../../dist/packages/core',
    tsConfig: './tsconfig.lib.json',
    compiler: 'swc',
    format: ['cjs', 'esm'],
    // note: '{projectRoot}' tokens are not interpolated inside rollup.config —
    // the path must be spelled out relative to the workspace root
    assets: [
      { input: 'packages/core', output: '.', glob: '*.md' },
      { input: 'packages/core', output: '.', glob: 'LICENSE' },
      // machine-readable API reference for coding assistants — generated by
      // `nx run docs-tools:llms`, read from node_modules/@oge-ui/core/llms.txt
      { input: 'packages/core', output: '.', glob: 'llms.txt' },
      // the suite's theme stylesheets (dark, bootstrap, tailwind). Their
      // source sits next to the token mixin in grid; core ships them because
      // every Angular and React package depends on core, so a React-only app
      // never has to install the Angular grid to get a dark theme
      {
        input: 'packages/grid/src/lib/styles/themes',
        output: 'themes',
        glob: '*.css',
      },
    ],
  },
  {
    // Provide additional rollup configuration here. See: https://rollupjs.org/configuration-options
    // e.g.
    // output: { sourcemap: true },
  },
);
