export { OgeEditor } from './lib/editor/editor';
export { ogeEditorMaxLength } from './lib/editor-validators';
export {
  OGE_EDITOR_CONFIG,
  provideOgeEditorConfig,
  OGE_DEFAULT_EDITOR_CONFIG,
  OGE_DEFAULT_EDITOR_MESSAGES,
  type OgeEditorAnnouncementMessages,
  type OgeEditorBlockMessages,
  type OgeEditorColorMessages,
  type OgeEditorConfig,
  type OgeEditorConfigInput,
  type OgeEditorCounterMessages,
  type OgeEditorDialogMessages,
  type OgeEditorKeyMessages,
  type OgeEditorMessages,
  type OgeEditorMessagesInput,
  type OgeEditorToolMessages,
  type OgeEditorValidationMessages,
} from './lib/config';
// The document model, the sanitizer and the command vocabulary are
// framework-free and shared with the React editor through
// `@oge-ui/behavior`; re-exported so the Angular package is one import path.
export {
  OGE_DEFAULT_EDITOR_TOOLBAR,
  OGE_EDITOR_TRUSTED_TYPES_POLICY,
  ogeSanitizeEditorHtml,
  ogeEditorHtmlLength,
  ogeEditorCommandFromName,
  type OgeEditorActiveState,
  type OgeEditorAlign,
  type OgeEditorBlockFormatValue,
  type OgeEditorCommand,
  type OgeEditorCommandExecutedEvent,
  type OgeEditorCommandName,
  type OgeEditorCounterMode,
  type OgeEditorCustomTool,
  type OgeEditorDialogKind,
  type OgeEditorDialogOpeningEvent,
  type OgeEditorDirection,
  type OgeEditorFocusEvent,
  type OgeEditorHeadingLevel,
  type OgeEditorLink,
  type OgeEditorListKind,
  type OgeEditorMarkName,
  type OgeEditorParseOptions,
  type OgeEditorPasteMode,
  type OgeEditorPastingEvent,
  type OgeEditorSelectionChangedEvent,
  type OgeEditorToolClickEvent,
  type OgeEditorToolContext,
  type OgeEditorToolName,
  type OgeEditorToolbarEntry,
  type OgeEditorValueCommittedEvent,
} from '@oge-ui/behavior';
