import {
  ChangeDetectionStrategy,
  Component,
  DOCUMENT,
  DestroyRef,
  afterNextRender,
  computed,
  effect,
  inject,
  signal,
} from '@angular/core';
import { Location } from '@angular/common';
import { RouterLink } from '@angular/router';
import { OgeButton } from '@oge-ui/buttons';
import { OgeColumn, OgeGrid } from '@oge-ui/grid';
import { OgeColorBox } from '@oge-ui/inputs/color-box';
import { OgeDateBox } from '@oge-ui/inputs/date-box';
import { OgeSelectBox } from '@oge-ui/inputs/select-box';
import { OgeToastService } from '@oge-ui/overlay';
import { OgeTab, OgeTabPanel } from '@oge-ui/tabs';
import { CodeBlock } from '../../shared/code-block';
import { DocHeader } from '../../shared/doc-header';
import { FrameworkService } from '../../shared/framework.service';
import { PageToc } from '../../shared/page-toc';
// Generated by `docs-tools:llms` from _tokens.scss and themes/*.css.
import presetFile from './generated/theme-presets.json';
import {
  FONT_STACKS,
  INITIAL_STATE,
  KEY_COLORS,
  RADIUS_MAX,
  contrastChecks,
  decodeState,
  encodeState,
  exportJson,
  exportRootCss,
  exportScopedCss,
  keyColorValue,
  presetOf,
  pxOf,
  resolveTokens,
  themeSlug,
  type BuilderState,
  type Density,
  type PresetFile,
  type PresetId,
} from './theme-builder-model';
import { EXPORT_SCOPE, EXPORT_USAGE } from './theme-builder-snippets';

const PRESETS = presetFile as unknown as PresetFile;
const STORAGE_KEY = 'oge-docs-theme-builder';
const QUERY_KEY = 'theme';
/** The preview subtree — and the toast host, which renders into `<body>`. */
const PREVIEW_SELECTOR = '.app-theme-preview, oge-toast-host';

type ExportFormat = 'root' | 'scoped' | 'json';

interface OrderRow {
  readonly id: number;
  readonly customer: string;
  readonly status: string;
  readonly total: number;
}

const ORDERS: readonly OrderRow[] = [
  { id: 1041, customer: 'Northwind Traders', status: 'Shipped', total: 1280 },
  { id: 1042, customer: 'Contoso Ltd', status: 'Pending', total: 432.5 },
  { id: 1043, customer: 'Fabrikam Inc', status: 'Delivered', total: 2210 },
  { id: 1044, customer: 'Tailspin Toys', status: 'Cancelled', total: 98 },
  { id: 1045, customer: 'Adventure Works', status: 'Shipped', total: 760.25 },
];

/**
 * `/getting-started/theme-builder` — edit the key tokens on top of a built-in
 * theme, watch real OGE components follow, check WCAG contrast and export
 * the result as CSS (`:root` or a scoped theme) or DTCG JSON.
 *
 * The preview is themed by one constructed stylesheet (CSSOM —
 * `adoptedStyleSheets`, no `<style>` element, so it holds under the strict
 * CSP run) whose rule sets every token on the preview subtree and the toast
 * host. State lives in the URL (`?theme=`, shareable) and localStorage.
 */
@Component({
  selector: 'app-getting-started-theme-builder',
  imports: [
    CodeBlock,
    DocHeader,
    OgeButton,
    OgeColorBox,
    OgeColumn,
    OgeDateBox,
    OgeGrid,
    OgeSelectBox,
    OgeTab,
    OgeTabPanel,
    PageToc,
    RouterLink,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <app-doc-header
      title="Theme builder"
      category="Getting Started"
      categoryLink="/getting-started"
      [chips]="['live preview', 'WCAG contrast', 'CSS + JSON export']"
    >
      <p>
        Start from a built-in theme, change the key tokens and watch real OGE
        components follow. The builder checks text contrast as you go and
        exports plain CSS custom properties — no build step, no theme API. Every
        token it writes is in the
        <a
          routerLink="/getting-started/tokens"
          class="text-indigo-600 underline dark:text-indigo-400"
          >token reference</a
        >.
      </p>
    </app-doc-header>
    <app-page-toc [sections]="sections" />

    @if (framework.framework() === 'react') {
      <p class="app-shared-note" data-testid="react-note">
        <strong>Same tokens in React.</strong> The preview renders the Angular
        components; the React components draw the same
        <code>.oge-*</code> classes from the same stylesheet, so a theme
        exported here styles both render layers identically.
      </p>
    }

    <h2 id="tokens" class="scroll-mt-20">Tokens</h2>
    <div class="mb-4 flex flex-wrap items-center gap-3">
      <span class="text-[13px] font-medium text-gray-700 dark:text-gray-300"
        >Start from</span
      >
      <div
        class="flex flex-wrap gap-1 rounded-lg border border-gray-200 p-0.5 dark:border-gray-700"
        role="group"
        aria-label="Start from a preset"
      >
        @for (preset of presets; track preset.id) {
          <button
            type="button"
            class="rounded-md px-2.5 py-1 text-[13px] font-medium transition-colors"
            [class]="
              state().preset === preset.id
                ? 'bg-gray-900 text-white dark:bg-gray-100 dark:text-gray-900'
                : 'text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-gray-100'
            "
            [attr.aria-pressed]="state().preset === preset.id"
            (click)="choosePreset(preset.id)"
          >
            {{ preset.label }}
          </button>
        }
      </div>
      <button
        type="button"
        class="text-[13px] text-indigo-600 underline disabled:text-gray-400 disabled:no-underline dark:text-indigo-400"
        [disabled]="!edited()"
        (click)="resetEdits()"
      >
        Reset edits
      </button>
    </div>

    <div class="app-theme-controls">
      @for (color of keyColors; track color.token) {
        <oge-color-box
          [label]="color.label"
          [hint]="color.hint"
          view="both"
          [fluid]="true"
          [value]="colorValue(color.token)"
          (valueChange)="setColor(color.token, $event)"
        />
      }
    </div>

    <div class="mt-4 grid gap-4 sm:grid-cols-3">
      <label class="flex flex-col gap-1 text-[13px]">
        <span class="font-medium text-gray-700 dark:text-gray-300"
          >Radius · {{ radiusValue() }}px</span
        >
        <input
          type="range"
          min="0"
          [max]="radiusMax"
          step="1"
          class="accent-indigo-600"
          [value]="radiusValue()"
          (input)="setRadius($any($event.target).valueAsNumber)"
        />
      </label>
      <div class="flex flex-col gap-1 text-[13px]">
        <span
          id="app-theme-density"
          class="font-medium text-gray-700 dark:text-gray-300"
          >Density</span
        >
        <div
          class="flex w-fit gap-1 rounded-lg border border-gray-200 p-0.5 dark:border-gray-700"
          role="group"
          aria-labelledby="app-theme-density"
        >
          @for (option of densities; track option.id) {
            <button
              type="button"
              class="rounded-md px-2.5 py-1 text-[13px] font-medium transition-colors"
              [class]="
                state().density === option.id
                  ? 'bg-gray-900 text-white dark:bg-gray-100 dark:text-gray-900'
                  : 'text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-gray-100'
              "
              [attr.aria-pressed]="state().density === option.id"
              (click)="patch({ density: option.id })"
            >
              {{ option.label }}
            </button>
          }
        </div>
      </div>
      <label class="flex flex-col gap-1 text-[13px]">
        <span class="font-medium text-gray-700 dark:text-gray-300"
          >Font family</span
        >
        <select
          class="app-theme-select"
          [value]="state().font"
          (change)="patch({ font: $any($event.target).value })"
        >
          @for (stack of fonts; track stack.id) {
            <option [value]="stack.id" [selected]="stack.id === state().font">
              {{ stack.label }}
            </option>
          }
        </select>
      </label>
    </div>

    <h2 id="preview" class="scroll-mt-20">Preview</h2>
    <div
      class="app-theme-preview"
      role="region"
      aria-label="Theme preview"
      data-testid="theme-preview"
    >
      <div class="flex flex-wrap items-center gap-2">
        <oge-button text="Save" severity="accent" stylingMode="contained" />
        <oge-button text="Cancel" stylingMode="outlined" />
        <oge-button text="Details" stylingMode="text" />
        <oge-button text="Approve" severity="success" stylingMode="contained" />
        <oge-button text="Review" severity="warning" stylingMode="contained" />
        <oge-button text="Delete" severity="danger" stylingMode="contained" />
      </div>
      <div class="mt-4 grid gap-4 sm:grid-cols-2">
        <oge-select-box
          label="Status"
          [items]="statuses"
          [fluid]="true"
          [(value)]="status"
        />
        <oge-date-box label="Ship date" [fluid]="true" [(value)]="shipDate" />
      </div>
      <oge-tab-panel class="mt-4 block" ariaLabel="Preview sections">
        <oge-tab text="Orders" key="orders">
          <div class="pt-3">
            <oge-grid [data]="orders" keyField="id">
              <oge-column field="id" caption="Order" [width]="90" />
              <oge-column field="customer" caption="Customer" />
              <oge-column field="status" caption="Status" [width]="120" />
              <oge-column
                field="total"
                caption="Total"
                dataType="number"
                [width]="110"
              />
            </oge-grid>
          </div>
        </oge-tab>
        <oge-tab text="Notifications" key="notifications">
          <div class="flex flex-wrap gap-2 pt-3">
            <oge-button
              text="Show success toast"
              stylingMode="outlined"
              (clicked)="toast('success')"
            />
            <oge-button
              text="Show error toast"
              stylingMode="outlined"
              (clicked)="toast('error')"
            />
          </div>
        </oge-tab>
      </oge-tab-panel>
    </div>

    <h2 id="contrast" class="scroll-mt-20">Contrast</h2>
    @if (failures().length) {
      <p class="app-theme-warning" role="status" data-testid="contrast-warning">
        {{ failures().length }}
        {{ failures().length === 1 ? 'pair fails' : 'pairs fail' }} WCAG AA:
        {{ failureLabels() }}.
      </p>
    } @else {
      <p class="app-theme-ok" role="status">
        Every checked pair meets WCAG AA.
      </p>
    }
    <ul class="app-theme-checks" aria-label="Contrast checks">
      @for (check of checks(); track check.id) {
        <li [attr.data-check]="check.id">
          <span class="app-theme-pair" aria-hidden="true"
            ><span [style.background]="check.bg" [style.color]="check.fg"
              >Aa</span
            ></span
          >
          <span class="min-w-0 flex-1">{{ check.label }}</span>
          <span class="tabular-nums">{{
            check.ratio === null ? 'n/a' : check.ratio.toFixed(2) + ':1'
          }}</span>
          <span
            class="app-theme-badge"
            [class.app-theme-badge-fail]="!check.pass"
            >{{ check.pass ? 'AA' : 'Fails AA · ' + check.min + ':1' }}</span
          >
        </li>
      }
    </ul>

    <h2 id="export" class="scroll-mt-20">Export</h2>
    <div class="mb-3 flex flex-wrap items-end gap-3">
      <div
        class="flex gap-1 rounded-lg border border-gray-200 p-0.5 dark:border-gray-700"
        role="group"
        aria-label="Export format"
      >
        @for (option of formats; track option.id) {
          <button
            type="button"
            class="rounded-md px-2.5 py-1 text-[13px] font-medium transition-colors"
            [class]="
              format() === option.id
                ? 'bg-gray-900 text-white dark:bg-gray-100 dark:text-gray-900'
                : 'text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-gray-100'
            "
            [attr.aria-pressed]="format() === option.id"
            (click)="format.set(option.id)"
          >
            {{ option.label }}
          </button>
        }
      </div>
      <label class="flex flex-col gap-1 text-[13px]">
        <span class="font-medium text-gray-700 dark:text-gray-300"
          >Theme name</span
        >
        <input
          type="text"
          class="app-theme-select"
          autocomplete="off"
          spellcheck="false"
          [value]="themeName()"
          (input)="themeName.set($any($event.target).value)"
        />
      </label>
      <button type="button" class="app-theme-action" (click)="download()">
        Download {{ format() === 'json' ? '.json' : '.css' }}
      </button>
      <button type="button" class="app-theme-action" (click)="copyLink()">
        {{ linkCopied() ? 'Link copied' : 'Copy share link' }}
      </button>
    </div>
    <div data-testid="theme-export">
      <app-code-block
        [code]="exported()"
        [language]="format() === 'json' ? 'json' : 'css'"
        [title]="fileName()"
      />
    </div>
    <p>
      Load the file after the OGE stylesheets. The <code>:root</code> export is
      self-contained — start from Dark and it needs no <code>dark.css</code>.
      The scoped export re-declares the derived tints, so it themes any subtree
      it is applied to:
    </p>
    <app-code-block [code]="usage" language="css" title="styles.css" />
    <app-code-block [code]="scopeUsage" language="html" title="index.html" />
  `,
  styles: `
    .app-theme-controls {
      display: grid;
      gap: 0.75rem 1rem;
      grid-template-columns: repeat(auto-fill, minmax(13rem, 1fr));
    }
    .app-theme-select {
      padding: 0.4rem 0.6rem;
      border: 1px solid rgb(209 213 219);
      border-radius: 0.5rem;
      background: transparent;
      font-size: 14px;
    }
    .app-theme-select:focus-visible,
    .app-theme-action:focus-visible {
      outline: 2px solid rgb(99 102 241);
      outline-offset: 1px;
    }
    .app-theme-action {
      padding: 0.4rem 0.75rem;
      border: 1px solid rgb(209 213 219);
      border-radius: 0.5rem;
      font-size: 13px;
      font-weight: 500;
    }
    .app-theme-action:hover {
      background: rgb(243 244 246);
    }
    .app-theme-preview {
      padding: 1rem;
      border: 1px solid var(--oge-border-color);
      border-radius: var(--oge-radius-lg);
      background: var(--oge-bg);
      color: var(--oge-text-color);
      font-size: var(--oge-font-size);
    }
    .app-theme-warning,
    .app-theme-ok {
      padding: 0.5rem 0.75rem;
      border-radius: 0.5rem;
      font-size: 14px;
    }
    .app-theme-warning {
      background: rgb(254 243 199);
      color: rgb(120 53 15);
    }
    .app-theme-ok {
      background: rgb(220 252 231);
      color: rgb(20 83 45);
    }
    .app-theme-checks {
      margin: 0.75rem 0 0;
      padding: 0;
      list-style: none;
    }
    .app-theme-checks li {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      margin: 0;
      padding: 0.4rem 0;
      border-bottom: 1px solid var(--app-theme-rule, rgb(243 244 246));
      font-size: 14px;
    }
    .app-theme-pair {
      flex: none;
      border-radius: 0.375rem;
      border: 1px solid rgb(0 0 0 / 0.12);
      overflow: hidden;
      background: #fff;
    }
    .app-theme-pair > span {
      display: block;
      padding: 0.1rem 0.45rem;
      font-weight: 600;
    }
    .app-theme-badge {
      flex: none;
      padding: 0.05rem 0.5rem;
      border-radius: 999px;
      background: rgb(220 252 231);
      color: rgb(21 128 61);
      font-size: 12px;
      font-weight: 600;
    }
    .app-theme-badge-fail {
      background: rgb(254 226 226);
      color: rgb(153 27 27);
    }
    :host-context(.dark) .app-theme-select,
    :host-context(.dark) .app-theme-action {
      border-color: rgb(75 85 99);
    }
    :host-context(.dark) .app-theme-action:hover {
      background: rgb(31 41 55);
    }
    :host-context(.dark) .app-theme-checks {
      --app-theme-rule: rgb(31 41 55);
    }
    :host-context(.dark) .app-theme-warning {
      background: rgb(245 158 11 / 0.16);
      color: rgb(253 230 138);
    }
    :host-context(.dark) .app-theme-ok {
      background: rgb(34 197 94 / 0.16);
      color: rgb(187 247 208);
    }
    :host-context(.dark) .app-theme-badge {
      background: rgb(34 197 94 / 0.16);
      color: rgb(134 239 172);
    }
    :host-context(.dark) .app-theme-badge-fail {
      background: rgb(239 68 68 / 0.18);
      color: rgb(254 202 202);
    }
  `,
})
export class GettingStartedThemeBuilderPage {
  private readonly document = inject(DOCUMENT);
  private readonly location = inject(Location);
  private readonly toasts = inject(OgeToastService);
  protected readonly framework = inject(FrameworkService);

  protected readonly sections = ['Tokens', 'Preview', 'Contrast', 'Export'];
  protected readonly presets = PRESETS.presets;
  protected readonly keyColors = KEY_COLORS;
  protected readonly fonts = FONT_STACKS;
  protected readonly radiusMax = RADIUS_MAX;
  protected readonly usage = EXPORT_USAGE;
  protected readonly scopeUsage = EXPORT_SCOPE;
  protected readonly densities: readonly { id: Density; label: string }[] = [
    { id: 'compact', label: 'Compact' },
    { id: 'standard', label: 'Standard' },
    { id: 'comfortable', label: 'Comfortable' },
  ];
  protected readonly formats: readonly { id: ExportFormat; label: string }[] = [
    { id: 'root', label: ':root CSS' },
    { id: 'scoped', label: 'Scoped CSS' },
    { id: 'json', label: 'JSON (DTCG)' },
  ];

  protected readonly orders = ORDERS;
  protected readonly statuses = ['Pending', 'Shipped', 'Delivered'];
  protected readonly status = signal<unknown>('Shipped');
  protected readonly shipDate = signal<Date | null>(new Date(2026, 9, 12));

  protected readonly state = signal<BuilderState>(INITIAL_STATE);
  protected readonly format = signal<ExportFormat>('root');
  protected readonly themeName = signal('my-theme');
  protected readonly linkCopied = signal(false);
  /** Set once the browser has restored state — persistence starts then. */
  private readonly restored = signal(false);

  protected readonly tokens = computed(() =>
    resolveTokens(PRESETS, this.state()),
  );
  protected readonly checks = computed(() => contrastChecks(this.tokens()));
  protected readonly failures = computed(() =>
    this.checks().filter((check) => !check.pass),
  );
  protected readonly failureLabels = computed(() =>
    this.failures()
      .map((check) => check.label.toLowerCase())
      .join(', '),
  );
  protected readonly edited = computed(() => {
    const { colors, radius } = this.state();
    return Object.keys(colors).length > 0 || radius !== null;
  });
  protected readonly radiusValue = computed(
    () =>
      this.state().radius ??
      pxOf(presetOf(PRESETS, this.state().preset).tokens['--oge-radius']) ??
      6,
  );
  protected readonly fileName = computed(
    () =>
      `${themeSlug(this.themeName())}.${this.format() === 'json' ? 'json' : 'css'}`,
  );
  protected readonly exported = computed(() => {
    const state = this.state();
    const name = this.themeName();
    switch (this.format()) {
      case 'scoped':
        return exportScopedCss(PRESETS, state, name);
      case 'json':
        return exportJson(PRESETS, state, name);
      default:
        return exportRootCss(PRESETS, state, name);
    }
  });

  private sheet: CSSStyleSheet | null = null;
  private rule: CSSStyleRule | null = null;

  constructor() {
    afterNextRender(() => {
      this.state.set(this.readInitialState());
      this.mountSheet();
      this.restored.set(true);
    });

    effect(() => {
      const tokens = this.tokens();
      const state = this.state();
      if (!this.restored()) return;
      this.applyPreview(tokens, state);
      this.persist(state);
    });

    inject(DestroyRef).onDestroy(() => this.unmountSheet());
  }

  protected colorValue(token: string): string {
    return keyColorValue(PRESETS, this.state(), token);
  }

  protected setColor(token: string, value: string | null): void {
    const current = this.state();
    const colors = { ...current.colors };
    if (value) colors[token] = value.toLowerCase();
    else delete colors[token];
    this.state.set({ ...current, colors });
  }

  protected setRadius(value: number): void {
    if (Number.isNaN(value)) return;
    this.patch({
      radius: Math.max(0, Math.min(RADIUS_MAX, Math.round(value))),
    });
  }

  protected patch(change: Partial<BuilderState>): void {
    this.state.update((current) => ({ ...current, ...change }));
  }

  /** A new preset discards colour and radius edits; density and font stay. */
  protected choosePreset(preset: PresetId): void {
    this.state.update((current) => ({
      ...current,
      preset,
      colors: {},
      radius: null,
    }));
  }

  protected resetEdits(): void {
    this.patch({ colors: {}, radius: null });
  }

  protected toast(severity: 'success' | 'error'): void {
    this.toasts.show({
      severity,
      message:
        severity === 'success'
          ? 'Order 1045 shipped'
          : 'Could not reach the server',
    });
  }

  protected download(): void {
    const view = this.document.defaultView;
    if (!view) return;
    const json = this.format() === 'json';
    const blob = new Blob([this.exported()], {
      type: json ? 'application/json' : 'text/css',
    });
    const url = view.URL.createObjectURL(blob);
    const link = this.document.createElement('a');
    link.href = url;
    link.download = this.fileName();
    this.document.body.appendChild(link);
    link.click();
    link.remove();
    view.setTimeout(() => view.URL.revokeObjectURL(url), 0);
  }

  protected async copyLink(): Promise<void> {
    try {
      await this.document.defaultView?.navigator.clipboard.writeText(
        this.document.location.href,
      );
      this.linkCopied.set(true);
      this.document.defaultView?.setTimeout(
        () => this.linkCopied.set(false),
        2000,
      );
    } catch {
      // clipboard blocked — the address bar holds the same link
    }
  }

  /** `?theme=` wins (a shared link), then the last session, then defaults. */
  private readInitialState(): BuilderState {
    const query = new URLSearchParams(this.document.location.search);
    const fromUrl = decodeState(query.get(QUERY_KEY));
    if (fromUrl) return fromUrl;
    try {
      return (
        decodeState(
          this.document.defaultView?.localStorage.getItem(STORAGE_KEY),
        ) ?? INITIAL_STATE
      );
    } catch {
      return INITIAL_STATE;
    }
  }

  private persist(state: BuilderState): void {
    const encoded = encodeState(state);
    try {
      const storage = this.document.defaultView?.localStorage;
      if (encoded) storage?.setItem(STORAGE_KEY, encoded);
      else storage?.removeItem(STORAGE_KEY);
    } catch {
      // private browsing — the URL still carries the state
    }
    const [path, search = ''] = this.location.path().split('?');
    const params = new URLSearchParams(search);
    if (encoded) params.set(QUERY_KEY, encoded);
    else params.delete(QUERY_KEY);
    const next = params.toString();
    if (next !== search) this.location.replaceState(path.split('#')[0], next);
  }

  /** One constructed stylesheet; CSSOM writes, so values cannot inject rules. */
  private mountSheet(): void {
    if (
      typeof CSSStyleSheet === 'undefined' ||
      !('adoptedStyleSheets' in this.document)
    ) {
      return;
    }
    const sheet = new CSSStyleSheet();
    sheet.insertRule(`${PREVIEW_SELECTOR} {}`);
    this.sheet = sheet;
    this.rule = sheet.cssRules[0] as CSSStyleRule;
    this.document.adoptedStyleSheets = [
      ...this.document.adoptedStyleSheets,
      sheet,
    ];
  }

  private unmountSheet(): void {
    const sheet = this.sheet;
    if (!sheet) return;
    this.document.adoptedStyleSheets = this.document.adoptedStyleSheets.filter(
      (entry) => entry !== sheet,
    );
    this.sheet = null;
    this.rule = null;
  }

  private applyPreview(
    tokens: Record<string, string>,
    state: BuilderState,
  ): void {
    const style = this.rule?.style;
    if (!style) return;
    style.cssText = '';
    for (const [name, value] of Object.entries(tokens)) {
      style.setProperty(name, value);
    }
    style.setProperty('color-scheme', presetOf(PRESETS, state.preset).scheme);
    const font = FONT_STACKS.find((stack) => stack.id === state.font)?.css;
    if (font) style.setProperty('font-family', font);
  }
}
