import {
  ChangeDetectionStrategy,
  Component,
  DOCUMENT,
  computed,
  effect,
  inject,
  signal,
} from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { motionScrollBehavior } from '@oge-ui/behavior';
import { CodeBlock } from '../../shared/code-block';
import { DocHeader } from '../../shared/doc-header';
import { Icon } from '../../shared/icon';
import { PageToc } from '../../shared/page-toc';
// Generated by `docs-tools:llms` from _tokens.scss and themes/*.css — the
// table can never disagree with the stylesheets (llms-check fails if stale).
import tokenFile from './generated/design-tokens.json';
import {
  filterTokens,
  groupTokens,
  shortPackage,
  tokenAnchor,
  type CategoryFilter,
  type TokenFile,
  type TokenRow,
} from './tokens-data';
import { DTCG_IMPORT, OVERRIDE } from './tokens-snippets';

const DATA = tokenFile as unknown as TokenFile;

/** Packages listed inline; more collapse into a disclosure. */
const INLINE_PACKAGES = 3;

/**
 * `/getting-started/tokens` — every `--oge-*` design token with its default,
 * dark, high-contrast and bridge-theme values, a swatch for colours, its
 * category and the packages that read it. Filterable, each row linkable.
 */
@Component({
  selector: 'app-getting-started-tokens',
  imports: [CodeBlock, DocHeader, Icon, PageToc, RouterLink],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <app-doc-header
      title="Design tokens"
      category="Getting Started"
      categoryLink="/getting-started"
      [chips]="[
        total + ' tokens',
        'light · dark · high contrast',
        'Tailwind & Bootstrap bridges',
        'DTCG tokens.json',
      ]"
    >
      <p>
        Every visual value in OGE UI is a <code>--oge-*</code> CSS custom
        property. This table is generated from the token source and the theme
        stylesheets at build time, so it always matches what ships. Try values
        live in the
        <a
          routerLink="/getting-started/theme-builder"
          class="text-indigo-600 underline dark:text-indigo-400"
          >theme builder</a
        >, or read
        <a
          routerLink="/getting-started/styling"
          class="text-indigo-600 underline dark:text-indigo-400"
          >Style the app</a
        >
        for how to override them.
      </p>
    </app-doc-header>
    <app-page-toc [sections]="sections" />

    <h2 id="all-tokens" class="scroll-mt-20">All tokens</h2>
    <p class="app-shared-note">
      <strong>Identical in Angular and React.</strong> Both render layers draw
      the same <code>.oge-*</code> classes from one stylesheet, so every token
      below themes both.
    </p>
    <div class="mb-3 flex flex-wrap items-end gap-3">
      <label class="flex min-w-[220px] flex-1 flex-col gap-1 text-[13px]">
        <span class="font-medium text-gray-700 dark:text-gray-300"
          >Filter tokens</span
        >
        <input
          type="search"
          class="app-token-search"
          placeholder="Name, value or package — e.g. accent, #fff, kanban"
          autocomplete="off"
          spellcheck="false"
          [value]="query()"
          (input)="query.set($any($event.target).value)"
        />
      </label>
      <div
        class="flex flex-wrap gap-1 rounded-lg border border-gray-200 p-0.5 dark:border-gray-700"
        role="group"
        aria-label="Filter by category"
      >
        @for (option of categoryOptions; track option.id) {
          <button
            type="button"
            class="rounded-md px-2.5 py-1 text-[13px] font-medium transition-colors"
            [class]="
              category() === option.id
                ? 'bg-gray-900 text-white dark:bg-gray-100 dark:text-gray-900'
                : 'text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-gray-100'
            "
            [attr.aria-pressed]="category() === option.id"
            (click)="category.set(option.id)"
          >
            {{ option.label }}
          </button>
        }
      </div>
    </div>
    <p
      class="!my-2 text-[13px] text-gray-600 dark:text-gray-400"
      role="status"
      data-testid="token-count"
    >
      {{ visible().length }} of {{ total }} tokens
      @if (copied(); as name) {
        · copied <code>{{ name }}</code>
      }
    </p>

    @if (groups().length) {
      <div
        class="overflow-x-auto rounded-lg border border-gray-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400/60 dark:border-gray-800"
        tabindex="0"
        role="region"
        aria-labelledby="all-tokens"
      >
        <table class="app-token-table">
          <caption class="sr-only">
            Design tokens grouped by category, with the value in each theme. An
            empty theme cell keeps the default value.
          </caption>
          <thead>
            <tr>
              <th scope="col">Token</th>
              @for (theme of themes; track theme.id) {
                <th scope="col">{{ theme.label }}</th>
              }
              <th scope="col">Used by</th>
            </tr>
          </thead>
          @for (group of groups(); track group.id) {
            <tbody>
              <tr class="app-token-group">
                <th scope="rowgroup" [attr.colspan]="themes.length + 2">
                  {{ group.label }}
                  <span
                    class="ml-2 text-[12px] font-normal text-gray-500 dark:text-gray-400"
                    >{{ group.rows.length }}</span
                  >
                </th>
              </tr>
              @for (row of group.rows; track row.n) {
                <tr [class.app-token-targeted]="targeted() === anchor(row)">
                  <th scope="row" class="app-token-name" [id]="anchor(row)">
                    <span class="flex items-center gap-1">
                      <a
                        class="font-mono text-[12.5px] font-medium text-gray-900 no-underline hover:underline dark:text-gray-100"
                        [href]="'#' + anchor(row)"
                        (click)="jump($event, anchor(row))"
                        >{{ row.n }}</a
                      >
                      <button
                        type="button"
                        class="app-token-copy"
                        [attr.aria-label]="'Copy ' + row.n"
                        (click)="copy(row.n)"
                      >
                        <app-icon
                          [name]="copied() === row.n ? 'check' : 'copy'"
                          [size]="13"
                        />
                      </button>
                      @if (row.k === 'd') {
                        <span
                          class="app-token-derived"
                          title="Computed from other tokens"
                          >derived</span
                        >
                      }
                    </span>
                    @if (row.d) {
                      <span class="app-token-note">{{ row.d }}</span>
                    }
                  </th>
                  @for (theme of themes; track theme.id) {
                    <td>
                      @if (row.v[theme.id]; as value) {
                        <span class="flex items-start gap-1.5">
                          @if (row.s?.[theme.id]; as swatch) {
                            <span class="app-token-chip" aria-hidden="true"
                              ><span [style.background]="swatch"></span
                            ></span>
                          }
                          <code class="app-token-value">{{ value }}</code>
                        </span>
                      } @else {
                        <span
                          class="text-gray-400 dark:text-gray-500"
                          aria-hidden="true"
                          >—</span
                        ><span class="sr-only">{{
                          theme.id === 'light' ? 'not set' : 'same as default'
                        }}</span>
                      }
                    </td>
                  }
                  <td class="app-token-used">
                    @if (row.u.length === 0) {
                      <span class="text-gray-500 dark:text-gray-400"
                        >none yet</span
                      >
                    } @else if (row.u.length <= inlinePackages) {
                      {{ packages(row.u) }}
                    } @else {
                      <details>
                        <summary>{{ row.u.length }} packages</summary>
                        {{ packages(row.u) }}
                      </details>
                    }
                  </td>
                </tr>
              }
            </tbody>
          }
        </table>
      </div>
    } @else {
      <p
        class="rounded-lg border border-dashed border-gray-300 p-4 text-[14px] dark:border-gray-700"
      >
        No token matches “{{ query() }}”.
        <button
          type="button"
          class="text-indigo-600 underline dark:text-indigo-400"
          (click)="reset()"
        >
          Clear the filter
        </button>
      </p>
    }

    <h2 id="reading-the-table" class="scroll-mt-20">Reading the table</h2>
    <ul>
      <li>
        <strong>Default (light)</strong> is the value every page gets, declared
        at zero specificity on <code>:root</code> — any declaration of yours
        wins. <strong>Dark</strong> and <strong>High contrast</strong> apply
        under <code>.oge-theme-dark</code> /
        <code>[data-oge-theme='high-contrast']</code>; the
        <strong>Tailwind</strong> and <strong>Bootstrap</strong> bridges map
        tokens onto those frameworks' variables, falling back to the value in
        parentheses. An empty cell keeps the default.
      </li>
      <li>
        <strong>Derived</strong> tokens are expressions over other tokens (<code
          >color-mix()</code
        >
        tints of <code>--oge-accent</code>, aliases like
        <code>--oge-input-muted</code>). Set the base token and they follow;
        swatches show them resolved in each theme.
      </li>
      <li>
        <strong>Used by</strong> lists the packages whose stylesheets read the
        token. React packages ship the same stylesheets as their Angular
        siblings, so a token used by <code>grid</code> themes
        <code>&#64;oge-ui/react-grid</code> too.
      </li>
      <li>
        Component-local knobs (<code>--oge-card-pad</code>,
        <code>--oge-input-width</code>…) are set on a component's own class and
        documented on its page; they are not part of this shared set.
      </li>
    </ul>
    <app-code-block [code]="override" language="css" />

    <h2 id="dtcg-tokens-json" class="scroll-mt-20">DTCG tokens.json</h2>
    <p>
      The light, dark and high-contrast themes also ship as a
      <a
        href="https://www.designtokens.org/tr/2025.10/format/"
        class="text-indigo-600 underline dark:text-indigo-400"
        target="_blank"
        rel="noopener"
        >Design Tokens Community Group</a
      >
      file — <code>&#64;oge-ui/core/tokens.json</code> — for design tools and
      token pipelines that read the format. Colours are sRGB component objects
      with a <code>hex</code> fallback, dimensions are
      <code>{{ '{' }} value, unit {{ '}' }}</code
      >, aliases stay aliases and computed tints carry their CSS expression in
      <code>$extensions</code>.
      <a
        href="/tokens.json"
        download="oge-tokens.json"
        class="text-indigo-600 underline dark:text-indigo-400"
        >Download tokens.json</a
      >.
    </p>
    <app-code-block [code]="dtcgImport" language="typescript" />
  `,
  styles: `
    .app-token-search {
      width: 100%;
      padding: 0.45rem 0.7rem;
      border: 1px solid rgb(209 213 219);
      border-radius: 0.5rem;
      background: transparent;
      font-size: 14px;
    }
    .app-token-search:focus-visible {
      outline: 2px solid rgb(99 102 241);
      outline-offset: 1px;
    }
    .app-token-table {
      width: 100%;
      margin: 0;
      border-collapse: collapse;
      font-size: 13px;
    }
    .app-token-table th,
    .app-token-table td {
      padding: 0.45rem 0.7rem;
      border-bottom: 1px solid var(--app-token-rule, rgb(243 244 246));
      text-align: left;
      vertical-align: top;
      font-weight: 400;
    }
    .app-token-table thead th {
      background: var(--app-token-head, rgb(249 250 251));
      font-size: 12px;
      font-weight: 600;
      white-space: nowrap;
    }
    .app-token-group th {
      padding-top: 0.8rem;
      font-weight: 600;
      background: var(--app-token-group-bg, rgb(249 250 251 / 0.6));
    }
    .app-token-name {
      min-width: 15rem;
      max-width: 19rem;
    }
    .app-token-targeted > * {
      background: var(--app-token-target, rgb(238 242 255));
    }
    .app-token-note {
      display: block;
      margin-top: 0.2rem;
      color: rgb(107 114 128);
      font-size: 12px;
      line-height: 1.35;
    }
    .app-token-value {
      font-size: 12px;
      white-space: normal;
      overflow-wrap: anywhere;
      min-width: 7rem;
      display: inline-block;
    }
    .app-token-chip {
      flex: none;
      width: 1rem;
      height: 1rem;
      margin-top: 0.1rem;
      border-radius: 0.25rem;
      border: 1px solid rgb(0 0 0 / 0.15);
      overflow: hidden;
      background: repeating-conic-gradient(#d1d5db 0 25%, #fff 0 50%) 0 0 / 8px
        8px;
    }
    .app-token-chip > span {
      display: block;
      width: 100%;
      height: 100%;
    }
    .app-token-copy {
      display: inline-flex;
      padding: 0.2rem;
      border-radius: 0.25rem;
      color: rgb(107 114 128);
    }
    .app-token-copy:hover {
      color: rgb(17 24 39);
      background: rgb(243 244 246);
    }
    .app-token-copy:focus-visible {
      outline: 2px solid rgb(99 102 241);
      outline-offset: 1px;
    }
    .app-token-derived {
      padding: 0 0.4rem;
      border-radius: 999px;
      background: rgb(224 231 255);
      color: rgb(55 48 163);
      font-size: 10.5px;
      font-weight: 600;
    }
    .app-token-used {
      min-width: 9rem;
      font-size: 12px;
    }
    .app-token-used summary {
      cursor: pointer;
    }
    :host-context(.dark) .app-token-table {
      --app-token-rule: rgb(31 41 55);
      --app-token-head: rgb(17 24 39);
      --app-token-group-bg: rgb(17 24 39 / 0.6);
      --app-token-target: rgb(49 46 129 / 0.45);
    }
    :host-context(.dark) .app-token-search {
      border-color: rgb(75 85 99);
    }
    :host-context(.dark) .app-token-note {
      color: rgb(156 163 175);
    }
    :host-context(.dark) .app-token-copy {
      color: rgb(156 163 175);
    }
    :host-context(.dark) .app-token-copy:hover {
      color: rgb(243 244 246);
      background: rgb(31 41 55);
    }
    :host-context(.dark) .app-token-derived {
      background: rgb(99 102 241 / 0.2);
      color: rgb(199 210 254);
    }
  `,
})
export class GettingStartedTokensPage {
  private readonly document = inject(DOCUMENT);
  private readonly fragment = toSignal(inject(ActivatedRoute).fragment);

  protected readonly sections = [
    'All tokens',
    'Reading the table',
    'DTCG tokens.json',
  ];
  protected readonly themes = DATA.themes;
  protected readonly total = DATA.tokens.length;
  protected readonly inlinePackages = INLINE_PACKAGES;
  protected readonly override = OVERRIDE;
  protected readonly dtcgImport = DTCG_IMPORT;
  protected readonly categoryOptions: readonly {
    id: CategoryFilter;
    label: string;
  }[] = [{ id: 'all', label: 'All' }, ...DATA.categories];

  protected readonly query = signal('');
  protected readonly category = signal<CategoryFilter>('all');
  /** The row a link or the URL points at, highlighted. */
  protected readonly targeted = signal<string | null>(null);
  /** The token name last copied, for the status line. */
  protected readonly copied = signal<string | null>(null);

  protected readonly visible = computed(() =>
    filterTokens(DATA.tokens, this.query(), this.category()),
  );
  protected readonly groups = computed(() =>
    groupTokens(this.visible(), DATA.categories),
  );

  /**
   * A deep link (`#oge-accent`, a search pick) to a row the filter hides
   * clears the filter so the row renders and the router can scroll to it.
   */
  private readonly followFragment = effect(() => {
    const id = this.fragment();
    if (!id) return;
    const row = DATA.tokens.find((token) => tokenAnchor(token.n) === id);
    if (!row) return;
    this.targeted.set(id);
    if (!this.visible().includes(row)) this.reset();
  });

  protected anchor(row: TokenRow): string {
    return tokenAnchor(row.n);
  }

  protected packages(names: readonly string[]): string {
    return names.map(shortPackage).join(', ');
  }

  protected reset(): void {
    this.query.set('');
    this.category.set('all');
  }

  /**
   * Fragment hrefs resolve against `<base href="/">` and would route away —
   * scroll in place and update only the hash, keeping the query string.
   */
  protected jump(event: Event, id: string): void {
    event.preventDefault();
    this.targeted.set(id);
    this.document
      .getElementById(id)
      ?.scrollIntoView({ behavior: motionScrollBehavior(), block: 'center' });
    const { pathname, search } = this.document.location;
    this.document.defaultView?.history.replaceState(
      null,
      '',
      `${pathname}${search}#${id}`,
    );
  }

  protected async copy(name: string): Promise<void> {
    try {
      await this.document.defaultView?.navigator.clipboard.writeText(name);
      this.copied.set(name);
    } catch {
      // clipboard blocked (permissions, insecure context) — nothing to undo
    }
  }
}
