export {
  OgeEditor,
  type OgeEditorProps,
  type OgeEditorHandle,
} from './lib/editor';
export {
  OgeEditorConfigProvider,
  useOgeEditorConfig,
  type OgeEditorConfig,
  type OgeEditorConfigInput,
  type OgeEditorMessages,
  type OgeEditorMessagesInput,
  type OgeEditorToolMessages,
  type OgeEditorBlockMessages,
  type OgeEditorDialogMessages,
  type OgeEditorColorMessages,
  type OgeEditorCounterMessages,
  type OgeEditorAnnouncementMessages,
  type OgeEditorValidationMessages,
  type OgeEditorKeyMessages,
} from './lib/editor-config';
// The document model, the sanitizer and the command vocabulary are shared
// with the Angular editor through `@oge-ui/behavior`; re-exported so React
// consumers import one package — the same surface the Angular barrel exposes.
export {
  OGE_DEFAULT_EDITOR_CONFIG,
  OGE_DEFAULT_EDITOR_MESSAGES,
  OGE_DEFAULT_EDITOR_TOOLBAR,
  OGE_EDITOR_TRUSTED_TYPES_POLICY,
  ogeSanitizeEditorHtml,
  ogeEditorHtmlLength,
  ogeEditorCommandFromName,
  type OgeEditorActiveState,
  type OgeEditorAlign,
  type OgeEditorBlockFormatValue,
  type OgeEditorCommand,
  type OgeEditorCommandExecutedEvent,
  type OgeEditorCommandName,
  type OgeEditorCounterMode,
  type OgeEditorCustomTool,
  type OgeEditorDialogKind,
  type OgeEditorDialogOpeningEvent,
  type OgeEditorDirection,
  type OgeEditorFocusEvent,
  type OgeEditorHeadingLevel,
  type OgeEditorLink,
  type OgeEditorListKind,
  type OgeEditorMarkName,
  type OgeEditorParseOptions,
  type OgeEditorPasteMode,
  type OgeEditorPastingEvent,
  type OgeEditorSelectionChangedEvent,
  type OgeEditorToolClickEvent,
  type OgeEditorToolContext,
  type OgeEditorToolName,
  type OgeEditorToolbarEntry,
  type OgeEditorValueCommittedEvent,
} from '@oge-ui/behavior';
