const { withNx } = require('@nx/rollup/with-nx');

module.exports = withNx(
  {
    main: './src/index.ts',
    // `@oge-ui/bpmn-engine/testing`: BPMN sample documents for tests, kept out
    // of the main entry so no app bundle carries them.
    // note: workspace-relative, and the file name becomes the entry name
    additionalEntryPoints: ['packages/bpmn-engine/src/testing.ts'],
    outputPath: '../../dist/packages/bpmn-engine',
    tsConfig: './tsconfig.lib.json',
    compiler: 'swc',
    format: ['cjs', 'esm'],
    // note: '{projectRoot}' tokens are not interpolated inside rollup.config —
    // the path must be spelled out relative to the workspace root
    assets: [
      { input: 'packages/bpmn-engine', output: '.', glob: '*.md' },
      { input: 'packages/bpmn-engine', output: '.', glob: 'LICENSE' },
      // machine-readable reference for coding assistants — generated by
      // `nx run docs-tools:llms`
      { input: 'packages/bpmn-engine', output: '.', glob: 'llms.txt' },
    ],
  },
  {},
);
