const { withNx } = require('@nx/rollup/with-nx');

module.exports = withNx(
  {
    main: './src/index.ts',
    // Secondary entry points: the dependency-free iCalendar codec and the
    // optional-peer `.xlsx` / `.pdf` list builders, so `exceljs` and `jspdf`
    // load only in an app that imports one of them. Workspace-relative; each
    // file name becomes the entry name.
    additionalEntryPoints: [
      'packages/scheduler-engine/src/export-ical.ts',
      'packages/scheduler-engine/src/export-excel.ts',
      'packages/scheduler-engine/src/export-pdf.ts',
    ],
    outputPath: '../../dist/packages/scheduler-engine',
    tsConfig: './tsconfig.lib.json',
    compiler: 'swc',
    format: ['cjs', 'esm'],
    // note: '{projectRoot}' tokens are not interpolated inside rollup.config —
    // the path must be spelled out relative to the workspace root
    assets: [
      { input: 'packages/scheduler-engine', output: '.', glob: '*.md' },
      { input: 'packages/scheduler-engine', output: '.', glob: 'LICENSE' },
      // machine-readable API reference for coding assistants — generated by
      // `nx run docs-tools:llms`, read from
      // node_modules/@oge-ui/scheduler-engine/llms.txt
      { input: 'packages/scheduler-engine', output: '.', glob: 'llms.txt' },
    ],
  },
  {},
);
