const { withNx } = require('@nx/rollup/with-nx');

module.exports = withNx(
  {
    main: './src/index.ts',
    outputPath: '../../dist/packages/scheduler-engine',
    tsConfig: './tsconfig.lib.json',
    compiler: 'swc',
    format: ['cjs', 'esm'],
    // note: '{projectRoot}' tokens are not interpolated inside rollup.config —
    // the path must be spelled out relative to the workspace root
    assets: [
      { input: 'packages/scheduler-engine', output: '.', glob: '*.md' },
      { input: 'packages/scheduler-engine', output: '.', glob: 'LICENSE' },
      // machine-readable API reference for coding assistants — generated by
      // `nx run docs-tools:llms`, read from
      // node_modules/@oge-ui/scheduler-engine/llms.txt
      { input: 'packages/scheduler-engine', output: '.', glob: 'llms.txt' },
    ],
  },
  {},
);
