// @oge-ui/kanban-engine — the framework-free Kanban engine both render layers
// run (ADR 0003). Explicit named exports only (house rule).
export {
  applyMoveToItem,
  deriveColumns,
  filterCards,
  groupBoard,
  normalizeCard,
  normalizeCards,
  orderBetween,
  orderColumns,
  renumberPatches,
  resolveKanbanFields,
  toKanbanAccessor,
  withFieldValue,
  type KanbanCard,
  type KanbanColumnDef,
  type KanbanColumnGroup,
  type KanbanFieldExpr,
  type KanbanFieldExprs,
  type KanbanFieldKey,
  type KanbanMoveTarget,
  type KanbanSwimlane,
  type ResolvedKanbanFields,
} from './lib/board-model';
export {
  columnReorderIndex,
  edgeScrollVelocity,
  hitTestCell,
  insertionIndexAt,
  type KanbanCellRect,
  type RectLike,
} from './lib/drag-math';
export {
  computeColumnWindow,
  type KanbanColumnWindow,
} from './lib/virtual-column';
export { previewCount, wipState, type KanbanWipState } from './lib/wip';
export {
  beginKanbanGesture,
  prepareKanbanTouchDrag,
  type KanbanGestureCallbacks,
} from './lib/gesture';
export {
  OGE_DEFAULT_KANBAN_CONFIG,
  OGE_DEFAULT_KANBAN_MESSAGES,
  mergeOgeKanbanMessages,
  resolveOgeKanbanConfig,
  type OgeKanbanAnnouncementMessages,
  type OgeKanbanBoardMessages,
  type OgeKanbanConfig,
  type OgeKanbanConfigInput,
  type OgeKanbanDialogMessages,
  type OgeKanbanMenuMessages,
  type OgeKanbanMessages,
  type OgeKanbanToolbarMessages,
} from './lib/config';
export type {
  OgeKanbanCard,
  OgeKanbanCardAddedEvent,
  OgeKanbanCardAddingEvent,
  OgeKanbanCardColorMode,
  OgeKanbanCardDeletedEvent,
  OgeKanbanCardDeletingEvent,
  OgeKanbanCardEvent,
  OgeKanbanCardMovedEvent,
  OgeKanbanCardMovingEvent,
  OgeKanbanCardUpdatedEvent,
  OgeKanbanCardUpdatingEvent,
  OgeKanbanColumn,
  OgeKanbanColumnAddedEvent,
  OgeKanbanColumnAddingEvent,
  OgeKanbanColumnReorderedEvent,
  OgeKanbanEditDialogShowingEventBase,
  OgeKanbanFieldExpr,
} from './lib/types';
export {
  KANBAN_EMPTY_EDITOR_CHOICES,
  buildKanbanEditorChoices,
  buildKanbanEditorItems,
  buildKanbanItem,
  kanbanEditorModelFrom,
  newKanbanEditorModel,
  newKanbanItemBase,
  type KanbanEditorChoices,
  type KanbanEditorModel,
  type KanbanEditorResult,
  type KanbanMappedFields,
} from './lib/editor';
export {
  KANBAN_CARD_GAP,
  KANBAN_COLLAPSED_TRACK,
  KANBAN_DEFAULT_CARD_HEIGHT,
  KANBAN_DEFAULT_CELL_HEIGHT,
  formatKanbanDue,
  formatKanbanMessage,
  isKanbanLegalTarget,
  isKanbanOverdue,
  kanbanCardActionLabel,
  kanbanCardLabel,
  kanbanCardShortcuts,
  kanbanCellKey,
  kanbanCellLabel,
  kanbanCellWindow,
  kanbanColumnCounts,
  kanbanColumnTitle,
  kanbanColumnWip,
  kanbanFocusableKeys,
  kanbanGridTemplate,
  kanbanInitials,
  kanbanMoveTargets,
  kanbanScrollIntoViewTop,
  resolveKanbanColumns,
  type KanbanCapabilities,
  type KanbanCellScroll,
  type KanbanColumnsInput,
  type KanbanColumnsResult,
} from './lib/board-view';
export {
  commitKanbanMove,
  findKanbanCard,
  isKanbanCardShifted,
  isKanbanMenuAvailable,
  kanbanCardKeyRoute,
  kanbanColumnOrderPreview,
  kanbanDropIndex,
  kanbanKeyboardMove,
  kanbanNavigationTarget,
  kanbanNewColumn,
  kanbanToolbarAddColumn,
  planKanbanMove,
  toggleKanbanKey,
  type KanbanCardKeyInput,
  type KanbanCardPosition,
  type KanbanDragState,
  type KanbanDragTarget,
  type KanbanKeyboardMove,
  type KanbanMoveCommit,
  type KanbanMovePlan,
} from './lib/interaction';
export {
  focusFirstKanbanMenuItem,
  focusKanbanCard,
  focusOwningKanbanCard,
  isKanbanCardContentTarget,
  kanbanAutoScrollStep,
  kanbanCssEscape,
  kanbanHeaderCenters,
  measureKanbanCells,
  measureKanbanDragGeometry,
  resolveKanbanDragTarget,
  scrollKanbanCell,
  startKanbanFrameLoop,
  stepKanbanMenuFocus,
  syncKanbanCardTabStops,
  type KanbanDragGeometry,
  type KanbanDragOrigin,
} from './lib/dom';
