// @oge-ui/kanban-engine — the framework-free Kanban engine both render layers
// run (ADR 0003). Explicit named exports only (house rule).
export {
  applyMoveToItem,
  deriveColumns,
  filterCards,
  groupBoard,
  normalizeCard,
  normalizeCards,
  normalizeKanbanChecklist,
  orderBetween,
  orderColumns,
  renumberPatches,
  resolveKanbanFields,
  toKanbanAccessor,
  withFieldValue,
  type KanbanCard,
  type KanbanChecklistItem,
  type KanbanColumnDef,
  type KanbanColumnGroup,
  type KanbanFieldExpr,
  type KanbanFieldExprs,
  type KanbanFieldKey,
  type KanbanMoveTarget,
  type KanbanSwimlane,
  type ResolvedKanbanFields,
} from './lib/board-model';
export {
  columnReorderIndex,
  edgeScrollVelocity,
  hitTestCell,
  insertionIndexAt,
  type KanbanCellRect,
  type RectLike,
} from './lib/drag-math';
export {
  computeColumnWindow,
  type KanbanColumnWindow,
} from './lib/virtual-column';
export { previewCount, wipState, type KanbanWipState } from './lib/wip';
export {
  beginKanbanGesture,
  prepareKanbanTouchDrag,
  type KanbanGestureCallbacks,
} from './lib/gesture';
export {
  OGE_DEFAULT_KANBAN_CONFIG,
  OGE_DEFAULT_KANBAN_MESSAGES,
  fillKanbanMessages,
  mergeOgeKanbanMessages,
  resolveOgeKanbanConfig,
  type OgeKanbanAnnouncementMessages,
  type OgeKanbanBoardMessages,
  type OgeKanbanConfig,
  type OgeKanbanConfigInput,
  type OgeKanbanDialogMessages,
  type OgeKanbanExportMessages,
  type OgeKanbanMenuMessages,
  type OgeKanbanMessages,
  type OgeKanbanResolvedMessages,
  type OgeKanbanToolbarMessages,
} from './lib/config';
export {
  KANBAN_DEFAULT_PRIORITY_ORDER,
  applyKanbanFilters,
  compileKanbanFilter,
  isKanbanFilterChipActive,
  isKanbanFilterEmpty,
  kanbanActiveSort,
  kanbanColumnSortSpec,
  kanbanFilterChoices,
  kanbanPriorityRank,
  kanbanSortComparer,
  setKanbanColumnSort,
  sortKanbanLanes,
  toggleKanbanFilterChip,
  type KanbanFilterChoices,
  type OgeKanbanColumnSort,
  type OgeKanbanColumnSortSpec,
  type OgeKanbanFilter,
  type OgeKanbanFilterChipKind,
  type OgeKanbanFilterExpression,
  type OgeKanbanSortField,
} from './lib/filter-sort';
export {
  kanbanAnchorIndex,
  kanbanBoardOrder,
  kanbanCarriedCards,
  kanbanMultiMoveAnchor,
  kanbanOrderKeys,
  kanbanSelectCard,
  kanbanSelectCell,
  kanbanSelectionShortcut,
  type KanbanSelectModifiers,
  type KanbanSelection,
  type KanbanSelectionShortcut,
  type OgeKanbanSelectionMode,
} from './lib/selection';
export {
  KANBAN_DEFAULT_UNDO_LIMIT,
  KanbanHistory,
  invertKanbanOp,
  isKanbanEditingTarget,
  kanbanHistoryShortcut,
  type KanbanHistoryOp,
  type KanbanHistoryPlace,
} from './lib/history';
export {
  isInsideKanbanHost,
  kanbanBoardPeers,
  kanbanPeerAt,
  nextKanbanBoardId,
  registerKanbanBoard,
  type KanbanBoardPeer,
  type KanbanTransfer,
  type KanbanTransferResult,
} from './lib/board-registry';
export {
  canEditKanbanTitle,
  formatKanbanCount,
  kanbanChecklistLabel,
  kanbanChecklistProgress,
  kanbanChecklistToggle,
  kanbanQuickAddItem,
  kanbanTitleUpdate,
} from './lib/card-ops';
export {
  buildKanbanCsv,
  buildKanbanExportRows,
  downloadKanbanText,
  kanbanChecklistCell,
  type OgeKanbanCsvOptions,
  type OgeKanbanExportData,
  type OgeKanbanExportOptions,
  type OgeKanbanExportRow,
} from './lib/export';
export type {
  OgeKanbanCard,
  OgeKanbanCardAddedEvent,
  OgeKanbanCardAddingEvent,
  OgeKanbanCardColorMode,
  OgeKanbanCardDeletedEvent,
  OgeKanbanCardDeletingEvent,
  OgeKanbanCardEvent,
  OgeKanbanCardMovedEvent,
  OgeKanbanCardMovingEvent,
  OgeKanbanCardUpdatedEvent,
  OgeKanbanCardUpdatingEvent,
  OgeKanbanColumn,
  OgeKanbanColumnAddedEvent,
  OgeKanbanColumnAddingEvent,
  OgeKanbanColumnReorderedEvent,
  OgeKanbanCardTransferredEvent,
  OgeKanbanCardTransferringEvent,
  OgeKanbanEditDialogShowingEventBase,
  OgeKanbanFieldExpr,
} from './lib/types';
export {
  KANBAN_EMPTY_EDITOR_CHOICES,
  buildKanbanEditorChoices,
  buildKanbanEditorItems,
  buildKanbanItem,
  kanbanEditorModelFrom,
  newKanbanEditorModel,
  newKanbanItemBase,
  type KanbanEditorChoices,
  type KanbanEditorModel,
  type KanbanEditorResult,
  type KanbanMappedFields,
} from './lib/editor';
export {
  KANBAN_CARD_GAP,
  KANBAN_COLLAPSED_TRACK,
  KANBAN_DEFAULT_CARD_HEIGHT,
  KANBAN_DEFAULT_CELL_HEIGHT,
  formatKanbanDue,
  formatKanbanMessage,
  isKanbanLegalTarget,
  isKanbanOverdue,
  kanbanCardActionLabel,
  kanbanCardLabel,
  kanbanCardShortcuts,
  kanbanCellCounts,
  kanbanCellKey,
  kanbanCellLabel,
  kanbanCellWindow,
  kanbanCellWip,
  kanbanColumnCounts,
  kanbanLaneCounts,
  kanbanLaneWip,
  kanbanColumnTitle,
  kanbanColumnWip,
  kanbanFocusableKeys,
  kanbanGridTemplate,
  kanbanInitials,
  kanbanMoveTargets,
  kanbanScrollIntoViewTop,
  resolveKanbanColumns,
  type KanbanCapabilities,
  type KanbanCellScroll,
  type KanbanColumnsInput,
  type KanbanColumnsResult,
} from './lib/board-view';
export {
  commitKanbanMove,
  findKanbanCard,
  isKanbanCardShifted,
  isKanbanMenuAvailable,
  kanbanCardKeyRoute,
  kanbanColumnOrderPreview,
  kanbanDropIndex,
  kanbanKeyboardMove,
  kanbanLogicalKey,
  kanbanNavigationTarget,
  kanbanNewColumn,
  kanbanToolbarAddColumn,
  planKanbanMove,
  toggleKanbanKey,
  type KanbanCardKeyInput,
  type KanbanCardPosition,
  type KanbanDragState,
  type KanbanDragTarget,
  type KanbanKeyboardMove,
  type KanbanMoveCommit,
  type KanbanMovePlan,
} from './lib/interaction';
export {
  focusFirstKanbanMenuItem,
  focusKanbanCard,
  focusOwningKanbanCard,
  isKanbanCardContentTarget,
  kanbanAutoScrollStep,
  kanbanCssEscape,
  kanbanHeaderCenters,
  measureKanbanCells,
  measureKanbanDragGeometry,
  resolveKanbanDragTarget,
  scrollKanbanCell,
  startKanbanFrameLoop,
  stepKanbanMenuFocus,
  syncKanbanCardTabStops,
  watchKanbanDirection,
  type KanbanDragGeometry,
  type KanbanDragOrigin,
} from './lib/dom';
