const { withNx } = require('@nx/rollup/with-nx');

module.exports = withNx(
  {
    main: './src/index.ts',
    // Optional-peer entry points: the pure `.xlsx` / `.pdf` builders shared by
    // both render layers. Separate entries so `exceljs` and `jspdf` are pulled
    // in only by an app that actually imports one of them.
    // note: workspace-relative, and each file name becomes the entry name —
    // `<dir>/index.ts` would collide with the main `index` entry
    additionalEntryPoints: [
      'packages/behavior/src/export-excel.ts',
      'packages/behavior/src/export-pdf.ts',
    ],
    outputPath: '../../dist/packages/behavior',
    tsConfig: './tsconfig.lib.json',
    compiler: 'swc',
    format: ['cjs', 'esm'],
    // note: '{projectRoot}' tokens are not interpolated inside rollup.config —
    // the path must be spelled out relative to the workspace root
    assets: [
      { input: 'packages/behavior', output: '.', glob: '*.md' },
      { input: 'packages/behavior', output: '.', glob: 'LICENSE' },
      // machine-readable API reference for coding assistants — generated by
      // `nx run docs-tools:llms`, read from node_modules/@oge-ui/behavior/llms.txt
      { input: 'packages/behavior', output: '.', glob: 'llms.txt' },
    ],
  },
  {
    // Provide additional rollup configuration here. See: https://rollupjs.org/configuration-options
    // e.g.
    // output: { sourcemap: true },
  },
);
