// Public API of @oge-ui/charts-engine (commercial — see LICENSE).
//
// The framework-free engine both chart render layers run (ADR 0003):
// `@oge-ui/charts` (Angular) and `@oge-ui/react-charts` (React) import it,
// and neither carries chart logic of its own. Explicit named exports only
// (house rule). The image exporter is the separate `./export-image` entry.

/* ---------------- public types, palette, config ---------------- */

export {
  OGE_CHART_PALETTE,
  type OgeChartAnimationEasing,
  type OgeChartAnimationOptions,
  type OgeChartAnnotation,
  type OgeChartAxisBreak,
  type OgeChartAxisLabelOptions,
  type OgeChartAxisOptions,
  type OgeChartAxisStrip,
  type OgeChartAxisType,
  type OgeChartConstantLine,
  type OgeChartCrosshairOptions,
  type OgeChartCustomPeriod,
  type OgeChartDateInterval,
  type OgeChartExportData,
  type OgeChartLegendClickEvent,
  type OgeChartLegendItem,
  type OgeChartLabelFormat,
  type OgeChartLabelOverlap,
  type OgeChartLegendOptions,
  type OgeChartMinorTickOptions,
  type OgeChartPane,
  type OgeChartPeriod,
  type OgeChartPieSliceEvent,
  type OgeChartPoint,
  type OgeChartPointEvent,
  type OgeChartPointRef,
  type OgeChartRange,
  type OgeChartSeriesEvent,
  type OgeChartSeriesInput,
  type OgeChartSeriesType,
  type OgeChartSmallValuesGrouping,
  type OgeChartStripLine,
  type OgeChartTickInterval,
  type OgeChartTooltipOptions,
  type OgeChartTooltipShowingEvent,
} from './lib/charts-types';
export {
  OGE_DEFAULT_CHARTS_CONFIG,
  OGE_DEFAULT_CHARTS_MESSAGES,
  formatOgeChartMessage,
  mergeOgeChartsMessages,
  resolveOgeChartsConfig,
  type OgeChartsAnnouncementMessages,
  type OgeChartsAriaMessages,
  type OgeChartsConfig,
  type OgeChartsConfigInput,
  type OgeChartsMessages,
  type OgeChartsPeriodMessages,
} from './lib/charts-config';

/* ---------------- view models ---------------- */

export {
  buildCartesianData,
  buildCartesianScene,
  cartesianActivePoints,
  cartesianAriaLabel,
  cartesianCrosshair,
  cartesianDragArgDelta,
  cartesianExportData,
  cartesianHoverAt,
  cartesianLabelTransform,
  cartesianNearestSeries,
  cartesianPanRange,
  cartesianPinchRange,
  cartesianPlotArgPx,
  cartesianPointAnnouncement,
  cartesianSelectionRange,
  cartesianSeriesEnterOrigin,
  cartesianSeriesPane,
  cartesianSrRows,
  cartesianTooltip,
  cartesianWheelRange,
  cartesianZoomRect,
  cartesianZoomTo,
  chartArgumentText,
  chartDragMode,
  chartMarkerRadius,
  chartSeriesColor,
  chartSeriesGroupOpacity,
  chartTouchAction,
  chartTouchGestures,
  chartValueAxesList,
  chartValueText,
  chartWheelZoomEnabled,
  chartZoomSelectionRect,
  detectArgumentKind,
  isChartPointSelected,
  mergeChartSeriesInputs,
  nextChartSelection,
  type OgeCartesianData,
  type OgeCartesianDataInput,
  type OgeCartesianHoverState,
  type OgeCartesianScene,
  type OgeCartesianSceneInput,
  type OgeChartAnnotationVm,
  type OgeChartAxisLabelVm,
  type OgeChartAxisTick,
  type OgeChartAxisTitleVm,
  type OgeChartCrosshairVm,
  type OgeChartLegendEntry,
  type OgeChartPlotRect,
  type OgeChartRenderBar,
  type OgeChartRenderCandle,
  type OgeChartRenderLabel,
  type OgeChartRenderMarker,
  type OgeChartRenderSeries,
  type OgeChartSrRow,
  type OgeChartStripRect,
  type OgeChartTooltipVm,
  type OgeChartValueAxisVm,
} from './lib/cartesian-model';
export {
  CHART_PANE_GAP,
  bindChartPaneAxes,
  chartPaneAt,
  chartPaneList,
  chartValueAxisSlots,
  layoutChartGuides,
  layoutChartPanes,
  type OgeChartAxisBinding,
  type OgeChartAxisSlots,
  type OgeChartBreakMarkerVm,
  type OgeChartGridLineVm,
  type OgeChartGuideLabelVm,
  type OgeChartGuideVm,
  type OgeChartPaneVm,
} from './lib/cartesian-layout';
export {
  createChartFrame,
  detectChartRtl,
  frameLabelAnchor,
  frameLabelBaseline,
  frameLine,
  frameLogical,
  framePoint,
  frameRect,
  frameTextTransform,
  type OgeChartFrame,
  type OgeChartLineVm,
  type OgeChartRectVm,
  type OgeChartXY,
} from './lib/chart-frame';
export {
  CHART_DRAW_IN_MS,
  chartAnimationVars,
  chartPrefersReducedMotion,
  chartSeriesEnterOrigin,
  resolveChartAnimation,
  type OgeChartResolvedAnimation,
} from './lib/chart-animation';
export {
  buildPieScene,
  pieAriaLabel,
  pieLabelText,
  pieSelectedAnnouncement,
  pieTooltip,
  pieValueText,
  togglePieSlice,
  type OgeChartFieldExpr,
  type OgePieGeometry,
  type OgePieScene,
  type OgePieSceneInput,
  type OgePieSliceVm,
  type OgePieTooltipVm,
} from './lib/pie-model';
export {
  buildPolarData,
  buildPolarScene,
  nextPolarSelection,
  polarPointAnnouncement,
  polarPointIndex,
  polarSrRows,
  polarTooltip,
  type OgePolarData,
  type OgePolarDataInput,
  type OgePolarHover,
  type OgePolarMarkerVm,
  type OgePolarRingVm,
  type OgePolarScene,
  type OgePolarSceneInput,
  type OgePolarSeriesVm,
  type OgePolarSpokeVm,
  type OgePolarTooltipVm,
} from './lib/polar-model';
export {
  buildRangeSelectorData,
  buildRangeSelectorScene,
  commitRangeSelection,
  detectRangeSelectorKind,
  rangeCenteredAt,
  rangeHandleDragRange,
  rangeSelectorAnnouncement,
  rangeSelectorDeltaValue,
  rangeSelectorEffective,
  rangeSelectorLabel,
  rangeSelectorPeriodRange,
  rangeSelectorPeriods,
  rangeSelectorWindowPx,
  rangeWindowDragRange,
  type OgeRangeSelectorData,
  type OgeRangeSelectorDataInput,
  type OgeRangeSelectorPeriodVm,
  type OgeRangeSelectorScene,
  type OgeRangeSelectorSceneInput,
  type OgeRangeSelectorSeriesVm,
} from './lib/range-selector-model';

/* ---------------- interaction ---------------- */

export {
  cartesianKeyCommand,
  polarKeyCommand,
  rangeHandleKeyRange,
  type OgeChartKeyCommand,
  type OgeChartKeyContext,
} from './lib/chart-keyboard';
export {
  beginChartGesture,
  createChartPinchTracker,
  type ChartGestureCallbacks,
  type ChartGestureHandle,
  type ChartPinchCallbacks,
  type ChartPinchPoint,
  type ChartPinchTracker,
} from './lib/chart-gesture';
export {
  measureChartElement,
  observeChartSize,
  type OgeChartSize,
} from './lib/chart-size';

/* ---------------- kernel ---------------- */

export {
  categoryBandPx,
  clampRange,
  createCategoryScale,
  createLinearScale,
  createLogScale,
  createTimeScale,
  logTicks,
  niceStep,
  niceTicks,
  pickTimeUnit,
  timeTicks,
  type ChartRange,
  type ChartScale,
  type ChartScaleKind,
  type TimeTickUnit,
} from './lib/scale';
export {
  buildSeries,
  collectCategories,
  isBarType,
  isStackedType,
  numericArgument,
  seriesValueExtent,
  type ChartFieldExpr,
  type ChartPoint,
  type ChartSeries,
  type ChartSeriesInput,
  type ChartSeriesType,
} from './lib/series-model';
export {
  candleGeometry,
  computeBarSlots,
  computeStacks,
  type BarSlot,
  type CandleGeometry,
  type StackedValue,
} from './lib/series-layout';
export {
  areaPath,
  baselineAreaPath,
  linePath,
  splinePath,
  steppedPoints,
  type PathPoint,
} from './lib/path-builder';
export { downsamplePath } from './lib/downsample';
export {
  decideLabelLayout,
  hideOverlappingLabels,
  numberFormat,
  siFormat,
  timeTickFormatter,
  type LabelLayoutDecision,
  type LabelOverlapMode,
} from './lib/tick-format';
export {
  buildArgumentIndex,
  nearestIndex,
  type ArgumentIndex,
} from './lib/hit-test';
export { panRange, rangeFromSelection, zoomRangeAt } from './lib/zoom-math';
export {
  CHART_BREAK_GAP_PX,
  addChartDateInterval,
  applyChartTickOptions,
  chartDateIntervalUnit,
  chartMinorTicks,
  createBrokenLinearScale,
  isChartDateInterval,
  normalizeChartBreaks,
  offsetChartScale,
  type ChartScaleBreak,
  type ChartTickOptions,
} from './lib/axis-scale';
export {
  applyChartLabelTemplate,
  chartArgumentLabelFormatter,
  chartValueLabelFormatter,
} from './lib/axis-labels';
export {
  buildPieSlices,
  groupSmallValues,
  layoutPieLabels,
  pieSliceAt,
  sliceArcPath,
  type GroupedPieValue,
  type PieLabelPosition,
  type PieSlice,
  type PieSmallValuesGrouping,
} from './lib/pie-layout';
export {
  angleForIndex,
  polarToCartesian,
  radarGridPath,
  radarLoopPath,
  type PolarXY,
} from './lib/polar-layout';
